// Swedish translation by Benjamin Horn · https://benjaminhorn.io/
// Dutch translation by Osman Temiz · u/MANllAC
// Polish translation by Mateusz K · u/DiVine92
// Russian translation by OemDef · u/OemDef
// Simplified chinese translation by Shuhuai Cao · github.com/csh980717
// Brazilian translation by Adilson Santos · github.com/adilsonfsantos
// Slovak translation by Roman Bartík
// German translation by Bernhard Wittmann · https://bernhardwittmann.com
// Italian translation by Trazalca · github.com/Trazalca
// Spanish translation by José Alberto · github.com/joatb

// base
// "": {
// fr: "",
// sv: "",
// nl: "",
// pl: "",
// pt_BR: "",
// ru: "",
// zh_CN: "",
// sk: "",
// de: "",
// it: "",
// es: "",
// no: ""}

function askfordict() {
	return {
		'New Tab': {
			fr: 'Nouvel onglet',
			sv: 'Ny flik',
			nl: 'Nieuw tabblad',
			pl: 'Nowa Karta',
			pt_BR: 'Nova Aba',
			ru: 'Новая вкладка',
			zh_CN: '新标签页',
			sk: 'Nová karta',
			de: 'Neuer Tab',
			it: 'Nuova scheda',
			es: 'Nueva Pestaña',
			no: 'New Tab',
		},
		SETTINGS: {
			fr: 'Réglages',
			sv: 'Inställningar',
			nl: 'Instellingen',
			pl: 'Ustawienia',
			pt_BR: 'Configurações',
			ru: 'Настройки',
			zh_CN: '设置',
			sk: 'Nastavenia',
			de: 'Einstellungen',
			it: 'Impostazioni',
			es: 'Configuración',
			no: 'SETTINGS',
		},
		'Show all settings': {
			fr: 'Afficher tous les réglages',
			sv: 'Show all settings',
			nl: 'Show all settings',
			pl: 'Show all settings',
			pt_BR: 'Show all settings',
			ru: 'Show all settings',
			zh_CN: 'Show all settings',
			sk: 'Show all settings',
			de: 'Show all settings',
			it: 'Show all settings',
			es: 'Mostrar todos los ajustes',
			no: 'Show all settings',
		},
		'QUICK LINKS': {
			fr: 'Liens favoris',
			sv: 'Snabblänkar',
			nl: 'Snelle links',
			pl: 'Ulubione Witryny',
			pt_BR: 'Links Rápidos',
			ru: 'Закладки',
			zh_CN: '快速链接',
			sk: 'RÝCHLA NAVIGÁCIA',
			de: 'Quick Links',
			it: 'Collegamenti rapidi',
			es: 'Enlaces favoritos',
			no: 'QUICK LINKS',
		},
		'Quick Links are bookmarks integrated into Bonjourr. You can edit your Quick Links by right clicking on their icon.': {
			fr: "Vous pouvez gérer vos favoris directement dans Bonjourr. Éditez ou supprimez un lien favori en faisant un clic droit sur l'icône.",
			sv: 'Quick Links are bookmarks integrated into Bonjourr. You can edit your Quick Links by right clicking on their icon.',
			nl: 'Quick Links are bookmarks integrated into Bonjourr. You can edit your Quick Links by right clicking on their icon.',
			pl: 'Quick Links are bookmarks integrated into Bonjourr. You can edit your Quick Links by right clicking on their icon.',
			pt_BR: 'Quick Links are bookmarks integrated into Bonjourr. You can edit your Quick Links by right clicking on their icon.',
			ru: 'Quick Links are bookmarks integrated into Bonjourr. You can edit your Quick Links by right clicking on their icon.',
			zh_CN: 'Quick Links are bookmarks integrated into Bonjourr. You can edit your Quick Links by right clicking on their icon.',
			sk: 'Quick Links are bookmarks integrated into Bonjourr. You can edit your Quick Links by right clicking on their icon.',
			de: 'Quick Links are bookmarks integrated into Bonjourr. You can edit your Quick Links by right clicking on their icon.',
			it: 'Quick Links are bookmarks integrated into Bonjourr. You can edit your Quick Links by right clicking on their icon.',
			es: 'Quick Links are bookmarks integrated into Bonjourr. You can edit your Quick Links by right clicking on their icon.',
			no: 'Quick Links are bookmarks integrated into Bonjourr. You can edit your Quick Links by right clicking on their icon.',
		},
		Name: {
			fr: 'Nom',
			sv: 'Namn',
			nl: 'Naam',
			pl: 'Nazwa',
			pt_BR: 'Nome',
			ru: 'название',
			zh_CN: '名称',
			sk: 'názov',
			de: 'Name',
			it: 'nome',
			es: 'Nombre',
			no: 'Name',
		},
		Add: {
			fr: 'Ajouter',
			sv: 'Lägg till',
			nl: 'Voeg toe',
			pl: 'Dodaj',
			pt_BR: 'Adicionar',
			ru: 'Добавить',
			zh_CN: '添加',
			sk: 'Pridať',
			de: 'Hinzufügen',
			it: 'Aggiungere',
			es: 'Añadir',
			no: 'Add',
		},
		'Open in new tab by default': {
			fr: 'Ouvrir dans un nouvel onglet par défaut',
			zh_CN: '默认在新标签页打开链接',
			sv: 'Open in new tab by default',
			nl: 'Open in new tab by default',
			pl: 'Otwieraj domyślnie w nowej karcie',
			pt_BR: 'Abrir em nova aba por padrão',
			ru: 'Open in new tab by default',
			sk: 'Predvolene otvoriť v novej karte',
			de: 'Standardmäßig in einem neuen Tab öffnen',
			it: 'Apri in una nuova scheda come impostazione predefinita',
			es: 'Abrir en una nueva pestaña por defecto',
			no: 'Open in new tab by default',
		},
		'Links per row': {
			fr: 'Liens par ligne',
			sv: 'Links per row',
			nl: 'Links per row',
			pl: 'Links per row',
			pt_BR: 'Links por linha',
			ru: 'Links per row',
			zh_CN: 'Links per row',
			sk: 'Links per row',
			de: 'Links per row',
			it: 'Links per row',
			es: 'Enlaces por fila',
			no: 'Links per row',
		},
		VISUALS: {
			fr: 'Affichage',
			sv: 'Visuella',
			nl: 'Vormgeving',
			pl: 'Wygląd',
			pt_BR: 'Visuais',
			ru: 'Внешний вид',
			zh_CN: '外观',
			sk: 'VZHĽAD',
			de: 'Bilder',
			it: 'Visualizzazione',
			es: 'Visualización',
			no: 'VISUALS',
		},
		'Background type': {
			fr: "Type d'arrière-plan",
			sv: 'Background type',
			nl: 'Background type',
			pl: 'Rodzaj tła',
			pt_BR: 'Tipo de background',
			ru: 'Background type',
			zh_CN: '背景类型',
			sk: 'Pozadie',
			de: 'Hintergrund Typ',
			it: 'Tipo di sfondo',
			es: 'Tipo de fondo',
			no: 'Background type',
		},
		Default: {
			fr: 'Par défaut',
			sv: 'Default',
			nl: 'Default',
			pl: 'Domyślne',
			pt_BR: 'Padrão',
			ru: 'Default',
			zh_CN: '默认',
			sk: 'Default',
			de: 'Standard',
			it: 'Predefinito',
			es: 'Por Defecto',
			no: 'Default',
		},
		Dynamic: {
			fr: 'Dynamique',
			sv: 'Dynamic',
			nl: 'Dynamic',
			pl: 'Dynamiczne',
			pt_BR: 'Dinâmico',
			ru: 'Dynamic',
			zh_CN: '动态',
			sk: 'Dynamic',
			de: 'Dynamisch',
			it: 'Dinamico',
			es: 'Dinámico',
			no: 'Dynamic',
		},
		Custom: {
			fr: 'Personnalisé',
			sv: 'Custom',
			nl: 'Custom',
			pl: 'Użytkownika',
			pt_BR: 'Personalizado',
			ru: 'Custom',
			zh_CN: '自定义',
			sk: 'Custom',
			de: 'Benutzerdefiniert',
			it: 'Personalizzato',
			es: 'Personalizado',
			no: 'Custom',
		},
		Frequency: {
			fr: 'Fréquence',
			sv: 'Frequency',
			nl: 'Frequency',
			pl: 'Częstotliwość',
			pt_BR: 'Frequência',
			ru: 'Frequency',
			zh_CN: '背景切换频率',
			sk: 'Frequency',
			de: 'Häufigkeit',
			it: 'Frequenza',
			es: 'Frequencia',
			no: 'Frequency',
		},
		'Every tab': {
			fr: 'Chaque onglet',
			sv: 'Every tab',
			nl: 'Every tab',
			pl: 'Co zakładkę',
			pt_BR: 'A cada aba',
			ru: 'Every tab',
			zh_CN: '每次新建标签页',
			sk: 'Every tab',
			de: 'Jedes Tab',
			it: 'Ogni scheda',
			es: 'Cada Pestaña',
			no: 'Every tab',
		},
		'Every hour': {
			fr: 'Chaque heure',
			sv: 'Every hour',
			nl: 'Every hour',
			pl: 'Co godzinę',
			pt_BR: 'A cada hora',
			ru: 'Every hour',
			zh_CN: '每小时',
			sk: 'Every hour',
			de: 'Jede Stunde',
			it: 'Ogni ora',
			es: 'Cada hora',
			no: 'Every hour',
		},
		'Every day': {
			fr: 'Chaque jour',
			sv: 'Every day',
			nl: 'Every day',
			pl: 'Codziennie',
			pt_BR: 'Todos os dias',
			ru: 'Every day',
			zh_CN: '每天',
			sk: 'Every day',
			de: 'Jeden Tag',
			it: 'Ogni giorno',
			es: 'Cada día',
			no: 'Every day',
		},
		Pause: {
			fr: 'Pause',
			sv: 'Pause',
			nl: 'Pause',
			pl: 'Pauza',
			pt_BR: 'Parar',
			ru: 'Pause',
			zh_CN: '不切换',
			sk: 'Pause',
			de: 'Pause',
			it: 'Pausa',
			es: 'Pausa',
			no: 'Pause',
		},
		'Unsplash collection': {
			fr: 'Collection Unsplash',
			sv: 'Unsplash collection',
			nl: 'Unsplash collection',
			pl: 'Unsplash collection',
			pt_BR: 'Unsplash collection',
			ru: 'Unsplash collection',
			zh_CN: 'Unsplash collection',
			sk: 'Unsplash collection',
			de: 'Unsplash collection',
			it: 'Unsplash collection',
			es: 'Unsplash collection',
			no: 'Unsplash collection',
		},
		'Blur intensity': {
			fr: 'Intensité du flou',
			sv: 'Oskärpans intensitet',
			nl: 'Intensiviteit van het blur effect',
			pl: 'Intensywnośc rozmycia',
			pt_BR: 'Intensidade do desfoque',
			ru: 'Степень размытия фона',
			zh_CN: '模糊度',
			sk: 'Intenzita rozmazania',
			de: 'Weichzeichner Stärke',
			it: 'Intensità della sfocatura',
			es: 'Intensidad de desenfoque',
			no: 'Blur intensity',
		},
		Brightness: {
			fr: 'Luminosité',
			sv: 'Brightness',
			nl: 'Brightness',
			pl: 'Jasność',
			pt_BR: 'Brilho',
			ru: 'Brightness',
			zh_CN: '亮度',
			sk: 'Brightness',
			de: 'Helligkeit',
			it: 'Luminosità',
			es: 'Brillo',
			no: 'Brightness',
		},
		'Dark mode': {
			fr: 'Mode sombre',
			sv: 'Mörkt läge',
			nl: 'Nacht modus',
			pl: 'Tryb ciemny',
			pt_BR: 'Modo noturno',
			ru: 'Тёмная тема',
			zh_CN: '深色模式',
			sk: 'Tmavý režim',
			de: 'Dunkelmodus',
			it: 'Modalità notturna',
			es: 'Modo Oscuro',
			no: 'Dark mode',
		},
		'At night': {
			fr: 'La nuit',
			sv: 'På natten',
			nl: 'Nachts',
			pl: 'W nocy',
			pt_BR: 'à noite',
			ru: 'ночью',
			zh_CN: '只在夜间',
			sk: 'V noci',
			de: 'Nachts',
			it: 'Di notte',
			es: 'De noche',
			no: 'At night',
		},
		System: {
			fr: 'Système',
			sv: 'Systemet',
			nl: 'Systeem',
			pl: 'Systemem',
			pt_BR: 'Sistema',
			ru: 'системой',
			zh_CN: '系统设置',
			sk: 'Systému',
			de: 'Systemeinstellungen',
			it: 'Sistema',
			es: 'Sistema',
			no: 'System',
		},
		Enabled: {
			fr: 'Activé',
			sv: 'Aktiverad',
			nl: 'Ingeschakeld',
			pl: 'Włączony',
			pt_BR: 'Ativado',
			ru: 'Включена',
			zh_CN: '开启',
			sk: 'Zapnuté',
			de: 'Aktiviert',
			it: 'Abilitato',
			es: 'Activado',
			no: 'Enabled',
		},
		Disabled: {
			fr: 'Désactivé',
			sv: 'Inaktiverad',
			nl: 'Uitgeschakeld',
			pl: 'Wyłączony',
			pt_BR: 'Desativado',
			ru: 'Выключена',
			zh_CN: '关闭',
			sk: 'Vypnuté',
			de: 'Deaktiviert',
			it: 'Disabilitato',
			es: 'Desactivado',
			no: 'Disabled',
		},
		'Hide elements': {
			fr: 'Cacher des éléments',
			sv: 'Hide elements',
			nl: 'Hide elements',
			pl: 'Hide elements',
			pt_BR: 'Esconder elementos',
			ru: 'Hide elements',
			zh_CN: 'Hide elements',
			sk: 'Hide elements',
			de: 'Hide elements',
			it: 'Hide elements',
			es: 'Esconder elementos',
			no: 'Hide elements',
		},
		Clock: {
			fr: 'Horloge',
			sv: 'Clock',
			nl: 'Clock',
			pl: 'Clock',
			pt_BR: 'Relógio',
			ru: 'Clock',
			zh_CN: 'Clock',
			sk: 'Clock',
			de: 'Clock',
			it: 'Clock',
			es: 'Reloj',
			no: 'Clock',
		},
		Date: {
			fr: 'Date',
			sv: 'Date',
			nl: 'Date',
			pl: 'Date',
			pt_BR: 'Data',
			ru: 'Date',
			zh_CN: 'Date',
			sk: 'Date',
			de: 'Date',
			it: 'Date',
			es: 'Fecha',
			no: 'Date',
		},
		Greetings: {
			fr: 'Horloge',
			sv: 'Greetings',
			nl: 'Greetings',
			pl: 'Greetings',
			pt_BR: 'Cumprimentos',
			ru: 'Greetings',
			zh_CN: 'Greetings',
			sk: 'Greetings',
			de: 'Greetings',
			it: 'Greetings',
			es: 'Saludos',
			no: 'Greetings',
		},
		Weather: {
			fr: 'Météo',
			sv: 'Weather',
			nl: 'Weather',
			pl: 'Weather',
			pt_BR: 'Tempo',
			ru: 'Weather',
			zh_CN: 'Weather',
			sk: 'Weather',
			de: 'Weather',
			it: 'Weather',
			es: 'Tiempo',
			no: 'Weather',
		},
		Icon: {
			fr: 'Icône',
			sv: 'Icon',
			nl: 'Icon',
			pl: 'Icon',
			pt_BR: 'Ícone',
			ru: 'Icon',
			zh_CN: 'Icon',
			sk: 'Icon',
			de: 'Icon',
			it: 'Icon',
			es: 'Icono',
			no: 'Icon',
		},
		'Quick Links': {
			fr: 'Liens favoris',
			sv: 'Quick Links',
			nl: 'Quick Links',
			pl: 'Quick Links',
			pt_BR: 'Links Rápidos',
			ru: 'Quick Links',
			zh_CN: 'Quick Links',
			sk: 'Quick Links',
			de: 'Quick Links',
			it: 'Quick Links',
			es: 'Enlaces favoritos',
			no: 'Quick Links',
		},
		'Settings icon': {
			fr: 'Icône réglages',
			sv: 'Settings icon',
			nl: 'Settings icon',
			pl: 'Settings icon',
			pt_BR: 'Settings icon',
			ru: 'Settings icon',
			zh_CN: 'Settings icon',
			sk: 'Settings icon',
			de: 'Settings icon',
			it: 'Settings icon',
			es: 'Configuración icono',
			no: 'Settings icon',
		},
		'Upload background here': {
			fr: 'Ajoutez votre arrière-plan',
			sv: 'Upload background here',
			nl: 'Upload background here',
			pl: 'Upload background here',
			pt_BR: 'Suba o seu background aqui',
			ru: 'Upload background here',
			zh_CN: '上传背景',
			sk: 'Upload background here',
			de: 'Upload background here',
			it: 'Upload background here',
			es: 'Suba el fondo aquí',
			no: 'Upload background here',
		},
		'Analog clock': {
			fr: 'Horloge analogue',
			sv: 'Analog clock',
			nl: 'Analog clock',
			pl: 'Analog clock',
			pt_BR: 'Relógio Analógico',
			ru: 'Analog clock',
			zh_CN: 'Analog clock',
			sk: 'Analog clock',
			de: 'Analog clock',
			it: 'Analog clock',
			es: 'Reloj Analógico',
			no: 'Analog clock',
		},
		'Display Seconds': {
			fr: 'Afficher les secondes',
			sv: 'Display seconds',
			nl: 'Display seconds',
			pl: 'Display seconds',
			pt_BR: 'Mostrar segundos',
			ru: 'Display seconds',
			zh_CN: 'Display seconds',
			sk: 'Display seconds',
			de: 'Display seconds',
			it: 'Display seconds',
			es: 'Mostrar los segundos',
			no: 'Display Seconds',
		},
		Automatic: {
			fr: 'Automatique',
			sv: 'Automatiskt',
			nl: 'Automatisch ',
			pl: 'Automatycznie',
			pt_BR: 'Automático',
			ru: 'Автоматически',
			zh_CN: '自动设置',
			sk: 'Automatické',
			de: 'Automatisch',
			it: 'Automatico',
			es: 'Automático',
			no: 'Automatic',
		},
		WEATHER: {
			fr: 'Météo',
			sv: 'Väder',
			nl: 'Weer',
			pl: 'Pogoda',
			pt_BR: 'Tempo',
			ru: 'Погода',
			zh_CN: '天气',
			sk: 'POČASIE',
			de: 'Wetter',
			it: 'Meteo',
			es: 'Tiempo',
			no: 'WEATHER',
		},
		Geolocation: {
			fr: 'Géolocalisation',
			sv: 'Geolocation',
			nl: 'Locatie',
			pl: 'Geolokalizacja',
			pt_BR: 'Geolocalização',
			ru: 'Геолокация',
			zh_CN: '使用我的位置',
			sk: 'Geolokácia',
			de: 'Geolokalisierung',
			it: 'Geolocalizzazione',
			es: 'Geolocalización',
			no: 'Geolocation',
		},
		'City not found': {
			fr: 'Ville non trouvé',
			sv: 'Staden hittades inte',
			nl: 'Stad niet gevonden',
			pl: 'Zmień miasto',
			pt_BR: 'Cidade não encontrada',
			ru: 'Город не найден',
			zh_CN: '找不到城市',
			sk: 'Mesto nenájdené',
			de: 'Stadt nicht gefunden',
			it: 'Città non trovata',
			es: 'Ciudad no encontrada',
			no: 'City not found',
		},
		'Change city': {
			fr: 'Changer la ville',
			sv: 'Byt stad',
			nl: 'Verander locatie',
			pl: 'Zmień miasto',
			pt_BR: 'Mudar cidade',
			ru: 'Сменить город',
			zh_CN: '更改城市',
			sk: 'Zmeniť mesto',
			de: 'Stadt ändern',
			it: 'Cambia città',
			es: 'Cambiar ciudad',
			no: 'Change city',
		},
		// "Use this option if you don't want to enable geolocation.": {
		// 	fr: 'Utilisez cette option si vous ne souhaitez pas activer la géolocalisation.',
		// 	sv: 'Använd detta alternativ om du inte vill aktivera geolocation.',
		// 	nl: 'Gebruik deze optie als u geen locatie wilt gebruiken',
		// 	pl: 'Użyj tej opcji jesli nie chcesz włączyć geolokalizacji.',
		// 	pt_BR: 'Use esta opção se você não quer ativar a geolocalização',
		// 	ru: 'Если вы не хотите включать геолокацию – воспользуйтесь этой опцией.',
		// 	zh_CN: '如果不想根据您的位置自动设置天气，请使用该选项。',
		// 	sk: 'Túto možnosť použite, ak nechcete povoliť geolokáciu.',
		// 	de: 'Diese Option wählen, wenn du die Geolokalisierung nicht aktivieren willst',
		// 	it: 'Usa questa opzione se non vuoi abilitare la geolocalizzazione',
		// 	es: 'Usa esta opción si no quieres habilitar la geolocalización',
		// 	no: "Use this option if you don't want to enable geolocation.",
		// },
		'There was a problem': {
			fr: 'Il y a eu un problème',
			sv: 'Ett fel uppstod',
			nl: 'Er is een probleem',
			pl: 'Wystąpił problem',
			pt_BR: 'Houve um problema',
			ru: 'Возникла проблема',
			zh_CN: '出现错误',
			sk: 'Nastal problém',
			de: 'Ein Problem ist aufgetreten',
			it: "C'è stato un problema",
			es: 'Hubo un problema',
			no: 'There was a problem',
		},
		'Imperial units': {
			fr: 'Unités impériales',
			sv: 'Imperial enheter',
			nl: 'Empirische eenheden',
			pl: 'Jednostki Imperialne',
			pt_BR: 'Unidades imperiais',
			ru: 'Использовать Фаренгейты',
			zh_CN: '英制单位',
			sk: 'Imperiálne jednotky',
			de: 'Imperiale Maßeinheiten',
			it: 'Sistema imperiale',
			es: 'Sistema imperial',
			no: 'Imperial units',
		},
		'SEARCH BAR': {
			fr: 'Barre de recherche',
			sv: 'Sökruta',
			nl: 'Zoek balk',
			pl: 'Pasek wyszukiwania',
			pt_BR: 'Barra de pesquisa',
			ru: 'Строка поиска',
			zh_CN: '搜索框',
			sk: 'VYHĽADÁVACÍ PANEL',
			de: 'Suchleiste',
			it: 'Barra di ricerca',
			es: 'Barra de búsqueda',
			no: 'SEARCH BAR',
		},
		'Search engine': {
			fr: 'Moteur de recherche',
			sv: 'Sökmotor',
			nl: 'Zoek engine',
			pl: 'Wyszukiwarka',
			pt_BR: 'Buscadores',
			ru: 'Поисковая система',
			zh_CN: '搜索引擎',
			sk: 'Vyhľadávač',
			de: 'Suchmaschine',
			it: 'Motore di ricerca',
			es: 'Motor de búsqueda',
			no: 'Search engine',
		},
		Enable: {
			fr: 'Activer',
			sv: 'Aktivera',
			nl: 'Activeren',
			pl: 'Aktywować',
			pt_BR: 'Ativar',
			ru: 'позволять',
			zh_CN: '启用',
			sk: 'Aktivovať',
			de: 'Aktivieren',
			it: 'Abilita',
			es: 'Activar',
			no: 'Enable',
		},
		'Open in new tab': {
			fr: 'Ouvrir dans un nouvel onglet',
			zh_CN: '在新标签页打开链接',
			sv: 'Open in new tab',
			nl: 'Open in new tab',
			pl: 'Otwieraj w nowej karcie',
			pt_BR: 'Abrir em nova aba',
			ru: 'Open in new tab',
			sk: 'Otvoriť v novej karte',
			de: 'In einem neuen Tab öffnen',
			it: 'Apri in una nuova scheda',
			es: 'Abrir en una nueva pestaña',
			no: 'Open in new tab',
		},
		'Search on Startpage': {
			fr: 'Rechercher sur Startpage',
			sv: 'Startpage för sök',
			nl: 'Zoek op Startpage',
			pl: ' Szukaj z Startpage',
			pt_BR: 'Buscar no Startpage',
			ru: 'Поиск в Startpage',
			zh_CN: '搜索 Startpage',
			sk: 'Vyhľadávanie Startpage',
			de: 'Auf der Startseite suchen',
			it: 'Cerca su Startpage',
			es: 'Buscar en la página de inicio',
			no: 'Search on Startpage',
		},
		'Search on Ecosia': {
			fr: 'Rechercher sur Ecosia',
			sv: 'Sök med Ecosia',
			nl: 'Zoek op Ecosia',
			pl: 'Szukaj z Ecosia',
			pt_BR: 'Buscar no Ecosia',
			ru: 'Поиск в Ecosia',
			zh_CN: '搜索 Ecosia',
			sk: 'Vyhľadávanie Ecosia',
			de: 'Mit Ecosia suchen',
			it: 'Cerca su Ecosia',
			es: 'Buscar en Ecosia',
			no: 'Search on Ecosia',
		},
		'Search on DuckDuckGo': {
			fr: 'Rechercher sur DuckDuckGo',
			sv: 'Sök med DuckDuckGo',
			nl: 'Zoek op DuckDuckGo',
			pl: 'Szukaj z DuckDuckGo',
			pt_BR: 'Buscar no DuckDuckGo',
			ru: 'Поиск в DuckDuckGo',
			zh_CN: '搜索 DuckDuckGo',
			sk: 'Vyhľadávanie DuckDuckGo',
			de: 'Mit DuckDuckGo suchen',
			it: 'Cerca su DuckDuckGo',
			es: 'Buscar en DuckDuckGo',
			no: 'Search on DuckDuckGo',
		},
		'Search on Google': {
			fr: 'Rechercher sur Google',
			sv: 'Sök med Google',
			nl: 'Zoek op Google',
			pl: 'Szukaj z Google',
			pt_BR: 'Buscar no Google',
			ru: 'Поиск в Google',
			zh_CN: '搜索 Google',
			sk: 'Vyhľadávanie Google',
			de: 'Mit Google suchen',
			it: 'Cerca su Google',
			es: 'Buscar en Google',
			no: 'Search on Google',
		},
		'Search on Yahoo': {
			fr: 'Rechercher sur Yahoo',
			sv: 'Sök med Yahoo',
			nl: 'Zoek op Yahoo',
			pl: 'Szukaj z Yahoo',
			pt_BR: 'Buscar no Yahoo',
			ru: 'Поиск в Yahoo',
			zh_CN: '搜索 Yahoo',
			sk: 'Vyhľadávanie Yahoo',
			de: 'Mit Yahoo suchen',
			it: 'Cerca su Yahoo',
			es: 'Buscar en Yahoo',
			no: 'Search on Yahoo',
		},
		'Search on Bing': {
			fr: 'Rechercher sur Bing',
			sv: 'Sök med Bing',
			nl: 'Zoek op Bing',
			pl: 'Szukaj z Bing',
			pt_BR: 'Buscar no Bing',
			ru: 'Поиск в Bing',
			zh_CN: '搜索 Bing',
			sk: 'Vyhľadávanie Bing',
			de: 'Mit Bing suchen',
			it: 'Cerca su Bing',
			es: 'Buscar en Bing',
			no: 'Search on Bing',
		},
		'Search on Qwant': {
			fr: 'Rechercher sur Qwant',
			sv: 'Sök med Qwant',
			nl: 'Zoek op Qwant',
			pl: 'Szukaj z Qwant',
			pt_BR: 'Buscar no Qwant',
			ru: 'Поиск в Qwant',
			zh_CN: '搜索 Qwant',
			sk: 'Vyhľadávanie Qwant',
			de: 'Mit Qwant suchen',
			it: 'Cerca su Qwant',
			es: 'Buscar en Qwant',
			no: 'Search on Qwant',
		},
		'Search on Lilo': {
			fr: 'Rechercher sur Lilo',
			sv: 'Sök med Lilo',
			nl: 'Zoek op Lilo',
			pl: 'Szukaj z Lilo',
			pt_BR: 'Buscar no Lilo',
			ru: 'Поиск в Lilo',
			zh_CN: '搜索 Lilo',
			sk: 'Vyhľadávanie Lilo',
			de: 'Mit Lilo suchen',
			it: 'Cerca su Lilo',
			es: 'Buscar en Lilo',
			no: 'Search on Lilo',
		},
		'TIME & DATE': {
			fr: 'Date & heure',
			sv: 'TIME & DATE',
			nl: 'TIME & DATE',
			pl: 'TIME & DATE',
			pt_BR: 'DATA & HORA',
			ru: 'TIME & DATE',
			zh_CN: 'TIME & DATE',
			sk: 'TIME & DATE',
			de: 'TIME & DATE',
			it: 'TIME & DATE',
			es: 'Fecha & hora',
			no: 'TIME & DATE',
		},
		'CUSTOM FONT': {
			fr: 'Police personnalisée',
			sv: 'Custom FONT',
			nl: 'Custom FONT',
			pl: 'Custom FONT',
			pt_BR: 'Fonte personalizada',
			ru: 'Custom FONT',
			zh_CN: 'Custom FONT',
			sk: 'Custom FONT',
			de: 'Custom FONT',
			it: 'Custom FONT',
			es: 'Fuente personalizada',
			no: 'CUSTOM FONT',
		},
		'Any Google fonts': {
			fr: 'Toutes Google fonts',
			sv: 'Any Google fonts',
			nl: 'Any Google fonts',
			pl: 'Any Google fonts',
			pt_BR: 'Qualquer Google Fonts',
			ru: 'Any Google fonts',
			zh_CN: 'Any Google fonts',
			sk: 'Any Google fonts',
			de: 'Any Google fonts',
			it: 'Any Google fonts',
			es: 'Cualquier fuente de Google',
			no: 'Any Google fonts',
		},
		'CUSTOM STYLE': {
			fr: 'Style personnalisé',
			sv: 'Custom Style',
			nl: 'Custom Style',
			pl: 'Custom Style',
			pt_BR: 'Estilo personalizado',
			ru: 'Custom Style',
			zh_CN: 'Custom Style',
			sk: 'Custom Style',
			de: 'Custom Style',
			it: 'Custom Style',
			es: 'Estilo personalizado',
			no: 'CUSTOM STYLE',
		},
		'Type in your custom CSS': {
			fr: 'Entrez votre CSS personnalisé',
			sv: 'Type in your custom CSS',
			nl: 'Type in your custom CSS',
			pl: 'Type in your custom CSS',
			pt_BR: 'Insira seu CSS personalizado',
			ru: 'Type in your custom CSS',
			zh_CN: 'Type in your custom CSS',
			sk: 'Type in your custom CSS',
			de: 'Type in your custom CSS',
			it: 'Type in your custom CSS',
			es: 'Escribe aquí tu CSS personalizado',
			no: 'Type in your custom CSS',
		},
		GENERAL: {
			fr: 'Général',
			sv: 'General',
			nl: 'General',
			pl: 'Ogólne',
			pt_BR: 'Geral',
			ru: 'General',
			zh_CN: '通用',
			sk: 'General',
			de: 'Allgemein',
			it: 'Generale',
			es: 'General',
			no: 'GENERAL',
		},
		'US Date Format': {
			fr: 'Date américaine',
			sv: 'US Date Format',
			nl: 'US Date Format',
			pl: 'US Date Format',
			pt_BR: 'Formato de data dos EUA',
			ru: 'US Date Format',
			zh_CN: 'US Date Format',
			sk: 'US Date Format',
			de: 'US Date Format',
			it: 'US Date Format',
			es: 'Formato de fecha americano',
			no: 'US Date Format',
		},
		'12-Hour Time': {
			fr: 'Affichage 12h',
			sv: '12-timmars klocka',
			nl: '12 uur tijd',
			pl: 'Czas 12-godzinny',
			pt_BR: 'Formato de 12 horas',
			ru: '12-часовой формат времени',
			zh_CN: '12小时制',
			sk: '12-hodinový čas',
			de: '12-Stunden Uhrzeit',
			it: 'Sistema orario a 12 ore',
			es: 'Sistema horario de 12 horas',
			no: '12-Hour Time',
		},
		'Time zone': {
			fr: 'Fuseau horaire',
			sv: 'Time Zone',
			nl: 'Time Zone',
			pl: 'Time Zone',
			pt_BR: 'Fuso Horário',
			ru: 'Time Zone',
			zh_CN: 'Time Zone',
			sk: 'Time Zone',
			de: 'Time Zone',
			it: 'Time Zone',
			es: 'Huso horario',
			no: 'Time zone',
		},
		Language: {
			fr: 'Langue',
			sv: 'Välj språk',
			nl: 'Kies een taal',
			pl: 'Wybierz Język',
			pt_BR: 'Escolha o idioma',
			ru: 'Выберите язык',
			zh_CN: '选择语言',
			sk: 'Vybrať jazyk',
			de: 'Sprache',
			it: 'Lingua',
			es: 'Lenguaje o idioma',
			no: 'Language',
		},
		Greeting: {
			fr: 'Nom',
			sv: 'Greeting',
			nl: 'Greeting',
			pl: 'Greeting',
			pt_BR: 'Cumprimento',
			ru: 'Greeting',
			zh_CN: 'Greeting',
			sk: 'Greeting',
			de: 'Greeting',
			it: 'Greeting',
			es: 'Saludo',
			no: 'Greeting',
		},
		'Custom CSS': {
			fr: 'CSS personnalisé',
			sv: 'Custom CSS',
			nl: 'Custom CSS',
			pl: 'Custom CSS',
			pt_BR: 'CSS Personalizado',
			ru: 'Custom CSS',
			zh_CN: 'Custom CSS',
			sk: 'Custom CSS',
			de: 'Custom CSS',
			it: 'Custom CSS',
			es: 'CSS personalizado',
			no: 'Custom CSS',
		},
		'Custom Font': {
			fr: 'Police personnalisée',
			sv: 'Custom Font',
			nl: 'Custom Font',
			pl: 'Custom Font',
			pt_BR: 'Fonte Personalizada',
			ru: 'Custom Font',
			zh_CN: 'Custom Font',
			sk: 'Custom Font',
			de: 'Custom Font',
			it: 'Custom Font',
			es: 'Fuente personalizada',
			no: 'Custom Font',
		},
		'Font family': {
			fr: 'Police',
			sv: 'Font family',
			nl: 'Font family',
			pl: 'Font family',
			pt_BR: 'Família de fontes',
			ru: 'Font family',
			zh_CN: 'Font family',
			sk: 'Font family',
			de: 'Font family',
			it: 'Font family',
			es: 'Fuente',
			no: 'Font family',
		},
		Weight: {
			fr: 'Épaisseur',
			sv: 'Weight',
			nl: 'Weight',
			pl: 'Weight',
			pt_BR: 'Peso',
			ru: 'Weight',
			zh_CN: 'Weight',
			sk: 'Weight',
			de: 'Weight',
			it: 'Weight',
			es: 'Peso',
			no: 'Weight',
		},
		Size: {
			fr: 'Taille',
			sv: 'Size',
			nl: 'Size',
			pl: 'Size',
			pt_BR: 'Tamanho',
			ru: 'Size',
			zh_CN: 'Size',
			sk: 'Size',
			de: 'Size',
			it: 'Size',
			es: 'Tamaño',
			no: 'Size',
		},
		'SETTINGS MANAGEMENT': {
			fr: 'GESTION DES RÉGLAGES',
			sv: 'SETTINGS MANAGEMENT',
			nl: 'SETTINGS MANAGEMENT',
			pl: 'SETTINGS MANAGEMENT',
			pt_BR: 'GERENCIAMENTO DE CONFIGURAÇÕES',
			ru: 'SETTINGS MANAGEMENT',
			zh_CN: '设置管理',
			sk: 'SETTINGS MANAGEMENT',
			de: 'SETTINGS MANAGEMENT',
			it: 'GESTIONE DELLE IMPOSTAZIONI',
			es: 'GESTIÓN DE AJUSTES',
			no: 'SETTINGS MANAGEMENT',
		},
		Import: {
			fr: 'Importer',
			sv: 'Import',
			nl: 'Import',
			pl: 'Import',
			pt_BR: 'Importar',
			ru: 'Import',
			zh_CN: '导入设置',
			sk: 'Import',
			de: 'Import',
			it: 'Importare',
			es: 'Importar',
			no: 'Import',
		},
		Export: {
			fr: 'Exporter',
			sv: 'Export',
			nl: 'Export',
			pl: 'Eksport',
			pt_BR: 'Exportar',
			ru: 'Export',
			zh_CN: '导出设置',
			sk: 'Export',
			de: 'Export',
			it: 'Esportare',
			es: 'Exportar',
			no: 'Export',
		},
		Copied: {
			fr: 'Copié',
			sv: 'Copied',
			nl: 'Copied',
			pl: 'Skopiowano',
			pt_BR: 'Copiado',
			ru: 'Copied',
			zh_CN: '已复制',
			sk: 'Copied',
			de: 'Copied',
			it: 'Copiato',
			es: 'Copiado',
			no: 'Copied',
		},
		'Import code': {
			fr: 'Importer le code',
			sv: 'Importera kod',
			nl: 'Code importeren',
			pl: 'Kod importu',
			pt_BR: 'Importar código',
			ru: 'Код импорта',
			zh_CN: '导入代码',
			sk: 'Importovať kód',
			de: 'Code importieren',
			it: 'Codice di importazione',
			es: 'Importar código',
			no: 'Import code',
		},
		'Error in import code': {
			fr: "Erreur dans le code d'importation",
			sv: 'IError in import code',
			nl: 'Error in import code',
			pl: 'Error in import code',
			pt_BR: 'Error in import code',
			ru: 'Error in import code',
			zh_CN: 'Error in import code',
			sk: 'Error in import code',
			de: 'Error in import code',
			it: 'Error in import code',
			es: 'Error in import code',
			no: 'Error in import code',
		},
		'Export code': {
			fr: "Code d'exportation",
			sv: 'exportkod',
			nl: 'export code',
			pl: 'kod eksportowy',
			pt_BR: 'Exportar código',
			ru: 'экспортный код',
			zh_CN: '导入代码',
			sk: 'vývozný kód',
			de: 'Exportcode',
			it: 'codice di esportazione',
			es: 'Exportar código',
			no: 'Export code',
		},
		'Reset settings': {
			fr: 'Réinitialiser les réglages',
			sv: 'Återställ inställningar',
			nl: 'Reset instellingen',
			pl: 'Przywróć ustawienia domyślne',
			pt_BR: 'Redefinir as configurações',
			ru: 'Сбросить настройки',
			zh_CN: '重新设置',
			sk: 'Obnoviť nastavenia',
			de: 'Einstellungen zurücksetzen',
			it: 'Impostazioni iniziali',
			es: 'Restablecer configuración',
			no: 'Reset settings',
		},
		'Are you sure ?': {
			fr: 'Etes vous sûr ?',
			sv: 'Are you sure ?',
			nl: 'Are you sure ?',
			pl: 'Czy jesteś pewien ?',
			pt_BR: 'Você tem certeza?',
			ru: 'Are you sure ?',
			zh_CN: '确定还原设置吗?',
			sk: 'Are you sure ?',
			de: 'Are you sure ?',
			it: 'Sei sicuro ?',
			es: '¿Estás seguro?',
			no: 'Are you sure ?',
		},
		'Made in France with ❤️': {
			fr: 'Fabriqué en France avec ❤️',
			sv: 'Tillverkad i frankrike med ❤️',
			nl: 'Gemaakt in Frankrijk ❤️',
			pl: 'Stworzone we Francji z ❤️',
			pt_BR: 'Feito na França com ❤️',
			ru: 'Сделано во франции с ❤️',
			zh_CN: '源自法国 匠❤️打造',
			sk: 'Spravené vo Francúzsku s ❤️',
			de: 'Gemacht in Frankreich mit ❤️',
			it: 'Fatto in Francia con ❤️',
			es: 'Hecho en Francia con ❤️',
			no: 'Made in France with ❤️',
		},
		by: {
			fr: 'par',
			sv: 'av',
			nl: 'Door',
			pl: 'przez',
			pt_BR: 'por',
			ru: 'Разработчики:',
			zh_CN: '由',
			sk: 'od',
			de: 'von',
			it: 'Da',
			es: 'por',
			no: 'by',
		},
		Visit: {
			fr: 'Rendez-vous sur',
			sv: 'Besök',
			nl: 'Bezoek',
			pl: 'Do zobaczenia na',
			pt_BR: 'Veja',
			ru: 'Посетите',
			zh_CN: '访问',
			sk: 'Navštívte',
			de: 'Besuche',
			it: 'Visita',
			es: 'Visitar',
			no: 'Visit',
		},
		'our website': {
			fr: 'notre site Internet',
			sv: 'vår hemsida',
			nl: 'onze website',
			pl: 'nasza strona',
			pt_BR: 'nosso site',
			ru: 'наш сайт',
			zh_CN: '我们的网站',
			sk: 'našu webstránku',
			de: 'unsere Website',
			it: 'il nostro sito internet',
			es: 'nuestra página web',
			no: 'our website',
		},
		'for infos and donations': {
			fr: 'pour en savoir plus ou faire un don',
			sv: 'för mera information och donationer',
			nl: 'Voor informatie en donaties',
			pl: 'aby dowiedzieć się więcej lub przekazać darowiznę',
			pt_BR: 'para mais informações e doações',
			ru: 'чтобы узнать больше или поддержать разработчиков',
			zh_CN: '以获取更多资讯，或向我们捐款',
			sk: 'pre informácie a dary',
			de: 'für Informationen und Spenden',
			it: 'per info e donazioni',
			es: 'para más información y donaciones',
			no: 'for infos and donations',
		},
		Consider: {
			fr: "N'hésitez pas",
			sv: 'Consider',
			nl: 'Consider',
			pl: 'Rozważ',
			pt_BR: 'Considere',
			ru: 'Consider',
			zh_CN: '您可以考虑',
			sk: 'Consider',
			de: 'Consider',
			it: 'Considera di',
			es: 'Considere',
			no: 'Consider',
		},
		donating: {
			fr: 'faire un don',
			sv: 'donating',
			nl: 'donating',
			pl: 'przekazanie darowizny',
			pt_BR: 'doar',
			ru: 'donating',
			zh_CN: '向我们捐款',
			sk: 'donating',
			de: 'donating',
			it: 'fare una donazione',
			es: 'hacer una donación',
			no: 'donating',
		},
		'if you love Bonjourr': {
			fr: 'si vous aimez Bonjourr',
			sv: 'if you love Bonjourr',
			nl: 'if you love Bonjourr',
			pl: 'jeśli kochasz Bonjourr',
			pt_BR: 'se você ama o Bonjourr',
			ru: 'if you love Bonjourr',
			zh_CN: '来支持 Bonjourr',
			sk: 'if you love Bonjourr',
			de: 'if you love Bonjourr',
			it: 'se ami Bonjourr',
			es: 'si amas Bonjourr',
			no: 'if you love Bonjourr',
		},
		'Love using Bonjourr? Consider giving us a review or donating, that would help a lot! 😇': {
			fr: 'Vous adorez utiliser Bonjourr ? Pensez à nous noter ou faire un don, ça serait super! 😇',
			sv: 'You love using Bonjourr? Consider giving us a review, that would help a lot! 😇',
			nl: 'You love using Bonjourr? Consider giving us a review, that would help a lot! 😇',
			pl: 'You love using Bonjourr? Consider giving us a review, that would help a lot! 😇',
			pt_BR: 'Se você gosta de usar o Bonjourr? Considere nos avaliar, isso ajudaria muito! 😇',
			ru: 'You love using Bonjourr? Consider giving us a review, that would help a lot! 😇',
			zh_CN: 'You love using Bonjourr? Consider giving us a review, that would help a lot! 😇',
			sk: 'You love using Bonjourr? Consider giving us a review, that would help a lot! 😇',
			de: 'You love using Bonjourr? Consider giving us a review, that would help a lot! 😇',
			it: 'You love using Bonjourr? Consider giving us a review, that would help a lot! 😇',
			es: '¿Te gusta Bonjourr? ¡Considera escribir una reseña, nos ayudaría mucho! 😇',
			no: 'You love using Bonjourr? Consider giving us a review, that would help a lot! 😇',
		},
		Review: {
			fr: 'Noter',
			sv: 'Review',
			nl: 'Review',
			pl: 'Review',
			pt_BR: 'Review',
			ru: 'Review',
			zh_CN: 'Review',
			sk: 'Review',
			de: 'Review',
			it: 'Review',
			es: 'Review',
			no: 'Review',
		},
		Donate: {
			fr: 'Faire un don',
			sv: 'Donate',
			nl: 'Donate',
			pl: 'Donate',
			pt_BR: 'Donate',
			ru: 'Donate',
			zh_CN: 'Donate',
			sk: 'Donate',
			de: 'Donate',
			it: 'Donate',
			es: 'Donate',
			no: 'Donate',
		},
		Cancel: {
			fr: 'Annuler',
			sv: 'Cancel',
			nl: 'Cancel',
			pl: 'Cancel',
			pt_BR: 'Cancelar',
			ru: 'Cancel',
			zh_CN: '取消',
			sk: 'Cancel',
			de: 'Cancel',
			it: 'Annulla',
			es: 'Cancelar',
			no: 'Cancel',
		},
		'Delete Quick Link': {
			fr: 'Supprimer',
			sv: 'Delete Quick Link',
			nl: 'Delete Quick Link',
			pl: 'Delete Quick Link',
			pt_BR: 'Deletar Links Rápidos',
			ru: 'Delete Quick Link',
			zh_CN: '删除快速链接',
			sk: 'Delete Quick Link',
			de: 'Delete Quick Link',
			it: 'Elimina',
			es: 'Eliminar',
			no: 'Delete Quick Link',
		},
		'Apply changes': {
			fr: 'Appliquer',
			sv: 'Apply changes',
			nl: 'Apply changes',
			pl: 'Apply changes',
			pt_BR: 'Aplicar mudanças',
			ru: 'Apply changes',
			zh_CN: '保存更改',
			sk: 'Apply changes',
			de: 'Apply changes',
			it: 'Applica modifiche',
			es: 'Aplicar cambios',
			no: 'Apply changes',
		},
		Monday: {
			fr: 'Lundi',
			sv: 'Måndag',
			nl: 'Maandag',
			pl: 'Poniedziałek',
			pt_BR: 'Segunda',
			ru: 'Понедельник',
			zh_CN: '星期一',
			sk: 'Pondelok',
			de: 'Montag',
			it: 'Lunedì',
			es: 'Lunes',
			no: 'Monday',
		},
		Tuesday: {
			fr: 'Mardi',
			sv: 'Tisdag',
			nl: 'Dinsdag',
			pl: 'Wtorek',
			pt_BR: 'Terça',
			ru: 'Вторник',
			zh_CN: '星期二',
			sk: 'Utorok',
			de: 'Dienstag',
			it: 'Martedì',
			es: 'Martes',
			no: 'Tuesday',
		},
		Wednesday: {
			fr: 'Mercredi',
			sv: 'Onsdag',
			nl: 'Woensdag',
			pl: 'Środa',
			pt_BR: 'Quarta',
			ru: 'Среда',
			zh_CN: '星期三',
			sk: 'Streda',
			de: 'Mittwoch',
			it: 'Mercoledì',
			es: 'Miércoles',
			no: 'Wednesday',
		},
		Thursday: {
			fr: 'Jeudi',
			sv: 'Torsdag',
			nl: 'Donderdag',
			pl: 'Czwartek',
			pt_BR: 'Quinta',
			ru: 'Четверг',
			zh_CN: '星期四',
			sk: 'Štvrtok',
			de: 'Donnerstag',
			it: 'Giovedì',
			es: 'Jueves',
			no: 'Thursday',
		},
		Friday: {
			fr: 'Vendredi',
			sv: 'Fredag',
			nl: 'Vrijdag',
			pl: 'Piątek',
			pt_BR: 'Sexta',
			ru: 'Пятница',
			zh_CN: '星期五',
			sk: 'Piatok',
			de: 'Freitag',
			it: 'Venerdì',
			es: 'Viernes',
			no: 'Friday',
		},
		Saturday: {
			fr: 'Samedi',
			sv: 'Lördag',
			nl: 'Zaterdag',
			pl: 'Sobota',
			pt_BR: 'Sábado',
			ru: 'Суббота',
			zh_CN: '星期六',
			sk: 'Sobota',
			de: 'Samstag',
			it: 'Sabato',
			es: 'Sábado',
			no: 'Saturday',
		},
		Sunday: {
			fr: 'Dimanche',
			sv: 'Söndag',
			nl: 'Zondag',
			pl: 'Niedziela',
			pt_BR: 'Domingo',
			ru: 'Воскресенье',
			zh_CN: '星期日',
			sk: 'Nedeľa',
			de: 'Sonntag',
			it: 'Domenica',
			es: 'Domingo',
			no: 'Sunday',
		},
		January: {
			fr: 'Janvier',
			sv: 'Januari',
			nl: 'Januari',
			pl: 'Styczeń',
			pt_BR: 'Janeiro',
			ru: 'января',
			zh_CN: '1月',
			sk: 'Január',
			de: 'Januar',
			it: 'Gennaio',
			es: 'Enero',
			no: 'January',
		},
		February: {
			fr: 'Février',
			sv: 'Februari',
			nl: 'Februari',
			pl: 'Luty',
			pt_BR: 'Fevereiro',
			ru: 'февраля',
			zh_CN: '2月',
			sk: 'Február',
			de: 'Februar',
			it: 'Febbraio',
			es: 'Febrero',
			no: 'February',
		},
		March: {
			fr: 'Mars',
			sv: 'Mars',
			nl: 'Maart',
			pl: 'Marzec',
			pt_BR: 'Março',
			ru: 'марта',
			zh_CN: '3月',
			sk: 'Marec',
			de: 'März',
			it: 'Marzo',
			es: 'Marzo',
			no: 'March',
		},
		April: {
			fr: 'Avril',
			sv: 'April',
			nl: 'April',
			pl: 'Kwiecień',
			pt_BR: 'Abril',
			ru: 'апреля',
			zh_CN: '4月',
			sk: 'Apríl',
			de: 'April',
			it: 'Aprile',
			es: 'Abril',
			no: 'April',
		},
		May: {
			fr: 'Mai',
			sv: 'Maj',
			nl: 'Mei',
			pl: 'Maj',
			pt_BR: 'Maio',
			ru: 'мая',
			zh_CN: '5月',
			sk: 'Máj',
			de: 'Mai',
			it: 'Maggio',
			es: 'Mayo',
			no: 'May',
		},
		June: {
			fr: 'Juin',
			sv: 'Juni',
			nl: 'Juni',
			pl: 'Czerwiec',
			pt_BR: 'Junho',
			ru: 'июня',
			zh_CN: '6月',
			sk: 'Jún',
			de: 'Juni',
			it: 'Giugno',
			es: 'Junio',
			no: 'June',
		},
		July: {
			fr: 'Juillet',
			sv: 'Juli',
			nl: 'July',
			pl: 'Lipiec',
			pt_BR: 'Julho',
			ru: 'июля',
			zh_CN: '7月',
			sk: 'Júl',
			de: 'Juli',
			it: 'Luglio',
			es: 'Julio',
			no: 'July',
		},
		August: {
			fr: 'Août',
			sv: 'Augusti',
			nl: 'Augustus',
			pl: 'Sierpień',
			pt_BR: 'Agosto',
			ru: 'августа',
			zh_CN: '8月',
			sk: 'August',
			de: 'August',
			it: 'Agosto',
			es: 'Agosto',
			no: 'August',
		},
		September: {
			fr: 'Septembre',
			sv: 'September',
			nl: 'September',
			pl: 'Wrzesień',
			pt_BR: 'Setembro',
			ru: 'сентября',
			zh_CN: '9月',
			sk: 'Spetember',
			de: 'September',
			it: 'Settembre',
			es: 'Septiembre',
			no: 'September',
		},
		October: {
			fr: 'Octobre',
			sv: 'Oktober',
			nl: 'Oktober',
			pl: 'Październik',
			pt_BR: 'Outubro',
			ru: 'октября',
			zh_CN: '10月',
			sk: 'Október',
			de: 'Oktober',
			it: 'Ottobre',
			es: 'Octubre',
			no: 'October',
		},
		November: {
			fr: 'Novembre',
			sv: 'November',
			nl: 'November',
			pl: 'Listopad',
			pt_BR: 'Novembro',
			ru: 'ноября',
			zh_CN: '11月',
			sk: 'November',
			de: 'November',
			it: 'Novembre',
			es: 'Noviembre',
			no: 'November',
		},
		December: {
			fr: 'Décembre',
			sv: 'December',
			nl: 'December',
			pl: 'Grudzień',
			pt_BR: 'Dezembro',
			ru: 'декабря',
			zh_CN: '12月',
			sk: 'December',
			de: 'Dezember',
			it: 'Dicembre',
			es: 'Diciembre',
			no: 'December',
		},
		'Good Morning': {
			fr: 'Bonjour',
			sv: 'Godmorgon',
			nl: 'Goedemorgen',
			pl: 'Dzień Dobry',
			pt_BR: 'Bom Dia',
			ru: 'Доброе утро!',
			zh_CN: '早上好',
			sk: 'Dobré ráno',
			de: 'Guten Morgen',
			it: 'Buongiorno',
			es: 'Buenos días',
			no: 'Good Morning',
		},
		'Good Afternoon': {
			fr: 'Bon après-midi',
			sv: 'Goddag',
			nl: 'Goedemiddag',
			pl: 'Miłego Popołudia',
			pt_BR: 'Boa Tarde',
			ru: 'Добрый день!',
			zh_CN: '下午好',
			sk: 'Dobrý deň',
			de: 'Guten Nachmittag',
			it: 'Buon pomeriggio',
			es: 'Buenas tardes',
			no: 'Good Afternoon',
		},
		'Good Evening': {
			fr: 'Bonsoir',
			sv: 'God kväll',
			nl: 'Goedenavond',
			pl: 'Dobry wieczór',
			pt_BR: 'Boa noite',
			ru: 'Добрый вечер!',
			zh_CN: '晚上好',
			sk: 'Dobrý večer',
			de: 'Guten Abend',
			it: 'Buonasera',
			es: 'Buenas noches',
			no: 'Good Evening',
		},
		'Good Night': {
			fr: 'Bonne nuit',
			sv: 'God natt',
			nl: 'Goedennacht',
			pl: 'Dobrej Nocy',
			pt_BR: 'Boa noite',
			ru: 'Доброй ночи!',
			zh_CN: '晚安',
			sk: 'Dobrú noc',
			de: 'Gute Nacht',
			it: 'Buonanotte',
			es: 'Buenas noches',
			no: 'Good Night',
		},
		'It is currently': {
			fr: 'Il fait actuellement',
			sv: 'Det är just nu',
			nl: 'Het is nu',
			pl: 'Jest obecnie',
			pt_BR: 'Atualmente faz',
			ru: 'Сейчас',
			zh_CN: '现在气温',
			sk: 'Momentálne je',
			de: 'Es ist derzeit',
			it: 'Ci sono',
			es: 'Actualmente está',
			no: 'It is currently',
		},
		'with a high of': {
			fr: 'avec une maximale de',
			sv: 'med högsta',
			nl: 'Met een grote',
			pl: 'z maksymalnie',
			pt_BR: 'com máxima de',
			ru: 'максимальная температура воздуха сегодня',
			zh_CN: '最高气温',
			sk: 'z maximálnych',
			de: 'mit maximal',
			it: 'con una massima di',
			es: 'con un máximo de',
			no: 'with a high of',
		},
		today: {
			fr: "aujourd'hui",
			sv: 'idag',
			nl: 'vandaag',
			pl: 'dzisiaj',
			pt_BR: 'hoje',
			ru: '',
			zh_CN: ', 以上是今日天气',
			sk: 'dnes',
			de: 'heute',
			it: 'oggi',
			es: 'hoy',
			no: 'today',
		},
		tomorrow: {
			fr: 'demain',
			sv: 'jutri',
			nl: 'morgen',
			pl: 'jutro',
			pt_BR: 'amanhã',
			ru: '',
			zh_CN: ', 以上是明天的天气',
			sk: 'zajtra',
			de: 'morgen',
			it: 'domani',
			es: 'mañana',
			no: 'i morgen',
		},
		Title: {
			fr: 'Titre',
			sv: 'Titel',
			nl: 'Titel',
			pl: 'Tytuł',
			pt_BR: 'Título',
			ru: 'Имя',
			zh_CN: '标题',
			sk: 'Názov',
			de: 'Titel',
			it: 'Titolo',
			es: 'Título',
			no: 'Title',
		},
		LANGUAGE: {
			fr: 'Langue',
			sv: 'Språk',
			nl: 'Taal',
			pl: 'Język',
			pt_BR: 'Idioma',
			ru: 'Язык',
			zh_CN: '语言',
			sk: 'JAZYK',
			de: 'Sprache',
			it: 'Lingua',
			es: 'Idioma',
			no: 'LANGUAGE',
		},
		'on Unsplash': {
			fr: 'sur Unsplash',
			sv: 'on Unsplash',
			nl: 'on Unsplash',
			pl: 'on Unsplash',
			pt_BR: 'on Unsplash',
			ru: 'on Unsplash',
			zh_CN: 'on Unsplash',
			sk: 'on Unsplash',
			de: 'on Unsplash',
			it: 'on Unsplash',
			es: 'on Unsplash',
			no: 'on Unsplash',
		},
	}
}

const engineLocales = {
	google: {
		base: 'https://www.google$locale$/search?q=$query$',
		fr: '.fr',
		en: '.com',
		ru: '.ru',
		pl: '.pl',
		pt_BR: '.com.br',
		sv: '.se',
		sl: '.sl',
		nl: '.nl',
		zh_CN: '.tw',
		sk: '.sk',
		de: '.de',
		it: '.it',
		es: '.es',
		no: '.no',
	},
	ddg: {
		base: 'https://duckduckgo.com/?q=$query$&kl=$locale$',
		fr: 'fr-fr',
		en: 'en-US',
		ru: 'ru-ru',
		pl: 'pl-pl',
		pt_BR: 'br-pt',
		sv: 'se-se',
		sl: 'sl-sl',
		nl: 'nl-nl',
		zh_CN: 'cn-zh',
		sk: 'sk-sk',
		de: 'de-de',
		it: 'it-it',
		es: 'es-es',
		no: 'no-no',
	},
	startpage: {
		base: 'https://www.startpage.com/do/dsearch?query=$query$&language=$locale$',
		fr: 'francais',
		en: 'english',
		ru: 'russian',
		pl: 'polski',
		pt_BR: 'br-pt',
		sv: 'svenska',
		sl: 'sl-sl',
		nl: 'nl-nl',
		zh_CN: 'cn-zh',
		sk: 'sk-sk',
		de: 'de-de',
		it: 'italiano',
		es: 'es-es',
		no: 'norsk',
	},
	qwant: {
		base: 'https://www.qwant.com/?q=$query$&r=$locale$',
		fr: 'FR&sr=fr',
		en: 'US&sr=en',
		ru: 'RU&sr=ru',
		pl: 'PL&sr=pl',
		pt_BR: 'BR&sr=pt',
		sv: 'SE&sr=sv',
		sl: 'SL&sr=sl',
		nl: 'NL&sr=nl',
		zh_CN: 'SG&sr=en',
		sk: 'en&sr=en',
		de: 'DE&sr=de',
		it: 'IT&sr=it',
		es: 'ES&sr=es',
		no: 'NO&sr=nb',
	},
	yahoo: {
		base: 'https://$locale$search.yahoo.com/search?q=$query$',
		fr: 'fr.',
		en: '',
		ru: 'ru.',
		pl: 'pl.',
		pt_BR: 'br.',
		sv: 'se.',
		sl: 'sl.',
		nl: 'nl.',
		zh_CN: '',
		sk: '',
		de: 'de.',
		it: 'it.',
		es: 'es.',
		no: 'no.',
	},
	bing: {
		base: 'https://www.bing.com/search?q=$query$&cc=$locale$',
		fr: 'fr',
		en: '',
		ru: 'ru',
		pl: 'pl',
		pt_BR: 'br',
		sv: 'se',
		sl: 'sl',
		nl: 'nl',
		zh_CN: '',
		sk: 'sk',
		de: 'de',
		it: 'it',
		es: 'es',
		no: 'no',
	},
	ecosia: {
		base: 'https://www.ecosia.org/search?q=$query$',
	},
	lilo: {
		base: 'https://search.lilo.org/?q=$query$',
	},
}
