// Swedish translation by Benjamin Horn · https://benjaminhorn.io/
// Dutch translation by Osman Temiz · u/MANllAC
// Polish translation by Mateusz K · u/DiVine92
// Russian translation by OemDef · u/OemDef
// Simplified chinese translation by Shuhuai Cao · github.com/csh980717
// Brazilian translation by Adilson Santos · github.com/adilsonfsantos
// Slovak translation by Roman Bartík
// German translation by Bernhard Wittmann · https://bernhardwittmann.com
// Italian translation by Trazalca · github.com/Trazalca

// base
// "": {
// fr: "",
// sv: "",
// nl: "",
// pl: "",
// pt_BR: "",
// ru: "",
// zh_CN: "",
// sk: "",
// de: "",
// it: "",
// },

function askfordict() {
	return {
		'New Tab': {
			fr: 'Nouvel onglet',
			sv: 'Ny flik',
			nl: 'Nieuw tabblad',
			pl: 'Nowa Karta',
			pt_BR: 'Nova Aba',
			ru: 'Новая вкладка',
			zh_CN: '新标签页',
			sk: 'Nová karta',
			de: 'Neues Tab',
			it: 'Nuova scheda',
		},

		//settings

		SETTINGS: {
			fr: 'Réglages',
			sv: 'Inställningar',
			nl: 'Instellingen',
			pl: 'Ustawienia',
			pt_BR: 'Configurações',
			ru: 'Настройки',
			zh_CN: '设置',
			sk: 'Nastavenia',
			de: 'Einstellungen',
			it: 'Impostazioni',
		},
		'Show all settings': {
			fr: 'Afficher tous les réglages',
			sv: 'Show all settings',
			nl: 'Show all settings',
			pl: 'Show all settings',
			pt_BR: 'Show all settings',
			ru: 'Show all settings',
			zh_CN: 'Show all settings',
			sk: 'Show all settings',
			de: 'Show all settings',
			it: 'Show all settings',
		},
		'QUICK LINKS': {
			fr: 'Liens favoris',
			sv: 'Snabblänkar',
			nl: 'Snelle links',
			pl: 'Ulubione Witryny',
			pt_BR: 'Links Rápidos',
			ru: 'Закладки',
			zh_CN: '快速链接',
			sk: 'RÝCHLA NAVIGÁCIA',
			de: 'Quick Links',
			it: 'Collegamenti rapidi',
		},
		Name: {
			fr: 'Nom',
			sv: 'Namn',
			nl: 'Naam',
			pl: 'Nazwa',
			pt_BR: 'Nome',
			ru: 'название',
			zh_CN: '名称',
			sk: 'názov',
			de: 'Name',
			it: 'nome',
		},
		Add: {
			fr: 'Ajouter',
			sv: 'Lägg till',
			nl: 'Voeg toe',
			pl: 'Dodaj',
			pt_BR: 'Adicionar',
			ru: 'Добавить',
			zh_CN: '添加',
			sk: 'Pridať',
			de: 'Hinzufügen',
			it: 'Aggiungere',
		},
		'Open in new tab by default': {
			fr: 'Ouvrir dans un nouvel onglet par défaut',
			zh_CN: '默认在新标签页打开链接',
			//The following languages need to be added:
			sv: 'Open in new tab by default',
			nl: 'Open in new tab by default',
			pl: 'Otwieraj domyślnie w nowej karcie',
			pt_BR: 'Abrir em nova aba por padrão',
			ru: 'Open in new tab by default',
			sk: 'Predvolene otvoriť v novej karte',
			de: 'Standardmäßig in einem neuen Tab öffnen',
			it: 'Apri in una nuova scheda come impostazione predefinita',
		},
		'Links per row': {
			fr: 'Liens par ligne',
			sv: 'Links per row',
			nl: 'Links per row',
			pl: 'Links per row',
			pt_BR: 'Links por linha',
			ru: 'Links per row',
			zh_CN: 'Links per row',
			sk: 'Links per row',
			de: 'Links per row',
			it: 'Links per row',
		},
		VISUALS: {
			fr: 'Affichage',
			sv: 'Visuella',
			nl: 'Vormgeving',
			pl: 'Wygląd',
			pt_BR: 'Visuais',
			ru: 'Внешний вид',
			zh_CN: '外观',
			sk: 'VZHĽAD',
			de: 'Bilder',
			it: 'Visualizzazione',
		},
		'Background type': {
			fr: "Type d'arrière-plan",
			sv: 'Background type',
			nl: 'Background type',
			pl: 'Rodzaj tła',
			pt_BR: 'Tipo de background',
			ru: 'Background type',
			zh_CN: '背景类型',
			sk: 'Pozadie',
			de: 'Hintergrund Typ',
			it: 'Tipo di sfondo',
		},
		Default: {
			fr: 'Par défaut',
			sv: 'Default',
			nl: 'Default',
			pl: 'Domyślne',
			pt_BR: 'Padrão',
			ru: 'Default',
			zh_CN: '默认',
			sk: 'Default',
			de: 'Standard',
			it: 'Predefinito',
		},
		Dynamic: {
			fr: 'Dynamique',
			sv: 'Dynamic',
			nl: 'Dynamic',
			pl: 'Dynamiczne',
			pt_BR: 'Dinâmico',
			ru: 'Dynamic',
			zh_CN: '动态',
			sk: 'Dynamic',
			de: 'Dynamisch',
			it: 'Dinamico',
		},
		Custom: {
			fr: 'Personnalisé',
			sv: 'Custom',
			nl: 'Custom',
			pl: 'Użytkownika',
			pt_BR: 'Personalizado',
			ru: 'Custom',
			zh_CN: '自定义',
			sk: 'Custom',
			de: 'Benutzerdefiniert',
			it: 'Personalizzato',
		},
		Frequency: {
			fr: 'Fréquence',
			sv: 'Frequency',
			nl: 'Frequency',
			pl: 'Częstotliwość',
			pt_BR: 'Frequencia',
			ru: 'Frequency',
			zh_CN: '背景切换频率',
			sk: 'Frequency',
			de: 'Häufigkeit',
			it: 'Frequenza',
		},
		'Every tab': {
			fr: 'Chaque onglet',
			sv: 'Every tab',
			nl: 'Every tab',
			pl: 'Co zakładkę',
			pt_BR: 'A cada aba',
			ru: 'Every tab',
			zh_CN: '每次新建标签页',
			sk: 'Every tab',
			de: 'Jedes Tab',
			it: 'Ogni scheda',
		},
		'Every hour': {
			fr: 'Chaque heure',
			sv: 'Every hour',
			nl: 'Every hour',
			pl: 'Co godzinę',
			pt_BR: 'A cada hora',
			ru: 'Every hour',
			zh_CN: '每小时',
			sk: 'Every hour',
			de: 'Jede Stunde',
			it: 'Ogni ora',
		},
		'Every day': {
			fr: 'Chaque jour',
			sv: 'Every day',
			nl: 'Every day',
			pl: 'Codziennie',
			pt_BR: 'Todos os dias',
			ru: 'Every day',
			zh_CN: '每天',
			sk: 'Every day',
			de: 'Jeden Tag',
			it: 'Ogni giorno',
		},
		Pause: {
			fr: 'Pause',
			sv: 'Pause',
			nl: 'Pause',
			pl: 'Pauza',
			pt_BR: 'Parar',
			ru: 'Pause',
			zh_CN: '不切换',
			sk: 'Pause',
			de: 'Pause',
			it: 'Pausa',
		},
		'Blur intensity': {
			fr: 'Intensité du flou',
			sv: 'Oskärpans intensitet',
			nl: 'Intensiviteit van het blur effect',
			pl: 'Intensywnośc rozmycia',
			pt_BR: 'Intensidade do desfoque',
			ru: 'Степень размытия фона',
			zh_CN: '模糊度',
			sk: 'Intenzita rozmazania',
			de: 'Weichzeichner Stärke',
			it: 'Intensità della sfocatura',
		},
		Brightness: {
			fr: 'Luminosité',
			sv: 'Brightness',
			nl: 'Brightness',
			pl: 'Jasność',
			pt_BR: 'Brilho',
			ru: 'Brightness',
			zh_CN: '亮度',
			sk: 'Brightness',
			de: 'Helligkeit',
			it: 'Luminosità',
		},
		'Dark mode': {
			fr: 'Mode sombre',
			sv: 'Mörkt läge',
			nl: 'Nacht modus',
			pl: 'Tryb ciemny',
			pt_BR: 'Modo noturno',
			ru: 'Тёмная тема',
			zh_CN: '深色模式',
			sk: 'Tmavý režim',
			de: 'Dunkelmodus',
			it: 'Modalità notturna',
		},
		'Only at night': {
			fr: 'Seulement la nuit',
			sv: 'Endast på natten',
			nl: 'Alleen ’s nachts',
			pl: 'Tylko w nocy',
			pt_BR: 'Apenas à noite',
			ru: 'Только ночью',
			zh_CN: '只在夜间开启',
			sk: 'Len v noci',
			de: 'Nur Nachts',
			it: 'Solo di notte',
		},
		'With the system': {
			fr: 'Avec le système',
			sv: 'Med systemet',
			nl: 'Met het systeem',
			pl: 'Razem z systemem',
			pt_BR: 'Seguir sistema',
			ru: 'Вместе с системой',
			zh_CN: '跟随系统设置',
			sk: 'Podľa systému',
			de: 'Wie in den Systemeinstellungen',
			it: 'Sistema',
		},
		Enabled: {
			fr: 'Activé',
			sv: 'Aktiverad',
			nl: 'Ingeschakeld',
			pl: 'Włączony',
			pt_BR: 'Ativado',
			ru: 'Включена',
			zh_CN: '开启',
			sk: 'Zapnuté',
			de: 'Aktiviert',
			it: 'Abilitato',
		},
		Disabled: {
			fr: 'Désactivé',
			sv: 'Inaktiverad',
			nl: 'Uitgeschakeld',
			pl: 'Wyłączony',
			pt_BR: 'Desativado',
			ru: 'Выключена',
			zh_CN: '关闭',
			sk: 'Vypnuté',
			de: 'Deaktiviert',
			it: 'Disabilitato',
		},
		'Hide elements': {
			fr: 'Cacher des éléments',
			sv: 'Hide elements',
			nl: 'Hide elements',
			pl: 'Hide elements',
			pt_BR: 'Hide elements',
			ru: 'Hide elements',
			zh_CN: 'Hide elements',
			sk: 'Hide elements',
			de: 'Hide elements',
			it: 'Hide elements',
		},
		Clock: {
			fr: 'Horloge',
			sv: 'Clock',
			nl: 'Clock',
			pl: 'Clock',
			pt_BR: 'Clock',
			ru: 'Clock',
			zh_CN: 'Clock',
			sk: 'Clock',
			de: 'Clock',
			it: 'Clock',
		},
		Date: {
			fr: 'Date',
			sv: 'Date',
			nl: 'Date',
			pl: 'Date',
			pt_BR: 'Date',
			ru: 'Date',
			zh_CN: 'Date',
			sk: 'Date',
			de: 'Date',
			it: 'Date',
		},
		Greetings: {
			fr: 'Horloge',
			sv: 'Greetings',
			nl: 'Greetings',
			pl: 'Greetings',
			pt_BR: 'Greetings',
			ru: 'Greetings',
			zh_CN: 'Greetings',
			sk: 'Greetings',
			de: 'Greetings',
			it: 'Greetings',
		},
		Weather: {
			fr: 'Météo',
			sv: 'Weather',
			nl: 'Weather',
			pl: 'Weather',
			pt_BR: 'Weather',
			ru: 'Weather',
			zh_CN: 'Weather',
			sk: 'Weather',
			de: 'Weather',
			it: 'Weather',
		},
		Icon: {
			fr: 'Icône',
			sv: 'Icon',
			nl: 'Icon',
			pl: 'Icon',
			pt_BR: 'Icon',
			ru: 'Icon',
			zh_CN: 'Icon',
			sk: 'Icon',
			de: 'Icon',
			it: 'Icon',
		},
		'Quick Links': {
			fr: 'Liens favoris',
			sv: 'Quick Links',
			nl: 'Quick Links',
			pl: 'Quick Links',
			pt_BR: 'Quick Links',
			ru: 'Quick Links',
			zh_CN: 'Quick Links',
			sk: 'Quick Links',
			de: 'Quick Links',
			it: 'Quick Links',
		},
		'Settings icon': {
			fr: 'Icône réglages',
			sv: 'Settings icon',
			nl: 'Settings icon',
			pl: 'Settings icon',
			pt_BR: 'Settings icon',
			ru: 'Settings icon',
			zh_CN: 'Settings icon',
			sk: 'Settings icon',
			de: 'Settings icon',
			it: 'Settings icon',
		},
		'Upload background here': {
			fr: 'Insérez votre arrière-plan',
			sv: 'Upload background here',
			nl: 'Upload background here',
			pl: 'Upload background here',
			pt_BR: 'Suba o seu background aqui',
			ru: 'Upload background here',
			zh_CN: '上传背景',
			sk: 'Upload background here',
			de: 'Upload background here',
			it: 'Upload background here',
		},
		'Analog clock': {
			fr: 'Horloge analogue',
			sv: 'Analog clock',
			nl: 'Analog clock',
			pl: 'Analog clock',
			pt_BR: 'Relógio Analógico',
			ru: 'Analog clock',
			zh_CN: 'Analog clock',
			sk: 'Analog clock',
			de: 'Analog clock',
			it: 'Analog clock',
		},
		'Display Seconds': {
			fr: 'Afficher les secondes',
			sv: 'Display seconds',
			nl: 'Display seconds',
			pl: 'Display seconds',
			pt_BR: 'Display seconds',
			ru: 'Display seconds',
			zh_CN: 'Display seconds',
			sk: 'Display seconds',
			de: 'Display seconds',
			it: 'Display seconds',
		},
		Automatic: {
			fr: 'Automatique',
			sv: 'Automatic',
			nl: 'Automatic',
			pl: 'Automatic',
			pt_BR: 'Automatic',
			ru: 'Automatic',
			zh_CN: 'Automatic',
			sk: 'Automatic',
			de: 'Automatic',
			it: 'Automatic',
		},
		WEATHER: {
			fr: 'Météo',
			sv: 'Väder',
			nl: 'Weer',
			pl: 'Pogoda',
			pt_BR: 'Tempo',
			ru: 'Погода',
			zh_CN: '天气',
			sk: 'POČASIE',
			de: 'Wetter',
			it: 'Meteo',
		},
		Geolocation: {
			fr: 'Géolocalisation',
			sv: 'Geolocation',
			nl: 'Locatie',
			pl: 'Geolokalizacja',
			pt_BR: 'Geolocalização',
			ru: 'Геолокация',
			zh_CN: '使用我的位置',
			sk: 'Geolokácia',
			de: 'Geolokalisierung',
			it: 'Geolocalizzazione',
		},
		'City not found': {
			fr: 'Ville non trouvé',
			sv: 'Staden hittades inte',
			nl: 'Stad niet gevonden',
			pl: 'Zmień miasto',
			pt_BR: 'Cidade não encontrada',
			ru: 'Город не найден',
			zh_CN: '找不到城市',
			sk: 'Mesto nenájdené',
			de: 'Stadt nicht gefunden',
			it: 'Città non trovata',
		},
		'Change city': {
			fr: 'Changer la ville',
			sv: 'Byt stad',
			nl: 'Verander locatie',
			pl: 'Zmień miasto',
			pt_BR: 'Mudar cidade',
			ru: 'Сменить город',
			zh_CN: '更改城市',
			sk: 'Zmeniť mesto',
			de: 'Stadt ändern',
			it: 'Cambia città',
		},
		"Use this option if you don't want to enable geolocation.": {
			fr: 'Utilisez cette option si vous ne souhaitez pas activer la géolocalisation.',
			sv: 'Använd detta alternativ om du inte vill aktivera geolocation.',
			nl: 'Gebruik deze optie als u geen locatie wilt gebruiken',
			pl: 'Użyj tej opcji jesli nie chcesz włączyć geolokalizacji.',
			pt_BR: 'Use esta opção se você não quer ativar a geolocalização',
			ru: 'Если вы не хотите включать геолокацию – воспользуйтесь этой опцией.',
			zh_CN: '如果不想根据您的位置自动设置天气，请使用该选项。',
			sk: 'Túto možnosť použite, ak nechcete povoliť geolokáciu.',
			de: 'Diese Option wählen, wenn du die Geolokalisierung nicht aktivieren willst',
			it: 'Usa questa opzione se non vuoi abilitare la geolocalizzazione',
		},
		'There was a problem': {
			fr: 'Il y a eu un problème',
			sv: 'Ett fel uppstod',
			nl: 'Er is een probleem',
			pl: 'Wystąpił problem',
			pt_BR: 'Houve um problema',
			ru: 'Возникла проблема',
			zh_CN: '出现错误',
			sk: 'Nastal problém',
			de: 'Ein Problem ist aufgetreten',
			it: "C'è stato un problema",
		},
		'Imperial units': {
			fr: 'Unités impériales',
			sv: 'Imperial enheter',
			nl: 'Empirische eenheden',
			pl: 'Jednostki Imperialne',
			pt_BR: 'Unidades imperiais',
			ru: 'Использовать Фаренгейты',
			zh_CN: '英制单位',
			sk: 'Imperiálne jednotky',
			de: 'Imperiale Maßeinheiten',
			it: 'Sistema imperiale',
		},
		'SEARCH BAR': {
			fr: 'Barre de recherche',
			sv: 'Sökruta',
			nl: 'Zoek balk',
			pl: 'Pasek wyszukiwania',
			pt_BR: 'Barra de pesquisa',
			ru: 'Строка поиска',
			zh_CN: '搜索框',
			sk: 'VYHĽADÁVACÍ PANEL',
			de: 'Suchleiste',
			it: 'Barra di ricerca',
		},
		'Search engine': {
			fr: 'Moteur de recherche',
			sv: 'Sökmotor',
			nl: 'Zoek engine',
			pl: 'Wyszukiwarka',
			pt_BR: 'Buscadores',
			ru: 'Поисковая система',
			zh_CN: '搜索引擎',
			sk: 'Vyhľadávač',
			de: 'Suchmaschine',
			it: 'Motore di ricerca',
		},
		Enable: {
			fr: 'Activer',
			sv: 'Aktivera',
			nl: 'Activeren', // unsure
			pl: 'Aktywować', // unsure
			pt_BR: 'Ativar',
			ru: 'позволять', // unsure
			zh_CN: '启用',
			sk: 'Aktivovať',
			de: 'Aktivieren',
			it: 'Abilita',
		},
		'Search on Startpage': {
			fr: 'Rechercher sur Startpage',
			sv: 'Startpage för sök',
			nl: 'Zoek op Startpage',
			pl: ' Szukaj z Startpage',
			pt_BR: 'Buscar no Startpage',
			ru: 'Поиск в Startpage',
			zh_CN: '搜索 Startpage',
			sk: 'Vyhľadávanie Startpage',
			de: 'Auf der Startseite suchen',
			it: 'Cerca su Startpage',
		},
		'Search on Ecosia': {
			fr: 'Rechercher sur Ecosia',
			sv: 'Sök med Ecosia',
			nl: 'Zoek op Ecosia',
			pl: 'Szukaj z Ecosia',
			pt_BR: 'Buscar no Ecosia',
			ru: 'Поиск в Ecosia',
			zh_CN: '搜索 Ecosia',
			sk: 'Vyhľadávanie Ecosia',
			de: 'Mit Ecosia suchen',
			it: 'Cerca su Ecosia',
		},
		'Search on DuckDuckGo': {
			fr: 'Rechercher sur DuckDuckGo',
			sv: 'Sök med DuckDuckGo',
			nl: 'Zoek op DuckDuckGo',
			pl: 'Szukaj z DuckDuckGo',
			pt_BR: 'Buscar no DuckDuckGo',
			ru: 'Поиск в DuckDuckGo',
			zh_CN: '搜索 DuckDuckGo',
			sk: 'Vyhľadávanie DuckDuckGo',
			de: 'Mit DuckDuckGo suchen',
			it: 'Cerca su DuckDuckGo',
		},
		'Search on Google': {
			fr: 'Rechercher sur Google',
			sv: 'Sök med Google',
			nl: 'Zoek op Google',
			pl: 'Szukaj z Google',
			pt_BR: 'Buscar no Google',
			ru: 'Поиск в Google',
			zh_CN: '搜索 Google',
			sk: 'Vyhľadávanie Google',
			de: 'Mit Google suchen',
			it: 'Cerca su Google',
		},
		'Search on Yahoo': {
			fr: 'Rechercher sur Yahoo',
			sv: 'Sök med Yahoo',
			nl: 'Zoek op Yahoo',
			pl: 'Szukaj z Yahoo',
			pt_BR: 'Buscar no Yahoo',
			ru: 'Поиск в Yahoo',
			zh_CN: '搜索 Yahoo',
			sk: 'Vyhľadávanie Yahoo',
			de: 'Mit Yahoo suchen',
			it: 'Cerca su Yahoo',
		},
		'Search on Bing': {
			fr: 'Rechercher sur Bing',
			sv: 'Sök med Bing',
			nl: 'Zoek op Bing',
			pl: 'Szukaj z Bing',
			pt_BR: 'Buscar no Bing',
			ru: 'Поиск в Bing',
			zh_CN: '搜索 Bing',
			sk: 'Vyhľadávanie Bing',
			de: 'Mit Bing suchen',
			it: 'Cerca su Bing',
		},
		'Search on Qwant': {
			fr: 'Rechercher sur Qwant',
			sv: 'Sök med Qwant',
			nl: 'Zoek op Qwant',
			pl: 'Szukaj z Qwant',
			pt_BR: 'Buscar no Qwant',
			ru: 'Поиск в Qwant',
			zh_CN: '搜索 Qwant',
			sk: 'Vyhľadávanie Qwant',
			de: 'Mit Qwant suchen',
			it: 'Cerca su Qwant',
		},
		'TIME & DATE': {
			fr: 'Date & heure',
			sv: 'TIME & DATE',
			nl: 'TIME & DATE',
			pl: 'TIME & DATE',
			pt_BR: 'TIME & DATE',
			ru: 'TIME & DATE',
			zh_CN: 'TIME & DATE',
			sk: 'TIME & DATE',
			de: 'TIME & DATE',
			it: 'TIME & DATE',
		},
		'CUSTOM FONT': {
			fr: 'Police personnalisée',
			sv: 'Custom FONT',
			nl: 'Custom FONT',
			pl: 'Custom FONT',
			pt_BR: 'Custom FONT',
			ru: 'Custom FONT',
			zh_CN: 'Custom FONT',
			sk: 'Custom FONT',
			de: 'Custom FONT',
			it: 'Custom FONT',
		},
		'Any Google fonts': {
			fr: 'Toutes Google fonts',
			sv: 'Any Google fonts',
			nl: 'Any Google fonts',
			pl: 'Any Google fonts',
			pt_BR: 'Any Google fonts',
			ru: 'Any Google fonts',
			zh_CN: 'Any Google fonts',
			sk: 'Any Google fonts',
			de: 'Any Google fonts',
			it: 'Any Google fonts',
		},
		'CUSTOM STYLE': {
			fr: 'Style personnalisé',
			sv: 'Custom Style',
			nl: 'Custom Style',
			pl: 'Custom Style',
			pt_BR: 'Custom Style',
			ru: 'Custom Style',
			zh_CN: 'Custom Style',
			sk: 'Custom Style',
			de: 'Custom Style',
			it: 'Custom Style',
		},
		'Type in your custom CSS': {
			fr: 'Entrez vous CSS personnalisé',
			sv: 'Type in your custom CSS',
			nl: 'Type in your custom CSS',
			pl: 'Type in your custom CSS',
			pt_BR: 'Type in your custom CSS',
			ru: 'Type in your custom CSS',
			zh_CN: 'Type in your custom CSS',
			sk: 'Type in your custom CSS',
			de: 'Type in your custom CSS',
			it: 'Type in your custom CSS',
		},
		GENERAL: {
			fr: 'Général',
			sv: 'General',
			nl: 'General',
			pl: 'Ogólne',
			pt_BR: 'Geral',
			ru: 'General',
			zh_CN: '通用',
			sk: 'General',
			de: 'Allgemein',
			it: 'Generale',
		},
		'US Date Format': {
			fr: 'Date américaine',
			sv: 'US Date Format',
			nl: 'US Date Format',
			pl: 'US Date Format',
			pt_BR: 'Formato de data dos EUA',
			ru: 'US Date Format',
			zh_CN: 'US Date Format',
			sk: 'US Date Format',
			de: 'US Date Format',
			it: 'US Date Format',
		},
		'12-Hour Time': {
			fr: 'Affichage 12h',
			sv: '12-timmars klocka',
			nl: '12 uur tijd',
			pl: 'Czas 12-godzinny',
			pt_BR: 'Formato de 12 horas',
			ru: '12-часовой формат времени',
			zh_CN: '12小时制',
			sk: '12-hodinový čas',
			de: '12-Stunden Uhrzeit',
			it: 'Sistema orario a 12 ore',
		},
		'Time zone': {
			fr: 'Fuseau horaire',
			sv: 'Time Zone',
			nl: 'Time Zone',
			pl: 'Time Zone',
			pt_BR: 'Fuso Horário',
			ru: 'Time Zone',
			zh_CN: 'Time Zone',
			sk: 'Time Zone',
			de: 'Time Zone',
			it: 'Time Zone',
		},
		Language: {
			fr: 'Langue',
			sv: 'Välj språk',
			nl: 'Kies een taal',
			pl: 'Wybierz Język',
			pt_BR: 'Escolha o idioma',
			ru: 'Выберите язык',
			zh_CN: '选择语言',
			sk: 'Vybrať jazyk',
			de: 'Sprache',
			it: 'Lingua',
		},
		Greeting: {
			fr: 'Nom',
			sv: 'Greeting',
			nl: 'Greeting',
			pl: 'Greeting',
			pt_BR: 'Greeting',
			ru: 'Greeting',
			zh_CN: 'Greeting',
			sk: 'Greeting',
			de: 'Greeting',
			it: 'Greeting',
		},
		'Custom CSS': {
			fr: 'CSS personnalisé',
			sv: 'Custom CSS',
			nl: 'Custom CSS',
			pl: 'Custom CSS',
			pt_BR: 'CSS Personalizado',
			ru: 'Custom CSS',
			zh_CN: 'Custom CSS',
			sk: 'Custom CSS',
			de: 'Custom CSS',
			it: 'Custom CSS',
		},
		'Custom Font': {
			fr: 'Police personnalisée',
			sv: 'Custom Font',
			nl: 'Custom Font',
			pl: 'Custom Font',
			pt_BR: 'Fonte Personalizada',
			ru: 'Custom Font',
			zh_CN: 'Custom Font',
			sk: 'Custom Font',
			de: 'Custom Font',
			it: 'Custom Font',
		},
		'Font family': {
			fr: 'Police',
			sv: 'Font family',
			nl: 'Font family',
			pl: 'Font family',
			pt_BR: 'Fonte',
			ru: 'Font family',
			zh_CN: 'Font family',
			sk: 'Font family',
			de: 'Font family',
			it: 'Font family',
		},
		Weight: {
			fr: 'Épaisseur',
			sv: 'Weight',
			nl: 'Weight',
			pl: 'Weight',
			pt_BR: 'Peso',
			ru: 'Weight',
			zh_CN: 'Weight',
			sk: 'Weight',
			de: 'Weight',
			it: 'Weight',
		},
		Size: {
			fr: 'Taille',
			sv: 'Size',
			nl: 'Size',
			pl: 'Size',
			pt_BR: 'Tamanho',
			ru: 'Size',
			zh_CN: 'Size',
			sk: 'Size',
			de: 'Size',
			it: 'Size',
		},
		'SETTINGS MANAGEMENT': {
			fr: 'GESTION DES RÉGLAGES',
			sv: 'SETTINGS MANAGEMENT',
			nl: 'SETTINGS MANAGEMENT',
			pl: 'SETTINGS MANAGEMENT',
			pt_BR: 'GERENCIAMENTO DE CONFIGURAÇÕES',
			ru: 'SETTINGS MANAGEMENT',
			zh_CN: '设置管理',
			sk: 'SETTINGS MANAGEMENT',
			de: 'SETTINGS MANAGEMENT',
			it: 'GESTIONE DELLE IMPOSTAZIONI',
		},
		Import: {
			fr: 'Importer',
			sv: 'Import',
			nl: 'Import',
			pl: 'Import',
			pt_BR: 'Importar',
			ru: 'Import',
			zh_CN: '导入设置',
			sk: 'Import',
			de: 'Import',
			it: 'Importare',
		},
		Export: {
			fr: 'Exporter',
			sv: 'Export',
			nl: 'Export',
			pl: 'Eksport',
			pt_BR: 'Exportar',
			ru: 'Export',
			zh_CN: '导出设置',
			sk: 'Export',
			de: 'Export',
			it: 'Esportare',
		},
		Copied: {
			fr: 'Copié',
			sv: 'Copied',
			nl: 'Copied',
			pl: 'Skopiowano',
			pt_BR: 'Copiados',
			ru: 'Copied',
			zh_CN: '已复制',
			sk: 'Copied',
			de: 'Copied',
			it: 'Copiato',
		},
		'Import code': {
			fr: 'Importer le code',
			sv: 'Importera kod',
			nl: 'Code importeren',
			pl: 'Kod importu',
			pt_BR: 'Código de importação',
			ru: 'Код импорта',
			zh_CN: '导入代码',
			sk: 'Importovať kód',
			de: 'Code importieren',
			it: 'Codice di importazione',
		},
		'Export code': {
			fr: "Code d'exportation",
			sv: 'exportkod',
			nl: 'export code',
			pl: 'kod eksportowy',
			pt_BR: 'código de exportação',
			ru: 'экспортный код',
			zh_CN: '导入代码',
			sk: 'vývozný kód',
			de: 'Exportcode',
			it: 'codice di esportazione',
		},
		'Reset settings': {
			fr: 'Réinitialiser les réglages',
			sv: 'Återställ inställningar',
			nl: 'Reset instellingen',
			pl: 'Przywróć ustawienia domyślne',
			pt_BR: 'Redefinir as configurações',
			ru: 'Сбросить настройки',
			zh_CN: '重新设置',
			sk: 'Obnoviť nastavenia',
			de: 'Einstellungen zurücksetzen',
			it: 'Impostazioni iniziali',
		},
		'Are you sure ?': {
			fr: 'Etes vous sûr ?',
			sv: 'Are you sure ?',
			nl: 'Are you sure ?',
			pl: 'Czy jesteś pewien ?',
			pt_BR: 'Você tem certeza?',
			ru: 'Are you sure ?',
			zh_CN: '确定还原设置吗?',
			sk: 'Are you sure ?',
			de: 'Are you sure ?',
			it: 'Sei sicuro ?',
		},
		'Made in France with ❤️': {
			fr: 'Fabriqué en France avec ❤️',
			sv: 'Tillverkad i frankrike med ❤️',
			nl: 'Gemaakt in Frankrijk ❤️',
			pl: 'Stworzone we Francji z ❤️',
			pt_BR: 'Feito na França com ❤️',
			ru: 'Сделано во франции с ❤️',
			zh_CN: '源自法国 匠❤️打造',
			sk: 'Spravené vo Francúzsku s ❤️',
			de: 'Gemacht in Frankreich mit ❤️',
			it: 'Fatto in Francia con ❤️',
		},
		by: {
			fr: 'par',
			sv: 'av',
			nl: 'Door',
			pl: 'przez',
			pt_BR: 'por',
			ru: 'Разработчики:',
			zh_CN: '由',
			sk: 'od',
			de: 'von',
			it: 'Da',
		},
		Visit: {
			fr: 'Rendez-vous sur',
			sv: 'Besök',
			nl: 'Bezoek',
			pl: 'Do zobaczenia na',
			pt_BR: 'Veja',
			ru: 'Посетите',
			zh_CN: '访问',
			sk: 'Navštívte',
			de: 'Besuche',
			it: 'Visita',
		},
		'our website': {
			fr: 'notre site Internet',
			sv: 'vår hemsida',
			nl: 'onze website',
			pl: 'nasza strona',
			pt_BR: 'nosso site',
			ru: 'наш сайт',
			zh_CN: '我们的网站',
			sk: 'našu webstránku',
			de: 'unsere Website',
			it: 'il nostro sito internet',
		},
		'for infos and donations': {
			fr: 'pour en savoir plus ou faire un don',
			sv: 'för mera information och donationer',
			nl: 'Voor informatie en donaties',
			pl: 'aby dowiedzieć się więcej lub przekazać darowiznę',
			pt_BR: 'para mais informações e doações',
			ru: 'чтобы узнать больше или поддержать разработчиков',
			zh_CN: '以获取更多资讯，或向我们捐款',
			sk: 'pre informácie a dary',
			de: 'für Informationen und Spenden',
			it: 'per info e donazioni',
		},
		Consider: {
			fr: "N'hésitez pas",
			sv: 'Consider',
			nl: 'Consider',
			pl: 'Rozważ',
			pt_BR: 'Considere',
			ru: 'Consider',
			zh_CN: '您可以考虑',
			sk: 'Consider',
			de: 'Consider',
			it: 'Considera di',
		},
		donating: {
			fr: 'faire un don',
			sv: 'donating',
			nl: 'donating',
			pl: 'przekazanie darowizny',
			pt_BR: 'doar',
			ru: 'donating',
			zh_CN: '向我们捐款',
			sk: 'donating',
			de: 'donating',
			it: 'fare una donazione',
		},
		'if you love Bonjourr': {
			fr: 'si vous aimez Bonjourr',
			sv: 'if you love Bonjourr',
			nl: 'if you love Bonjourr',
			pl: 'jeśli kochasz Bonjourr',
			pt_BR: 'se você ama o Bonjourr',
			ru: 'if you love Bonjourr',
			zh_CN: '来支持 Bonjourr',
			sk: 'if you love Bonjourr',
			de: 'if you love Bonjourr',
			it: 'se ami Bonjourr',
		},
		'You love using Bonjourr? Consider giving us a review, that would help a lot! 😇': {
			fr: 'Vous adorez utiliser Bonjourr ? Pensez à nous noter, ça serait super! 😇',
			sv: 'You love using Bonjourr? Consider giving us a review, that would help a lot! 😇',
			nl: 'You love using Bonjourr? Consider giving us a review, that would help a lot! 😇',
			pl: 'You love using Bonjourr? Consider giving us a review, that would help a lot! 😇',
			pt_BR: 'You love using Bonjourr? Consider giving us a review, that would help a lot! 😇',
			ru: 'You love using Bonjourr? Consider giving us a review, that would help a lot! 😇',
			zh_CN: 'You love using Bonjourr? Consider giving us a review, that would help a lot! 😇',
			sk: 'You love using Bonjourr? Consider giving us a review, that would help a lot! 😇',
			de: 'You love using Bonjourr? Consider giving us a review, that would help a lot! 😇',
			it: 'You love using Bonjourr? Consider giving us a review, that would help a lot! 😇',
		},

		//settings

		// edit links

		Cancel: {
			fr: 'Annuler',
			sv: 'Cancel',
			nl: 'Cancel',
			pl: 'Cancel',
			pt_BR: 'Cancelar',
			ru: 'Cancel',
			zh_CN: '取消',
			sk: 'Cancel',
			de: 'Cancel',
			it: 'Annulla',
		},
		'Delete Quick Link': {
			fr: 'Supprimer',
			sv: 'Delete Quick Link',
			nl: 'Delete Quick Link',
			pl: 'Delete Quick Link',
			pt_BR: 'Deletar Links Rápidos',
			ru: 'Delete Quick Link',
			zh_CN: '删除快速链接',
			sk: 'Delete Quick Link',
			de: 'Delete Quick Link',
			it: 'Elimina',
		},
		'Apply changes': {
			fr: 'Appliquer',
			sv: 'Apply changes',
			nl: 'Apply changes',
			pl: 'Apply changes',
			pt_BR: 'Aplicar mudanças',
			ru: 'Apply changes',
			zh_CN: '保存更改',
			sk: 'Apply changes',
			de: 'Apply changes',
			it: 'Applica modifiche',
		},

		//interface

		Monday: {
			fr: 'Lundi',
			sv: 'Måndag',
			nl: 'Maandag',
			pl: 'Poniedziałek',
			pt_BR: 'Segunda',
			ru: 'Понедельник,',
			zh_CN: '星期一',
			sk: 'Pondelok',
			de: 'Montag',
			it: 'Lunedì',
		},
		Tuesday: {
			fr: 'Mardi',
			sv: 'Tisdag',
			nl: 'Dinsdag',
			pl: 'Wtorek',
			pt_BR: 'Terça',
			ru: 'Вторник,',
			zh_CN: '星期二',
			sk: 'Utorok',
			de: 'Dienstag',
			it: 'Martedì',
		},
		Wednesday: {
			fr: 'Mercredi',
			sv: 'Onsdag',
			nl: 'Woensdag',
			pl: 'Środa',
			pt_BR: 'Quarta',
			ru: 'Среда,',
			zh_CN: '星期三',
			sk: 'Streda',
			de: 'Mittwoch',
			it: 'Mercoledì',
		},
		Thursday: {
			fr: 'Jeudi',
			sv: 'Torsdag',
			nl: 'Donderdag',
			pl: 'Czwartek',
			pt_BR: 'Quinta',
			ru: 'Четверг,',
			zh_CN: '星期四',
			sk: 'Štvrtok',
			de: 'Donnerstag',
			it: 'Giovedì',
		},
		Friday: {
			fr: 'Vendredi',
			sv: 'Fredag',
			nl: 'Vrijdag',
			pl: 'Piątek',
			pt_BR: 'Sexta',
			ru: 'Пятница,',
			zh_CN: '星期五',
			sk: 'Piatok',
			de: 'Freitag',
			it: 'Venerdì',
		},
		Saturday: {
			fr: 'Samedi',
			sv: 'Lördag',
			nl: 'Zaterdag',
			pl: 'Sobota',
			pt_BR: 'Sábado',
			ru: 'Суббота,',
			zh_CN: '星期六',
			sk: 'Sobota',
			de: 'Samstag',
			it: 'Sabato',
		},
		Sunday: {
			fr: 'Dimanche',
			sv: 'Söndag',
			nl: 'Zondag',
			pl: 'Niedziela',
			pt_BR: 'Domingo',
			ru: 'Воскресенье,',
			zh_CN: '星期日',
			sk: 'Nedeľa',
			de: 'Sonntag',
			it: 'Domenica',
		},
		January: {
			fr: 'Janvier',
			sv: 'Januari',
			nl: 'Januari',
			pl: 'Styczeń',
			pt_BR: 'Janeiro',
			ru: 'января',
			zh_CN: '1月',
			sk: 'Január',
			de: 'Januar',
			it: 'Gennaio',
		},
		February: {
			fr: 'Février',
			sv: 'Februari',
			nl: 'Februari',
			pl: 'Luty',
			pt_BR: 'Fevereiro',
			ru: 'февраля',
			zh_CN: '2月',
			sk: 'Február',
			de: 'Februar',
			it: 'Febbraio',
		},
		March: {
			fr: 'Mars',
			sv: 'Mars',
			nl: 'Maart',
			pl: 'Marzec',
			pt_BR: 'Março',
			ru: 'марта',
			zh_CN: '3月',
			sk: 'Marec',
			de: 'März',
			it: 'Marzo',
		},
		April: {
			fr: 'Avril',
			sv: 'April',
			nl: 'April',
			pl: 'Kwiecień',
			pt_BR: 'Abril',
			ru: 'апреля',
			zh_CN: '4月',
			sk: 'Apríl',
			de: 'April',
			it: 'Aprile',
		},
		May: {
			fr: 'Mai',
			sv: 'Maj',
			nl: 'Mei',
			pl: 'Maj',
			pt_BR: 'Maio',
			ru: 'мая',
			zh_CN: '5月',
			sk: 'Máj',
			de: 'Mai',
			it: 'Maggio',
		},
		June: {
			fr: 'Juin',
			sv: 'Juni',
			nl: 'Juni',
			pl: 'Czerwiec',
			pt_BR: 'Junho',
			ru: 'июня',
			zh_CN: '6月',
			sk: 'Jún',
			de: 'Juni',
			it: 'Giugno',
		},
		July: {
			fr: 'Juillet',
			sv: 'Juli',
			nl: 'July',
			pl: 'Lipiec',
			pt_BR: 'Julho',
			ru: 'июля',
			zh_CN: '7月',
			sk: 'Júl',
			de: 'Juli',
			it: 'Luglio',
		},
		August: {
			fr: 'Août',
			sv: 'Augusti',
			nl: 'Augustus',
			pl: 'Sierpień',
			pt_BR: 'Agosto',
			ru: 'августа',
			zh_CN: '8月',
			sk: 'August',
			de: 'August',
			it: 'Agosto',
		},
		September: {
			fr: 'Septembre',
			sv: 'September',
			nl: 'September',
			pl: 'Wrzesień',
			pt_BR: 'Setembro',
			ru: 'сентября',
			zh_CN: '9月',
			sk: 'Spetember',
			de: 'September',
			it: 'Settembre',
		},
		October: {
			fr: 'Octobre',
			sv: 'Oktober',
			nl: 'Oktober',
			pl: 'Październik',
			pt_BR: 'Outubro',
			ru: 'октября',
			zh_CN: '10月',
			sk: 'Október',
			de: 'Oktober',
			it: 'Ottobre',
		},
		November: {
			fr: 'Novembre',
			sv: 'November',
			nl: 'November',
			pl: 'Listopad',
			pt_BR: 'Novembro',
			ru: 'ноября',
			zh_CN: '11月',
			sk: 'November',
			de: 'November',
			it: 'Novembre',
		},
		December: {
			fr: 'Décembre',
			sv: 'December',
			nl: 'December',
			pl: 'Grudzień',
			pt_BR: 'Dezembro',
			ru: 'декабря',
			zh_CN: '12月',
			sk: 'December',
			de: 'Dezember',
			it: 'Dicembre',
		},
		'Good Morning': {
			fr: 'Bonjour',
			sv: 'Godmorgon',
			nl: 'Goedemorgen',
			pl: 'Dzień Dobry',
			pt_BR: 'Bom Dia',
			ru: 'Доброе утро!',
			zh_CN: '早上好',
			sk: 'Dobré ráno',
			de: 'Guten Morgen',
			it: 'Buongiorno',
		},
		'Good Afternoon': {
			fr: 'Bon après-midi',
			sv: 'Goddag',
			nl: 'Goedemiddag',
			pl: 'Miłego Popołudia',
			pt_BR: 'Boa Tarde',
			ru: 'Добрый день!',
			zh_CN: '下午好',
			sk: 'Dobrý deň',
			de: 'Guten Nachmittag',
			it: 'Buon pomeriggio',
		},
		'Good Evening': {
			fr: 'Bonsoir',
			sv: 'God kväll',
			nl: 'Goedenavond',
			pl: 'Dobry wieczór',
			pt_BR: 'Boa noite',
			ru: 'Добрый вечер!',
			zh_CN: '晚上好',
			sk: 'Dobrý večer',
			de: 'Guten Abend',
			it: 'Buonasera',
		},
		'Good Night': {
			fr: 'Bonne nuit',
			sv: 'God natt',
			nl: 'Goedennacht',
			pl: 'Dobrej Nocy',
			pt_BR: 'Boa noite',
			ru: 'Доброй ночи!',
			zh_CN: '晚安',
			sk: 'Dobrú noc',
			de: 'Gute Nacht',
			it: 'Buonanotte',
		},
		'It is currently': {
			fr: 'Il fait actuellement',
			sv: 'Det är just nu',
			nl: 'Het is nu',
			pl: 'Jest obecnie',
			pt_BR: 'Atualmente faz',
			ru: 'Сейчас',
			zh_CN: '现在气温',
			sk: 'Momentálne je',
			de: 'Es ist derzeit',
			it: 'Ci sono',
		},
		'with a high of': {
			fr: 'avec une maximale de',
			sv: 'med högsta',
			nl: 'Met een grote',
			pl: 'z maksymalnie',
			pt_BR: 'com máxima de',
			ru: 'максимальная температура воздуха сегодня',
			zh_CN: '最高气温',
			sk: 'z maximálnych',
			de: 'mit maximal',
			it: 'con una massima di',
		},
		'today.': {
			fr: "aujourd'hui.",
			sv: 'idag.',
			nl: 'vandaag.',
			pl: 'dzisiaj',
			pt_BR: 'hoje.',
			ru: '',
			zh_CN: ', 以上是今日天气.',
			sk: 'dnes.',
			de: 'heute.',
			it: 'oggi',
		},

		//OLD TRADS

		Automatic: {
			fr: 'Automatique',
			sv: 'Automatiskt',
			nl: 'Automatisch ',
			pl: 'Automatycznie',
			pt_BR: 'Automático',
			ru: 'Автоматически',
			zh_CN: '自动设置',
			sk: 'Automatické',
			de: 'Automatisch',
			it: 'Automatico',
		},
		Title: {
			fr: 'Titre',
			sv: 'Titel',
			nl: 'Titel',
			pl: 'Tytuł',
			pt_BR: 'Título',
			ru: 'Имя',
			zh_CN: '标题',
			sk: 'Názov',
			de: 'Titel',
			it: 'Titolo',
		},
		LANGUAGE: {
			fr: 'Langue',
			sv: 'Språk',
			nl: 'Taal',
			pl: 'Język',
			pt_BR: 'Idioma',
			ru: 'Язык',
			zh_CN: '语言',
			sk: 'JAZYK',
			de: 'Sprache',
			it: 'Lingua',
		},
	}
}

const l_google = {
	fr: '.fr/search?q=',
	en: '.com/search?q=',
	ru: '.ru/search?q=',
	pl: '.pl/search?q=',
	pt_BR: '.com.br/search?q=',
	sv: '.se/search?q=',
	sl: '.sl/search?q=',
	nl: '.nl/search?q=',
	zh_CN: '.tw/search?q=',
	sk: '.sk/search?q=',
	de: '.de/search?q=',
	it: '.it/search?q=',
}

const l_ddg = {
	fr: '&kl=fr-fr',
	en: '&kl=en-US',
	ru: '&kl=ru-ru',
	pl: '&kl=pl-pl',
	pt_BR: '&kl=br-pt',
	sv: '&kl=se-se',
	sl: '&kl=sl-sl',
	nl: '&kl=nl-nl',
	zh_CN: '&kl=cn-zh',
	sk: '&kl=sk-sk',
	de: '&kl=de-de',
	it: '&kl=it-it',
}

const l_startpage = {
	fr: '&language=francais',
	en: '&language=engish',
	ru: '&language=russian',
	pl: '&language=polski',
	pt_BR: '&language=br-pt',
	sv: '&language=svenska',
	sl: '&language=sl-sl',
	nl: '&language=nl-nl',
	zh_CN: '&language=cn-zh',
	sk: '&language=sk-sk',
	de: '&language=de-de',
	it: '&language=italiano',
}

const l_qwant = {
	fr: '&r=FR&sr=fr',
	en: '&r=US&sr=en',
	ru: '&r=RU&sr=ru',
	pl: '&r=PL&sr=pl',
	pt_BR: '&r=BR&sr=pt',
	sv: '&r=SE&sr=sv',
	sl: '&r=SL&sr=sl',
	nl: '&r=NL&sr=nl',
	zh_CN: '&r=SG&sr=en',
	sk: '&r=en&sr=en',
	de: '&r=DE&sr=de',
	it: '&r=IT&sr=it',
}

const l_yahoo = {
	fr: 'fr.search.yahoo.com/search?q=',
	en: 'search.yahoo.com/search?q=',
	ru: 'ru.search.yahoo.com/search?q=',
	pl: 'pl.search.yahoo.com/search?q=',
	pt_BR: 'br.search.yahoo.com/search?q=',
	sv: 'se.search.yahoo.com/search?q=',
	sl: 'sl.search.yahoo.com/search?q=',
	nl: 'nl.search.yahoo.com/search?q=',
	zh_CN: 'search.yahoo.com/search?q=',
	sk: 'search.yahoo.com/search?q=',
	de: 'de.search.yahoo.com/search?q=',
	it: 'it.search.yahoo.com/search?q=',
}
