import storage from '../storage'

interface SyncUpdate {
	type: string
}

type SyncType = 'auto' | 'gist' | 'url' | 'none'

export async function githubGistSync(token: string) {
	const data = await storage.sync.get()

	fetch('https://api.github.com/gists', {
		method: 'POST',
		body: JSON.stringify({
			files: {
				'bonjourr-export.json': {
					content: JSON.stringify(data),
				},
			},
			description:
				'File automatically generated by Bonjourr when using the option "Settings Synchronization > Github Gist"',
			public: false,
		}),
		headers: {
			Authorization: `Bearer ${token}`,
			Accept: 'application/vnd.github+json',
			'X-GitHub-Api-Version': '2022-11-28',
		},
	})
}

export default function synchronization(init: undefined, update: SyncUpdate) {
	updateSyncOption(update)
}

function updateSyncOption(update: SyncUpdate) {}
