// Full:
//   Brazilian translation by Adilson Santos · @adilsonfsantos
//   Turkish translation by Müslüm Barış Korkmazer · @babico
//   Ukrainian translation by Anton Boksha · @4doge
//   Indonesian translation by Imam Ali Mustofa · @darkterminal · https://read.cv/darkterminal
//   Danish translation by kar1 · @kar1

// Partial:
//   Swedish translation by Benjamin Horn · https://benjaminhorn.io/
//   Dutch translation by Osman Temiz · u/MANllAC, Erik Steinmann · @esteinmann
//   Polish translation by Mateusz K · u/DiVine92
//   Russian translation by OemDef · u/OemDef
//   Simplified chinese translation by Shuhuai Cao · @csh980717
//   Slovak translation by Roman Bartík
//   German translation by Bernhard Wittmann · https://bernhardwittmann.com
//   Italian translation by Trazalca · @Trazalca
//   Spanish translation by José Alberto · @joatb, and Alí Sinisterra · @alisinisterra

export const dict = {
	'New tab': {
		fr: 'Nouvel onglet',
		sv: 'Ny flik',
		nl: 'Nieuw tabblad',
		pl: 'Nowa Karta',
		pt_BR: 'Nova Aba',
		ru: 'Новая вкладка',
		zh_CN: '新标签页',
		sk: 'Nová karta',
		de: 'Neuer Tab',
		it: 'Nuova scheda',
		es: 'Nueva Pestaña',
		tr: 'Yeni Sekme',
		uk: 'Нова вкладка',
		id: 'Tab Baru',
		da: 'Nyt faneblad',
	},
	Consider: {
		fr: "N'hésitez pas",
		sv: 'Överväga',
		nl: 'Overweeg te',
		pl: 'Rozważ',
		pt_BR: 'Considere',
		ru: 'Рассмотрите возможность',
		zh_CN: '您可以考虑',
		sk: 'Zvážte',
		de: 'Erwägen Sie eine',
		it: 'Considera di',
		es: 'Considera',
		tr: 'İstersen',
		uk: 'Подумайте про те,',
		id: 'Mempertimbangkan',
		da: 'Overvej',
	},
	donating: {
		fr: 'faire un don',
		sv: 'donera',
		nl: 'doneren',
		pl: 'przekazanie darowizny',
		pt_BR: 'fazer uma doação',
		ru: 'пожертвования',
		zh_CN: '向我们捐款',
		sk: 'darovanie',
		de: 'Spende',
		it: 'fare una donazione',
		es: 'hacer una donación',
		tr: 'bağış yap',
		uk: 'щоб зробити пожертвування,',
		id: 'menyumbang',
		da: 'at donere',
	},
	'if you love Bonjourr': {
		fr: 'si vous aimez Bonjourr',
		sv: 'om du älskar Bonjourr',
		nl: 'als je van Bonjourr houdt',
		pl: 'jeśli kochasz Bonjourr',
		pt_BR: 'se você ama o Bonjourr',
		ru: 'если вам нравится Bonjourr',
		zh_CN: '来支持 Bonjourr',
		sk: 'Ak miluješ Bonjourra',
		de: 'wenn Sie Bonjourr lieben',
		it: 'se ami Bonjourr',
		es: 'si amas Bonjourr',
		tr: "tabi Bonjourr'u seviyorsan",
		uk: 'якщо Вам подобається Bonjourr',
		id: 'jika Anda menyukai Bonjourr',
		da: 'hvis du elsker Bonjourr',
	},
	'Love using Bonjourr? Consider giving us a review or donating, that would help a lot! 😇': {
		fr: 'Vous aimez utiliser Bonjourr ? Pensez à nous noter ou faire un don, ça serait super ! 😇',
		sv: 'Älskar du att använda Bonjourr? Överväg att ge oss en recension eller donera, det skulle hjälpa mycket! 😇',
		nl: 'Ben je dol op het gebruik van Bonjourr? Overweeg om ons een recensie te geven of te doneren, dat zou veel helpen! 😇',
		pl: 'Uwielbiasz korzystać z Bonjourr? Zastanów się nad wystawieniem nam recenzji lub darowizny, co bardzo by pomogło! 😇',
		pt_BR: 'Gosta de usar o Bonjourr? Considere nos avaliar ou faça uma doação, isso ajudaria muito! 😇',
		ru: 'Нравится Bonjourr? Подумайте о том, чтобы оставить отзыв или сделать нам пожертвование, это очень поможет! 😇',
		zh_CN: '喜欢使用 Bonjourr？ 考虑给我们一个评论或捐赠，这会很有帮助！ 😇',
		sk: 'Máte radi používanie Bonjourru? Skúste nám dať recenziu alebo darovať, to by veľmi pomohlo! 😇',
		de: 'Lieben Sie es, Bonjourr zu nutzen? Erwägen Sie, uns eine Bewertung zu geben oder zu spenden, das würde viel helfen! 😇',
		it: 'Ti piace usare Bonjourr? Considera di darci una recensione o di fare una donazione, sarebbe di grande aiuto! ?',
		es: '¿Te encanta usar Bonjourr? Considera darnos una reseña o hacer una donación, ¡eso nos ayudaría mucho! 😇',
		tr: "Bonjourr'u kullanmayı seviyor musunuz? Bize bir inceleme yapmayı veya bağış yapmayı düşünün, bu çok yardımcı olacaktır! 😇",
		uk: 'Подобається Bonjourr? Залиште відгук або пожертвуйте, це дуже нам допоможе! 😇',
		id: 'Suka menggunakan Bonjourr? Pertimbangkan untuk memberi kami ulasan atau donasi, itu akan sangat membantu! ',
		da: 'Elsker du at bruge Bonjourr? Overvej at give os en anmeldelse eller en donation, det vil hjælpe meget 😇',
	},
	Review: {
		fr: 'Noter',
		sv: 'Recension',
		nl: 'Beoordeling',
		pl: 'Przejrzeć',
		pt_BR: 'Avalie',
		ru: 'Оставить отзыв',
		zh_CN: '审查',
		sk: 'Preskúmanie',
		de: 'Rezension',
		it: 'Recensione',
		es: 'Revisar',
		tr: 'İnceleme',
		uk: 'Залишити відгук',
		id: 'Ulasan',
		da: 'Anmeldelse',
	},
	Donate: {
		fr: 'Faire un don',
		sv: 'Donera',
		nl: 'Doneer',
		pl: 'Podarować',
		pt_BR: 'Doe',
		ru: 'Пожертвовать',
		zh_CN: '捐',
		sk: 'Darovať',
		de: 'Spenden',
		it: 'Donare',
		es: 'Donar',
		tr: 'Bağış',
		uk: 'Пожертвувати',
		id: 'Donasi',
		da: 'Donere',
	},
	Cancel: {
		fr: 'Annuler',
		sv: 'Avbryt',
		nl: 'Annuleren',
		pl: 'Anulować',
		pt_BR: 'Cancelar',
		ru: 'Отмена',
		zh_CN: '取消',
		sk: 'Zrušiť',
		de: 'Abbrechen',
		it: 'Annulla',
		es: 'Cancelar',
		tr: 'İptal',
		uk: 'Скасувати',
		id: 'Batal',
		da: 'Afbryd',
	},
	Delete: {
		fr: 'Supprimer',
		sv: 'Radera',
		nl: 'Verwijderen',
		pl: 'Kasować',
		pt_BR: 'Deletar',
		ru: 'Удалить',
		zh_CN: '删除快速链接',
		sk: 'Odstrániť',
		de: 'Löschen',
		it: 'Elimina',
		es: 'Eliminar',
		tr: 'Sil',
		uk: 'Видалити',
		id: 'Hapus',
		da: 'Slet',
	},
	'Apply changes': {
		fr: 'Enregistrer',
		sv: 'Applicera förändringar',
		nl: 'Wijzigingen toepassen',
		pl: 'Zatwierdź zmiany',
		pt_BR: 'Aplicar mudanças',
		ru: 'Применить изменения',
		zh_CN: '保存更改',
		sk: 'Aplikovať zmeny',
		de: 'Änderungen übernehmen',
		it: 'Applica modifiche',
		es: 'Aplicar cambios',
		tr: 'Değişiklikleri uygula',
		uk: 'Зберегти зміни',
		id: 'Terapkan Perubahan',
		da: 'Anvend ændringer',
	},
	Monday: {
		fr: 'Lundi',
		sv: 'Måndag',
		nl: 'Maandag',
		pl: 'Poniedziałek',
		pt_BR: 'Segunda',
		ru: 'Понедельник',
		zh_CN: '星期一',
		sk: 'Pondelok',
		de: 'Montag',
		it: 'Lunedì',
		es: 'Lunes',
		tr: 'Pazartesi',
		uk: 'Понеділок',
		id: 'Senin',
		da: 'Mandag',
	},
	Tuesday: {
		fr: 'Mardi',
		sv: 'Tisdag',
		nl: 'Dinsdag',
		pl: 'Wtorek',
		pt_BR: 'Terça',
		ru: 'Вторник',
		zh_CN: '星期二',
		sk: 'Utorok',
		de: 'Dienstag',
		it: 'Martedì',
		es: 'Martes',
		tr: 'Salı',
		uk: 'Вівторок',
		id: 'Selasa',
		da: 'Tirsdag',
	},
	Wednesday: {
		fr: 'Mercredi',
		sv: 'Onsdag',
		nl: 'Woensdag',
		pl: 'Środa',
		pt_BR: 'Quarta',
		ru: 'Среда',
		zh_CN: '星期三',
		sk: 'Streda',
		de: 'Mittwoch',
		it: 'Mercoledì',
		es: 'Miércoles',
		tr: 'Çarşamba',
		uk: 'Середа',
		id: 'Rabu',
		da: 'Onsdag',
	},
	Thursday: {
		fr: 'Jeudi',
		sv: 'Torsdag',
		nl: 'Donderdag',
		pl: 'Czwartek',
		pt_BR: 'Quinta',
		ru: 'Четверг',
		zh_CN: '星期四',
		sk: 'Štvrtok',
		de: 'Donnerstag',
		it: 'Giovedì',
		es: 'Jueves',
		tr: 'Perşembe',
		uk: 'Четвер',
		id: 'Kamis',
		da: 'Torsdag',
	},
	Friday: {
		fr: 'Vendredi',
		sv: 'Fredag',
		nl: 'Vrijdag',
		pl: 'Piątek',
		pt_BR: 'Sexta',
		ru: 'Пятница',
		zh_CN: '星期五',
		sk: 'Piatok',
		de: 'Freitag',
		it: 'Venerdì',
		es: 'Viernes',
		tr: 'Cuma',
		uk: "П'ятниця",
		id: 'Jumat',
		da: 'Fredag',
	},
	Saturday: {
		fr: 'Samedi',
		sv: 'Lördag',
		nl: 'Zaterdag',
		pl: 'Sobota',
		pt_BR: 'Sábado',
		ru: 'Суббота',
		zh_CN: '星期六',
		sk: 'Sobota',
		de: 'Samstag',
		it: 'Sabato',
		es: 'Sábado',
		tr: 'Cumartesi',
		uk: 'Суббота',
		id: 'Sabtu',
		da: 'Lørdag',
	},
	Sunday: {
		fr: 'Dimanche',
		sv: 'Söndag',
		nl: 'Zondag',
		pl: 'Niedziela',
		pt_BR: 'Domingo',
		ru: 'Воскресенье',
		zh_CN: '星期日',
		sk: 'Nedeľa',
		de: 'Sonntag',
		it: 'Domenica',
		es: 'Domingo',
		tr: 'Pazar',
		uk: 'Неділя',
		id: 'Minggu',
		da: 'Søndag',
	},
	January: {
		fr: 'Janvier',
		sv: 'Januari',
		nl: 'Januari',
		pl: 'Styczeń',
		pt_BR: 'Janeiro',
		ru: 'января',
		zh_CN: '1月',
		sk: 'Január',
		de: 'Januar',
		it: 'Gennaio',
		es: 'Enero',
		tr: 'Ocak',
		uk: 'січня',
		id: 'Januari',
		da: 'januar',
	},
	February: {
		fr: 'Février',
		sv: 'Februari',
		nl: 'Februari',
		pl: 'Luty',
		pt_BR: 'Fevereiro',
		ru: 'февраля',
		zh_CN: '2月',
		sk: 'Február',
		de: 'Februar',
		it: 'Febbraio',
		es: 'Febrero',
		tr: 'Şubat',
		uk: 'люте',
		id: 'Februari',
		da: 'februar',
	},
	March: {
		fr: 'Mars',
		sv: 'Mars',
		nl: 'Maart',
		pl: 'Marzec',
		pt_BR: 'Março',
		ru: 'марта',
		zh_CN: '3月',
		sk: 'Marec',
		de: 'März',
		it: 'Marzo',
		es: 'Marzo',
		tr: 'Mart',
		uk: 'березня',
		id: 'Maret',
		da: 'marts',
	},
	April: {
		fr: 'Avril',
		sv: 'April',
		nl: 'April',
		pl: 'Kwiecień',
		pt_BR: 'Abril',
		ru: 'апреля',
		zh_CN: '4月',
		sk: 'Apríl',
		de: 'April',
		it: 'Aprile',
		es: 'Abril',
		tr: 'Nisan',
		uk: 'квітня',
		id: 'April',
		da: 'april',
	},
	May: {
		fr: 'Mai',
		sv: 'Maj',
		nl: 'Mei',
		pl: 'Maj',
		pt_BR: 'Maio',
		ru: 'мая',
		zh_CN: '5月',
		sk: 'Máj',
		de: 'Mai',
		it: 'Maggio',
		es: 'Mayo',
		tr: 'Mayıs',
		uk: 'травня',
		id: 'Mei',
		da: 'maj',
	},
	June: {
		fr: 'Juin',
		sv: 'Juni',
		nl: 'Juni',
		pl: 'Czerwiec',
		pt_BR: 'Junho',
		ru: 'июня',
		zh_CN: '6月',
		sk: 'Jún',
		de: 'Juni',
		it: 'Giugno',
		es: 'Junio',
		tr: 'Haziran',
		uk: 'червня',
		id: 'Juni',
		da: 'juni',
	},
	July: {
		fr: 'Juillet',
		sv: 'Juli',
		nl: 'Juli',
		pl: 'Lipiec',
		pt_BR: 'Julho',
		ru: 'июля',
		zh_CN: '7月',
		sk: 'Júl',
		de: 'Juli',
		it: 'Luglio',
		es: 'Julio',
		tr: 'Temmuz',
		uk: 'липня',
		id: 'Juli',
		da: 'juli',
	},
	August: {
		fr: 'Août',
		sv: 'Augusti',
		nl: 'Augustus',
		pl: 'Sierpień',
		pt_BR: 'Agosto',
		ru: 'августа',
		zh_CN: '8月',
		sk: 'August',
		de: 'August',
		it: 'Agosto',
		es: 'Agosto',
		tr: 'Ağustos',
		uk: 'серпня',
		id: 'Agustus',
		da: 'august',
	},
	September: {
		fr: 'Septembre',
		sv: 'September',
		nl: 'September',
		pl: 'Wrzesień',
		pt_BR: 'Setembro',
		ru: 'сентября',
		zh_CN: '9月',
		sk: 'Spetember',
		de: 'September',
		it: 'Settembre',
		es: 'Septiembre',
		tr: 'Eylül',
		uk: 'вересня',
		id: 'September',
		da: 'september',
	},
	October: {
		fr: 'Octobre',
		sv: 'Oktober',
		nl: 'Oktober',
		pl: 'Październik',
		pt_BR: 'Outubro',
		ru: 'октября',
		zh_CN: '10月',
		sk: 'Október',
		de: 'Oktober',
		it: 'Ottobre',
		es: 'Octubre',
		tr: 'Ekim',
		uk: 'жовтня',
		id: 'Oktober',
		da: 'oktober',
	},
	November: {
		fr: 'Novembre',
		sv: 'November',
		nl: 'november',
		pl: 'Listopad',
		pt_BR: 'Novembro',
		ru: 'ноября',
		zh_CN: '11月',
		sk: 'November',
		de: 'November',
		it: 'Novembre',
		es: 'Noviembre',
		tr: 'Kasım',
		uk: 'листопада',
		id: 'November',
		da: 'november',
	},
	December: {
		fr: 'Décembre',
		sv: 'December',
		nl: 'December',
		pl: 'Grudzień',
		pt_BR: 'Dezembro',
		ru: 'декабря',
		zh_CN: '12月',
		sk: 'December',
		de: 'Dezember',
		it: 'Dicembre',
		es: 'Diciembre',
		tr: 'Aralık',
		uk: 'грудня',
		id: 'Desember',
		da: 'december',
	},
	'Good morning': {
		fr: 'Bonjour',
		sv: 'Godmorgon',
		nl: 'Goedemorgen',
		pl: 'Dzień dobry',
		pt_BR: 'Bom dia',
		ru: 'Доброе утро!',
		zh_CN: '早上好',
		sk: 'Dobré ráno',
		de: 'Guten Morgen',
		it: 'Buongiorno',
		es: 'Buenos días',
		tr: 'Günaydın',
		uk: 'Доброго ранку',
		id: 'Selamat pagi',
		da: 'Godmorgen',
	},
	'Good afternoon': {
		fr: 'Bonjour',
		sv: 'Goddag',
		nl: 'Goedemiddag',
		pl: 'Miłego popołudia',
		pt_BR: 'Boa tarde',
		ru: 'Добрый день!',
		zh_CN: '下午好',
		sk: 'Dobrý deň',
		de: 'Guten Tag',
		it: 'Buon pomeriggio',
		es: 'Buenas tardes',
		tr: 'Tünaydın',
		uk: 'Добрий день',
		id: 'Selamat siang',
		da: 'God eftermiddag',
	},
	'Good evening': {
		fr: 'Bonsoir',
		sv: 'God kväll',
		nl: 'Goedenavond',
		pl: 'Dobry wieczór',
		pt_BR: 'Boa noite',
		ru: 'Добрый вечер!',
		zh_CN: '晚上好',
		sk: 'Dobrý večer',
		de: 'Guten Abend',
		it: 'Buonasera',
		es: 'Buenas noches',
		tr: 'İyi akşamlar',
		uk: 'Добрий вечір',
		id: 'Selamat sore',
		da: 'Godaften',
	},
	'Good night': {
		fr: 'Bonne nuit',
		sv: 'God natt',
		nl: 'Goedennacht',
		pl: 'Dobrej nocy',
		pt_BR: 'Boa noite',
		ru: 'Доброй ночи!',
		zh_CN: '晚安',
		sk: 'Dobrú noc',
		de: 'Gute Nacht',
		it: 'Buonanotte',
		es: 'Buenas noches',
		tr: 'İyi geceler',
		uk: 'Доброї ночі',
		id: 'Selamat malam',
		da: 'God nat',
	},
	'It is currently': {
		fr: 'Il fait actuellement',
		sv: 'Det är just nu',
		nl: 'Het is nu',
		pl: 'Jest obecnie',
		pt_BR: 'Atualmente faz',
		ru: 'Сейчас',
		zh_CN: '现在气温',
		sk: 'Momentálne je',
		de: 'Es ist derzeit',
		it: 'Ci sono',
		es: 'Actualmente está',
		tr: 'Şu anda',
		uk: 'Зараз',
		id: 'Saat ini',
		da: 'Det er lige nu',
	},
	'It currently feels like': {
		fr: 'Il y a actuellement un ressenti de',
		sv: 'Just nu känns det som',
		nl: 'Het voelt nu als',
		pl: 'Obecnie czuję się jak',
		pt_BR: 'A Sensação térmica é de',
		ru: 'Сейчас ощущается как',
		zh_CN: '目前感觉像',
		sk: 'Aktuálne je pocitovo',
		de: 'Es fühlt sich aktuell an wie',
		it: 'Attualmente sembra',
		es: 'Actualmente se siente como',
		tr: 'Şu anda gibi hissettiriyor',
		uk: 'Відчувається як',
		id: 'Saat ini terasa seperti',
		da: 'Lige nu føles det som',
	},
	'feels like': {
		fr: 'avec un ressenti de',
		sv: 'Känns som',
		nl: 'voelt als',
		pl: 'Czuje się jak',
		pt_BR: 'com sensação de',
		ru: 'По ощущениям',
		zh_CN: '感觉像',
		sk: 'pocitovo',
		de: 'es fühlt sich an wie',
		it: 'sembrano',
		es: 'se siente como',
		tr: 'gibi hissettiriyor',
		uk: 'відчувається як',
		id: 'terasa seperti',
		da: 'føles som',
	},
	'with a high of': {
		fr: 'avec une maximale de',
		sv: 'med högsta',
		nl: 'Met maximaal',
		pl: 'z maksymalnie',
		pt_BR: 'a máxima é de',
		ru: 'максимальная температура воздуха сегодня',
		zh_CN: '最高气温',
		sk: 'z maximálnych',
		de: 'mit maximal',
		it: 'con una massima di',
		es: 'con un máximo de',
		tr: 'maksimum ile',
		uk: 'з максимальною температурою',
		id: 'dengan tinggi',
		da: 'med op til',
	},
	today: {
		fr: "aujourd'hui",
		sv: 'idag',
		nl: 'vandaag',
		pl: 'dzisiaj',
		pt_BR: 'hoje',
		ru: 'сегодня',
		zh_CN: ', 以上是今日天气',
		sk: 'dnes',
		de: 'heute',
		it: 'oggi',
		es: 'hoy',
		tr: 'bugün',
		uk: 'сьогодні',
		id: 'hari ini',
		da: 'i dag',
	},
	tomorrow: {
		fr: 'demain',
		sv: 'jutri',
		nl: 'morgen',
		pl: 'jutro',
		pt_BR: 'amanhã',
		ru: 'завтра',
		zh_CN: ', 以上是明天的天气',
		sk: 'zajtra',
		de: 'morgen',
		it: 'domani',
		es: 'mañana',
		tr: 'yarın',
		uk: 'завтра',
		id: 'besok',
		da: 'i morgen',
	},
	Title: {
		fr: 'Titre',
		sv: 'Titel',
		nl: 'Titel',
		pl: 'Tytuł',
		pt_BR: 'Título',
		ru: 'Название',
		zh_CN: '标题',
		sk: 'Názov',
		de: 'Titel',
		it: 'Titolo',
		es: 'Título',
		tr: 'Başlık',
		uk: 'Назва',
		id: 'Judul',
		da: 'Titel',
	},
	Link: {
		fr: 'Lien',
		sv: 'Länk',
		nl: 'Koppeling',
		pl: 'Połączyć',
		pt_BR: 'Link',
		ru: 'Ссылка',
		zh_CN: '关联',
		sk: 'Odkaz',
		de: 'Link',
		it: 'Link',
		es: 'Link',
		tr: 'Bağlantı',
		uk: 'Посилання',
		id: 'Tautan',
		da: 'Link',
	},
	'on Unsplash': {
		fr: 'sur Unsplash',
		sv: 'på Unsplash',
		nl: 'op Unsplash',
		pl: 'na Unsplash',
		pt_BR: 'no Unsplash',
		ru: 'на Unsplash',
		zh_CN: '在 Unsplash',
		sk: 'na Unsplash',
		de: 'auf Unsplash',
		it: 'su Unsplash',
		es: 'en Unsplash',
		tr: "Unsplash'ta",
		uk: 'на Unsplash',
		id: 'di Unsplash',
		da: 'på Unsplash',
	},
	'Photo by ': {
		fr: 'Photo par ',
		sv: 'Foto av ',
		nl: 'Foto door ',
		pl: 'Zdjęcie z ',
		pt_BR: 'Foto por ',
		ru: 'Фото ',
		zh_CN: '拍摄者 ',
		sk: 'Fotka od ',
		de: 'Foto von ',
		it: 'Fotografato da ',
		es: 'Foto por ',
		tr: 'Fotoğrafı çeken ',
		uk: 'Фото від ',
		id: 'Foto oleh ',
		da: 'Foto af ',
	},
	'Icon must be < 8kB': {
		fr: "L'icone doit etre < 8kB",
		sv: 'Ikonen måste vara <8kB',
		nl: 'Icoon moet < 8kB zijn',
		pl: 'Ikona musi być < 8kB',
		pt_BR: 'O ícone deve ser < 8kB',
		ru: 'Иконка должна весить < 8 КБ',
		zh_CN: '图标必须< 8kB',
		sk: 'Ikona musí byť <8 kB',
		de: 'Das Symbol muss < 8kB sein',
		it: "L'icona deve essere < 8 kB",
		es: 'El icono debe ser <8 kB',
		tr: 'Simge <8kB olmalı',
		uk: 'Іконка повинна бути менше 8 КБ',
		id: 'Ikon harus <8kB',
		da: 'Ikonet skal være < 8kB',
	},
	// Don't translate these lines
	// 'Bonjourr has been updated to version 1.14 ✨': {
	// 	fr: 'Bonjour vient de passer en version 1.14 ✨',
	// 	sv: 'Bonjourr has been updated to version 1.14 ✨',
	// 	nl: 'Bonjourr has been updated to version 1.14 ✨',
	// 	pl: 'Bonjourr has been updated to version 1.14 ✨',
	// 	pt_BR: 'Bonjourr has been updated to version 1.14 ✨',
	// 	ru: 'Bonjourr обновился до версии 1.14 ✨',
	// 	zh_CN: 'Bonjourr has been updated to version 1.14 ✨',
	// 	sk: 'Bonjourr has been updated to version 1.14 ✨',
	// 	de: 'Bonjourr has been updated to version 1.14 ✨',
	// 	it: 'Bonjourr has been updated to version 1.14 ✨',
	// 	es: 'Bonjourr has been updated to version 1.14 ✨',
	// 	tr: 'Bonjourr has been updated to version 1.14 ✨',
	// 	uk: 'Bonjourr has been updated to version 1.14 ✨',
	// 	id: 'Bonjourr has been updated to version 1.14 ✨',
	// 	da: 'Bonjourr er blevet opdateret til version 1.14 ✨',
	// },
	// 'our full changelog': {
	// 	fr: 'notre changelog complet',
	// 	sv: 'our full changelog',
	// 	nl: 'our full changelog',
	// 	pl: 'our full changelog',
	// 	pt_BR: 'our full changelog',
	// 	ru: 'в нашем полном списке изменений',
	// 	zh_CN: 'our full changelog',
	// 	sk: 'our full changelog',
	// 	de: 'our full changelog',
	// 	it: 'our full changelog',
	// 	es: 'our full changelog',
	// 	tr: 'our full changelog',
	// 	uk: 'our full changelog',
	// 	id: 'our full changelog',
	// 	da: 'vores ændringslog',
	// },
	General: {
		fr: 'Général',
		sv: 'Allmän',
		nl: 'Algemeen',
		pl: 'Ogólne',
		pt_BR: 'Geral',
		ru: 'Основные',
		zh_CN: '通用',
		sk: 'Generál',
		de: 'Allgemein',
		it: 'Generale',
		es: 'General',
		tr: 'Genel',
		uk: 'Загальні',
		id: 'Umum',
		da: 'Generelt',
	},
	'Show all settings': {
		fr: 'Afficher tous les réglages',
		sv: 'Visa alla inställningar',
		nl: 'Toon alle instellingen',
		pl: 'Pokaż wszystkie ustawienia',
		pt_BR: 'Mostrar todas configurações',
		ru: 'Показать все настройки',
		zh_CN: '显示所有设置',
		sk: 'Zobraziť všetky nastavenia',
		de: 'Alle Einstellungen anzeigen',
		it: 'Mostra tutte le impostazioni',
		es: 'Mostrar todos los ajustes',
		tr: 'Tüm ayarları göster',
		uk: 'Показувати всі налаштування',
		id: 'Tampilkan semua pengaturan',
		da: 'Vis alle indstillingerne',
	},
	'Tab appearance': {
		fr: "Apparence de l'onglet",
		sv: 'Flikens utseende',
		nl: 'Tabbladweergave',
		pl: 'Wygląd karty',
		pt_BR: 'Aparência da guia',
		ru: 'Внешний вид вкладки',
		zh_CN: '选项卡外观',
		sk: 'Vzhľad karty',
		de: 'Tab-Erscheinungsbild',
		it: 'Aspetto della scheda',
		es: 'Aspecto de la pestaña',
		tr: 'Sekme görünümü',
		uk: 'Зовнішній вигляд вкладки',
		id: 'Tampilan tab',
		da: 'Faneudseende',
	},
	'The icon and title that appear on your tab. You can put any emoji.': {
		fr: "L'icône et le titre qui apparaissent sur votre onglet. Vous pouvez mettre un emoji de votre choix.",
		sv: 'Ikonen och titeln som visas på din flik. Du kan lägga in vilken emoji som helst.',
		nl: 'Het pictogram en de titel die op uw tabblad verschijnen. Je kunt elke emoji plaatsen.',
		pl: 'Ikona i tytuł, które pojawiają się na Twojej karcie. Możesz umieścić dowolny emotikon.',
		pt_BR: 'O ícone e o título que aparecem na sua guia. Você pode colocar qualquer emoji.',
		ru: 'Значок и заголовок, которые появляются на вашей вкладке. Вы можете поставить любой смайлик.',
		zh_CN: '标签上显示的图标和标题。 你可以放任何表情符号。',
		sk: 'Ikona a názov, ktoré sa zobrazujú na vašej karte. Môžete vložiť akékoľvek emotikony.',
		de: 'Das Symbol und der Titel, die auf Ihrem Tab angezeigt werden. Sie können jedes Emoji einfügen.',
		it: "L'icona e il titolo che appaiono nella tua scheda. Puoi mettere qualsiasi emoji.",
		es: 'El icono y el título que aparecen en tu ficha. Puedes poner cualquier emoji.',
		tr: 'Sekmenizde görünen simge ve başlık. Herhangi bir emoji koyabilirsiniz.',
		uk: 'Значок і назва, які відображаються на вашій вкладці. Ви можете поставити будь-який емодзі.',
		id: 'Ikon dan judul yang muncul di tab Anda. Anda dapat menempatkan emoji apa pun.',
		da: 'Ikonet og titlen, der vises på din fane. Du kan sætte enhver emoji.',
	},
	'More info': {
		fr: 'En savoir plus',
		sv: 'Mer information',
		nl: 'Meer informatie',
		pl: 'Więcej informacji',
		pt_BR: 'Mais informações',
		ru: 'Больше информации',
		zh_CN: '更多信息',
		sk: 'Viac informácií',
		de: 'Weitere Infos',
		it: 'Ulteriori informazioni',
		es: 'Más información',
		tr: 'Daha fazla bilgi',
		uk: 'Більше',
		id: 'Info Selengkapnya',
		da: 'Mere information',
	},
	"These are Bonjourr's bookmarks. ": {
		fr: '',
		sv: 'Det här är Bonjourrs bokmärken. ',
		nl: 'Dit zijn de bladwijzers van Bonjourr. ',
		pl: 'To są zakładki Bonjourr. ',
		pt_BR: 'Esses são os favoritos do Bonjourr. ',
		ru: 'Это закладки Bonjourr. ',
		zh_CN: '这些是 Bonjourr 的书签。',
		sk: 'Toto sú záložky Bonjourru. ',
		de: 'Dies sind Bonjourrs Lesezeichen. ',
		it: 'Questi sono i segnalibri di Bonjourr. ',
		es: 'Estos son los marcadores de Bonjourr. ',
		tr: "Bunlar Bonjourr'un hızlı bağlantıları. ",
		uk: 'Швидкі посилання Bonjourr. ',
		id: 'Ini adalah bookmark Bonjourr. ',
		da: 'De her er Bonjourrs bogmærker. ',
	},
	'Edit your Quick Links by right clicking the icon.': {
		fr: "Éditez un lien favori en faisant un clic droit sur l'icône.",
		sv: 'Redigera dina snabblänkar genom att högerklicka på deras ikon.',
		nl: 'Bewerk uw snelkoppelingen door met de rechtermuisknop op hun pictogram te klikken.',
		pl: 'Edytuj swoje szybkie linki, kliknutie pravým tlačidlom myši na ikonu.',
		pt_BR: 'Altere seus Links Rápidos clicando com o botão direito do mouse em seu ícone.',
		ru: ' Отредактируйте Быстрые ссылки, щелкнув по ним правой кнопкой мыши.',
		zh_CN: '通过右键单击它们的图标来编辑您的快速链接。',
		sk: 'Upravte svoje Quick Links kliknutím pravým tlačidlom na ikone.',
		de: 'Bearbeiten Sie Ihre Schnelllinks, indem Sie mit der rechten Maustaste auf das Symbol klicken.',
		it: "Modifica i tuoi collegamenti Quick Links clic con il pulsante destro del mouse sull'icona.",
		es: 'Edita tus Links Favoritos dándole clic derecho a un ícono.',
		tr: 'Simgeye sağ tıklayarak Hızlı Bağlantılarınızı düzenleyin.',
		uk: 'Редагуйте ваші швидкі посилання натиснувши правою кнопкою миші на піктограмі.',
		id: 'Edit Tautan Cepat Anda dengan mengeklik kanan ikon.',
		da: 'Rediger dine Hurtig Links ved at højreklikke på ikonet.',
	},
	'Edit your Quick Links by long-pressing the icon.': {
		fr: "Éditez un lien favori en appuyant longtemps sur l'icône.",
		sv: 'Redigera dina snabblänkar genom att trycka länge på ikonen i 300 ms.',
		nl: 'Bewerk uw snelkoppelingen door 300 ms lang op het pictogram te drukken.',
		pl: 'Edytuj swoje szybkie łącza, przytrzymując ikonę przez 300 ms.',
		pt_BR: 'Altere seus Links Rápidos pressionando o ícone por 300ms.',
		ru: 'Отредактируйте быстрые ссылки, нажав и удерживая значок в течение 300 мс.',
		zh_CN: '长按图标 300 毫秒来编辑您的快速链接。',
		sk: 'Upravte svoje Quick Links dlhým podržaním ikony po dobu 300 ms.',
		de: 'Bearbeiten Sie Ihre Schnelllinks, indem Sie das Symbol 300 ms lang gedrückt halten.',
		it: "Modifica i tuoi collegamenti rapidi premendo a lungo per 300 ms l'icona.",
		es: 'Edita tus Links Favoritos dejando un ícono presionado por 300 ms.',
		tr: 'Simgeye 300ms uzun süre basarak Hızlı Bağlantılarınızı düzenleyin.',
		uk: 'Редагуйте ваші швидкі посилання утримуючи піктограму протягом 300 мс',
		id: 'Edit Tautan Cepat Anda dengan menekan lama ikon selama 300 md.',
		da: 'Rediger dine Hurtig Links ved at trykke længe på ikonet.',
	},
	'Type the collection ID from its URL, add more by separating them with a comma.': {
		fr: "Entrez l'ID de l'URL de la collection. Ajoutez en plusieurs en les séparant par une virgule.",
		sv: 'Skriv samlings ID från dess URL. Lägg till mer genom att separera dem med ett komma.',
		nl: 'Typ de collectie ID van de URL. Voeg meer toe door ze te scheiden met een komma.',
		pl: 'Wpisz identyfikator kolekcji z adresu URL. Dodaj więcej oddzielając je przecinkiem.',
		pt_BR: 'Digite a identificação da coleção através da URL, adicione mais separando-os com uma vírgula.',
		ru: 'Введите идентификатор коллекции из ее URL-адреса. Добавьте другие, разделив их запятыми.',
		zh_CN: '从其 URL 中输入集合 ID。通过用逗号分隔它们来添加更多。',
		sk: 'Zadajte ID zbierky z jej adresy URL. Pridajte ďalšie ich oddelením čiarkou.',
		de: 'Geben Sie die Sammlungs ID aus ihrer URL ein. Fügen Sie weitere hinzu, indem Sie diese durch ein Komma trennen.',
		it: "Digita l'ID della raccolta dal relativo URL. Aggiungine altri separandoli con una virgola.",
		es: 'Escribe el ID de la colección de tu URL. Agrega más separándolos con una coma.',
		tr: "Koleksiyon kimliğini URL'sinden yazın, virgülle ayırarak daha fazlasını ekleyin.",
		uk: 'Введіть ідентифікатор колекції з URL-адреси або вкажіть декілька через кому',
		id: 'Ketik ID koleksi dari URL-nya, tambahkan lebih banyak dengan memisahkannya dengan koma.',
		da: "Skriv samlingsid'et fra dens URL, tilføj flere ved at adskille dem med komma.",
	},
	Name: {
		fr: 'Nom',
		sv: 'Namn',
		nl: 'Naam',
		pl: 'Nazwa',
		pt_BR: 'Nome',
		ru: 'Название',
		zh_CN: '名称',
		sk: 'názov',
		de: 'Name',
		it: 'nome',
		es: 'Nombre',
		tr: 'İsim',
		uk: 'Назва',
		id: 'Nama',
		da: 'Navn',
	},
	Add: {
		fr: 'Ajouter',
		sv: 'Lägg till',
		nl: 'Voeg toe',
		pl: 'Dodaj',
		pt_BR: 'Adicionar',
		ru: 'Добавить',
		zh_CN: '添加',
		sk: 'Pridať',
		de: 'Hinzufügen',
		it: 'Aggiungere',
		es: 'Añadir',
		tr: 'Ekle',
		uk: 'Додати',
		id: 'Tambah',
		da: 'Tilføj',
	},
	'No bookmarks found': {
		fr: 'Aucun favori trouvé',
		sv: 'Inga bokmärken hittades',
		nl: 'Geen bladwijzers gevonden',
		pl: 'Nie znaleziono zakładek',
		pt_BR: 'Nenhum favorito encontrado',
		ru: 'Закладок не найдено',
		zh_CN: '未找到书签',
		sk: 'Nenašli sa žiadne záložky',
		de: 'Keine Lesezeichen gefunden',
		it: 'Nessun segnalibro trovato',
		es: 'No se encontraron marcadores',
		tr: 'Yer işareti bulunamadı',
		uk: 'Закладок не знайдено',
		id: 'Tidak ada bookmark yang ditemukan',
		da: 'Ingen bogmærker fundet',
	},
	'Select bookmarks to import': {
		fr: 'Sélectionnez les favoris à importer',
		sv: 'Välj de bokmärken som ska importeras',
		nl: 'Selecteer de bladwijzers om te importeren',
		pl: 'Wybierz zakładki do zaimportowania',
		pt_BR: 'Selecione os favoritos para importar',
		ru: 'Выберите закладки для импорта',
		zh_CN: '选择要导入的书签',
		sk: 'Vyberte záložky, ktoré chcete importovať',
		de: 'Wählen Sie die zu importierenden Lesezeichen aus',
		it: 'Seleziona i segnalibri da importare',
		es: 'Selecciona marcadores para importar',
		tr: 'İçe aktarılacak yer imlerini seçin',
		uk: 'Оберіть закладки для імпорту',
		id: 'Pilih bookmark untuk diimpor',
		da: 'Vælg bogmærker som skal importeres',
	},
	'Import this bookmark': {
		fr: 'Importer ce favori',
		sv: 'Importera detta bokmärke',
		nl: 'Deze bladwijzer importeren',
		pl: 'Importuj tę zakładkę',
		pt_BR: 'Importar este favorito',
		ru: 'Импортировать эту закладку',
		zh_CN: '导入此书签',
		sk: 'Importovať túto záložku',
		de: 'Dieses Lesezeichen importieren',
		it: 'Importa questo segnalibro',
		es: 'Importar este marcador',
		tr: 'Bu yer işaretini içe aktar',
		uk: 'Імпортувати цю закладку',
		id: 'Impor bookmark ini',
		da: 'Importer dette bogmærke',
	},
	'Import these bookmarks': {
		fr: 'Importer ces favoris',
		sv: 'Importera dessa bokmärken',
		nl: 'Importeer deze bladwijzers',
		pl: 'Importuj te zakładki',
		pt_BR: 'Importar esses favoritos',
		ru: 'Импортировать эти закладки',
		zh_CN: '导入这些书签',
		sk: 'Importujte tieto záložky',
		de: 'Diese Lesezeichen importieren',
		it: 'Importa questi segnalibri',
		es: 'Importar estos marcadores',
		tr: 'Bu yer işaretlerini içe aktar',
		uk: 'Імпортувати ці закладки',
		id: 'Import these bookmarks',
		da: 'Importer disse bogmærker',
	},
	'Links per row': {
		fr: 'Liens par ligne',
		sv: 'Länkar per rad',
		nl: 'Links per rij',
		pl: 'Linki na wiersz',
		pt_BR: 'Links por linha',
		ru: 'Ссылок в строке',
		zh_CN: '每行链接',
		sk: 'Odkazy na riadok',
		de: 'Links pro Zeile',
		it: 'Link per riga',
		es: 'Links por fila',
		tr: 'Her satır bir bağlantı',
		uk: 'Посилань в рядку',
		id: 'Tautan per baris',
		da: 'Links per række',
	},
	Background: {
		fr: 'Arrière-plan',
		sv: 'Bakgrund',
		nl: 'Achtergrond',
		pl: 'Tło',
		pt_BR: 'Fundo',
		ru: 'Фон',
		zh_CN: '通用',
		sk: 'Pozadie',
		de: 'Hintergrund',
		it: 'Sfondo',
		es: 'Fondo',
		tr: 'Arka plan',
		uk: 'тла',
		id: 'Latar belakang',
		da: 'Baggrund',
	},
	'Background type': {
		fr: "Type d'arrière-plan",
		sv: 'Bakgrundstyp',
		nl: 'Achtergrondtype',
		pl: 'Rodzaj tła',
		pt_BR: 'Tipo de background',
		ru: 'Тип фона',
		zh_CN: '背景类型',
		sk: 'Pozadie',
		de: 'Hintergrund Typ',
		it: 'Tipo di sfondo',
		es: 'Tipo de fondo',
		tr: 'Arka plan türü',
		uk: 'Тип тла',
		id: 'Jenis latar belakang',
		da: 'Baggrundstype',
	},
	Default: {
		fr: 'Par défaut',
		sv: 'Standard',
		nl: 'Standaard',
		pl: 'Domyślne',
		pt_BR: 'Padrão',
		ru: 'По умолчанию',
		zh_CN: '默认',
		sk: 'Predvolené',
		de: 'Standard',
		it: 'Predefinito',
		es: 'Por Defecto',
		tr: 'Varsayılan',
		uk: 'За замовчуванням',
		id: 'Bawaan',
		da: 'Standard',
	},
	Dynamic: {
		fr: 'Dynamique',
		sv: 'Dynamisk',
		nl: 'Dynamisch',
		pl: 'Dynamiczne',
		pt_BR: 'Dinâmico',
		ru: 'Динамический',
		zh_CN: '动态',
		sk: 'Dynamický',
		de: 'Dynamisch',
		it: 'Dinamico',
		es: 'Dinámico',
		tr: 'Dinamik',
		uk: 'Динамічний',
		id: 'Dinamis',
		da: 'Dynamisk',
	},
	Custom: {
		fr: 'Personnalisé',
		sv: 'Beställnings',
		nl: 'Aangepast',
		pl: 'Użytkownika',
		pt_BR: 'Personalizado',
		ru: 'Персонализированный',
		zh_CN: '自定义',
		sk: 'Vlastné',
		de: 'Benutzerdefiniert',
		it: 'Personalizzato',
		es: 'Personalizado',
		tr: 'Özel',
		uk: 'Власний',
		id: 'Personalisasi',
		da: 'Brugerdefineret',
	},
	Frequency: {
		fr: 'Fréquence',
		sv: 'Frekvens',
		nl: 'Frequentie',
		pl: 'Częstotliwość',
		pt_BR: 'Frequência de atualização',
		ru: 'Частота обновления',
		zh_CN: '背景切换频率',
		sk: 'Frekvencia',
		de: 'Häufigkeit',
		it: 'Frequenza',
		es: 'Frecuencia',
		tr: 'Frekans',
		uk: 'Частота',
		id: 'Frekuensi',
		da: 'Hyppighed',
	},
	Daylight: {
		fr: 'Lumière du jour',
		sv: 'Dagsljus',
		nl: 'Daglicht',
		pl: 'Światło dzienne',
		pt_BR: 'Luz do dia',
		ru: 'Дневное время',
		zh_CN: '白天',
		sk: 'Denné svetlo',
		de: 'Tageslicht',
		it: 'Luce del giorno',
		es: 'Luz diario',
		tr: 'Gün ışığı',
		uk: 'денне світло',
		id: 'Siang hari',
		da: 'Dagslys',
	},
	'Every tab': {
		fr: 'Chaque onglet',
		sv: 'Varje flik',
		nl: 'Elk tabblad',
		pl: 'Co zakładkę',
		pt_BR: 'A cada aba',
		ru: 'Каждая вкладка',
		zh_CN: '每次新建标签页',
		sk: 'Každá karta',
		de: 'Jeden Tab',
		it: 'Ogni scheda',
		es: 'Cada Pestaña',
		tr: 'Sekmede bir',
		uk: 'Кожну вкладку',
		id: 'Setiap tab',
		da: 'Hvert faneblad',
	},
	'Every hour': {
		fr: 'Chaque heure',
		sv: 'Varje timme',
		nl: 'Elk uur',
		pl: 'Co godzinę',
		pt_BR: 'A cada hora',
		ru: 'Каждый час',
		zh_CN: '每小时',
		sk: 'Každú hodinu',
		de: 'Jede Stunde',
		it: 'Ogni ora',
		es: 'Cada hora',
		tr: 'Saatte bir',
		uk: 'Кожну годину',
		id: 'Setiap jam',
		da: 'Hver time',
	},
	'Every day': {
		fr: 'Chaque jour',
		sv: 'Varje dag',
		nl: 'Elke dag',
		pl: 'Codziennie',
		pt_BR: 'Diariamente',
		ru: 'Каждый день',
		zh_CN: '每天',
		sk: 'Každý deň',
		de: 'Jeden Tag',
		it: 'Ogni giorno',
		es: 'Cada día',
		tr: 'Günde bir',
		uk: 'Кожного дня',
		id: 'Setiap hari',
		da: 'Hver dag',
	},
	Pause: {
		fr: 'Pause',
		sv: 'Paus',
		nl: 'Pauze',
		pl: 'Pauza',
		pt_BR: 'Pausar',
		ru: 'Пауза',
		zh_CN: '不切换',
		sk: 'Pauza',
		de: 'Pause',
		it: 'Pausa',
		es: 'Pausa',
		tr: 'Durdur',
		uk: 'Пауза',
		id: 'Jeda',
		da: 'Pause',
	},
	'Unsplash collection': {
		fr: 'Collection Unsplash',
		sv: 'Unsplash samling',
		nl: 'Unsplash verzameling',
		pl: 'Kolekcja Unsplash',
		pt_BR: 'Coleção do Unsplash',
		ru: 'Коллекция Unsplash',
		zh_CN: 'Unsplash 收藏',
		sk: 'Unsplash collection',
		de: 'Unsplash Kollektion',
		it: 'Raccolta Unsplash',
		es: 'Colección Unsplash',
		tr: 'Unsplash koleksiyonu',
		uk: 'Колекція Unsplash',
		id: 'Koleksi Unsplash',
		da: 'Unsplash samling',
	},
	'Blur intensity': {
		fr: 'Intensité du flou',
		sv: 'Oskärpans intensitet',
		nl: 'Intensiviteit van het vervagingseffect',
		pl: 'Intensywnośc rozmycia',
		pt_BR: 'Intensidade do desfoque',
		ru: 'Степень размытия фона',
		zh_CN: '模糊度',
		sk: 'Intenzita rozmazania',
		de: 'Weichzeichner Stärke',
		it: 'Intensità della sfocatura',
		es: 'Intensidad de desenfoque',
		tr: 'Bulanıklık yoğunluğu',
		uk: 'Інтенсивність розмиття',
		id: 'Intensitas kabur',
		da: 'Sløringsintensitet',
	},
	Brightness: {
		fr: 'Luminosité',
		sv: 'Ljusstyrka',
		nl: 'Helderheid',
		pl: 'Jasność',
		pt_BR: 'Brilho',
		ru: 'Яркость',
		zh_CN: '亮度',
		sk: 'Jas',
		de: 'Helligkeit',
		it: 'Luminosità',
		es: 'Brillo',
		tr: 'Parlaklık',
		uk: 'Яскравість',
		id: 'Kecerahan',
		da: 'Lysstyrke',
	},
	'Dark mode': {
		fr: 'Mode sombre',
		sv: 'Mörkt läge',
		nl: 'Nacht modus',
		pl: 'Tryb ciemny',
		pt_BR: 'Modo noturno',
		ru: 'Тёмная тема',
		zh_CN: '深色模式',
		sk: 'Tmavý režim',
		de: 'Dunkelmodus',
		it: 'Modalità notturna',
		es: 'Modo Oscuro',
		tr: 'Karanlık mod',
		uk: 'Темний режим',
		id: 'Mode Gelap',
		da: 'Mørk tilstand',
	},
	'At night': {
		fr: 'La nuit',
		sv: 'På natten',
		nl: 'Nachts',
		pl: 'W nocy',
		pt_BR: 'Apenas à noite',
		ru: 'Ночью',
		zh_CN: '只在夜间',
		sk: 'V noci',
		de: 'Nachts',
		it: 'Di notte',
		es: 'De noche',
		tr: 'Geceleyin',
		uk: 'Вночі',
		id: 'Di malam hari',
		da: 'Om natten',
	},
	System: {
		fr: 'Système',
		sv: 'Systemet',
		nl: 'Systeem',
		pl: 'Systemem',
		pt_BR: 'Seguir sistema',
		ru: 'Задаётся системой',
		zh_CN: '系统设置',
		sk: 'Systému',
		de: 'System',
		it: 'Sistema',
		es: 'Sistema',
		tr: 'Sistem',
		uk: 'Система',
		id: 'Sistem',
		da: 'System',
	},
	Enabled: {
		fr: 'Activé',
		sv: 'Aktiverad',
		nl: 'Ingeschakeld',
		pl: 'Włączony',
		pt_BR: 'Ativado',
		ru: 'Включена',
		zh_CN: '开启',
		sk: 'Zapnuté',
		de: 'Aktiviert',
		it: 'Abilitato',
		es: 'Activado',
		tr: 'Etkinleştirildi',
		uk: 'Ввімкнено',
		id: 'Diaktifkan',
		da: 'Aktiveret',
	},
	Disabled: {
		fr: 'Désactivé',
		sv: 'Inaktiverad',
		nl: 'Uitgeschakeld',
		pl: 'Wyłączony',
		pt_BR: 'Desativado',
		ru: 'Выключена',
		zh_CN: '关闭',
		sk: 'Vypnuté',
		de: 'Deaktiviert',
		it: 'Disabilitato',
		es: 'Desactivado',
		tr: 'Devre dışı',
		uk: 'Вимкнено',
		id: 'Dinonaktifkan',
		da: 'Deaktiveret',
	},
	'New tab icon': {
		fr: 'Icône nouvel onglet',
		sv: 'Ikon för ny flik',
		nl: 'Nieuw tabbladpictogram',
		pl: 'Ikona nowej karty',
		pt_BR: 'Ícone de nova aba',
		ru: 'Значок новой вкладки',
		zh_CN: '新标签图标',
		sk: 'Ikona novej karty',
		de: 'Neues Tab-Symbol',
		it: 'Icona Nuova scheda',
		es: 'Icono para la nueva pestaña',
		tr: 'Yeni sekme simgesi',
		uk: 'Піктограма нової вкладки',
		id: 'Ikon tab baru',
		da: 'Fanebladsikon',
	},
	'Any emoji': {
		fr: "N'importe quel emoji",
		sv: 'Vilken emoji som helst',
		nl: 'Elke emoji',
		pl: 'Dowolny emotikon',
		pt_BR: 'Qualquer emoji',
		ru: 'Любые эмодзи',
		zh_CN: '任何表情符号',
		sk: 'Akékoľvek emoji',
		de: 'Beliebiger Emoji',
		it: 'Qualsiasi emoji',
		es: 'Cualquier emoji',
		tr: 'Herhangi bir emoji',
		uk: 'Будь-який емоджі',
		id: 'Apa saja emojo',
		da: 'Hvilken som helst emoji',
	},
	'New tab title': {
		fr: 'Titre du nouvel onglet',
		sv: 'New tab title',
		nl: 'New tab title',
		pl: 'New tab title',
		pt_BR: 'New tab title',
		ru: 'Название новой вкладки',
		zh_CN: 'New tab title',
		sk: 'New tab title',
		de: 'New tab title',
		it: 'New tab title',
		es: 'New tab title',
		tr: 'New tab title',
		uk: 'New tab title',
		id: 'New tab title',
		da: 'Fanebladstitel',
	},

	'Hide elements': {
		fr: 'Cacher des éléments',
		sv: 'Dölj element',
		nl: 'Verberg elementen',
		pl: 'Ukryj elementy',
		pt_BR: 'Esconder elementos',
		ru: 'Скрыть элементы',
		zh_CN: '隐藏元素',
		sk: 'Skryť prvky',
		de: 'Elemente ausblenden',
		it: 'Nascondi elementi',
		es: 'Esconder elementos',
		tr: 'Öğerleri gizle',
		uk: 'Сховати елементи',
		id: 'Sembunyikan elements',
		da: 'Skjul elementer',
	},
	Clock: {
		fr: 'Horloge',
		sv: 'Klocka',
		nl: 'Klok',
		pl: 'Zegar',
		pt_BR: 'Relógio',
		ru: 'Часы',
		zh_CN: '时钟',
		sk: 'Hodiny',
		de: 'Uhr',
		it: 'Orologio',
		es: 'Reloj',
		tr: 'Saat',
		uk: 'Годинник',
		id: 'Jam',
		da: 'Ur',
	},
	'Clock face': {
		fr: "Style d'horloge",
		sv: 'Klockansikte',
		nl: 'Wijzerplaat',
		pl: 'Tarcza zegara',
		pt_BR: 'Estilo do relógio',
		ru: 'Циферблат',
		zh_CN: '钟面',
		sk: 'Ciferník',
		de: 'Ziffernblatt',
		it: 'Quadrante',
		es: 'Estilo del reloj',
		tr: 'Saat stili',
		uk: 'Циферблат',
		id: 'Antarmuka Jam',
		da: 'Urskive',
	},
	None: {
		fr: 'Simple',
		sv: 'Ingen',
		nl: 'Geen',
		pl: 'Nic',
		pt_BR: 'Nenhum',
		ru: 'Пусто',
		zh_CN: '没有任何',
		sk: 'Žiadne',
		de: 'Keiner',
		it: 'Nessuno',
		es: 'Ninguno',
		tr: 'Hiçbiri',
		uk: 'Нічого',
		id: 'Tidak ada',
		da: 'Intet',
	},
	Numbers: {
		fr: 'Chiffres',
		sv: 'Tal',
		nl: 'Nummers',
		pl: 'Liczby',
		pt_BR: 'Números',
		ru: 'Арабские цифры',
		zh_CN: '数字',
		sk: 'Čísla',
		de: 'Zahlen',
		it: 'Numeri',
		es: 'Números',
		tr: 'Sayılar',
		uk: 'Числа',
		id: 'Nomor',
		da: 'Tal',
	},
	Romans: {
		fr: 'Chiffres romains',
		sv: 'Romarna',
		nl: 'Romeinen',
		pl: 'Rzymianie',
		pt_BR: 'Algarismos Romanos',
		ru: 'Римские цифры',
		zh_CN: '罗马书',
		sk: 'Rimania',
		de: 'Römer',
		it: 'Romani',
		es: 'Romanos',
		tr: 'Roma',
		uk: 'Римський',
		id: 'Roman',
		da: 'Romertal',
	},
	Marks: {
		fr: 'Graduations',
		sv: 'Markera',
		nl: 'Markering',
		pl: 'Znakowanie',
		pt_BR: 'Marcações',
		ru: 'Маркировка',
		zh_CN: '打标',
		sk: 'Značenie',
		de: 'Markierung',
		it: 'Marcatura',
		es: 'Marcado',
		tr: 'İşaretler',
		uk: 'Мітки',
		id: 'Tandai',
		da: 'Mærker',
	},
	Date: {
		fr: 'Date',
		sv: 'Datum',
		nl: 'Datum',
		pl: 'Data',
		pt_BR: 'Data',
		ru: 'Дата',
		zh_CN: '日期',
		sk: 'Dátum',
		de: 'Datum',
		it: 'Data',
		es: 'Fecha',
		tr: 'Tarih',
		uk: 'Дата',
		id: 'Tanggal',
		da: 'Dato',
	},
	Greetings: {
		fr: 'Bienvenue',
		sv: 'Hälsningar',
		nl: 'De groeten',
		pl: 'Pozdrowienia',
		pt_BR: 'Saudações',
		ru: 'Привет',
		zh_CN: '你好',
		sk: 'Pozdravom',
		de: 'Grüße',
		it: 'Saluti',
		es: 'Saludos',
		tr: 'Selamlama',
		uk: 'Вітання',
		id: 'Salam',
		da: 'Velkomst',
	},
	Weather: {
		fr: 'Météo',
		sv: 'Väder',
		nl: 'Het weer',
		pl: 'Pogoda',
		pt_BR: 'Tempo',
		ru: 'Погода',
		zh_CN: '天气',
		sk: 'Počasie',
		de: 'Wetter',
		it: 'Tempo',
		es: 'Clima',
		tr: 'Hava durumu',
		uk: 'Погода',
		id: 'Cuaca',
		da: 'Vejr',
	},
	Icon: {
		fr: 'Icône',
		sv: 'Ikon',
		nl: 'Icoon',
		pl: 'Ikona',
		pt_BR: 'Ícone',
		ru: 'Иконка',
		zh_CN: '图标',
		sk: 'Ikona',
		de: 'Symbol',
		it: 'Icona',
		es: 'Icono',
		tr: 'Simge',
		uk: 'Іконка',
		id: 'Icon',
		da: 'Ikon',
	},
	Style: {
		fr: 'Apparence',
		sv: 'Stil',
		nl: 'Stijl',
		pl: 'Styl',
		pt_BR: 'Estilo',
		ru: 'Стиль',
		zh_CN: '风格',
		sk: 'Štýl',
		de: 'Stil',
		it: 'Aspetto',
		es: 'Apariencia',
		tr: 'Görünüm',
		uk: 'Стиль',
		id: 'Gaya',
		da: 'Udseende',
	},
	Large: {
		fr: 'Grands',
		sv: 'Stor',
		nl: 'Groot',
		pl: 'Wielki',
		pt_BR: 'Grande',
		ru: 'Большой',
		zh_CN: '大的',
		sk: 'Veľký',
		de: 'Groß',
		it: 'Largo',
		es: 'Largo',
		tr: 'Büyük',
		uk: 'Великий',
		id: 'Besar',
		da: 'Stor',
	},
	Medium: {
		fr: 'Moyens',
		sv: 'Medium',
		nl: 'Gemiddeld',
		pl: 'Średnia',
		pt_BR: 'Médio',
		ru: 'Средний',
		zh_CN: '中等',
		sk: 'Stredný',
		de: 'Mittel',
		it: 'Medio',
		es: 'Medio',
		tr: 'Orta',
		uk: 'Середній',
		id: 'Sedang',
		da: 'Medium',
	},
	Small: {
		fr: 'Petits',
		sv: 'Liten',
		nl: 'Klein',
		pl: 'Mały',
		pt_BR: 'Pequeno',
		ru: 'Большой',
		zh_CN: '小的',
		sk: 'Malý',
		de: 'Klein',
		it: 'Piccolo',
		es: 'Pequeña',
		tr: 'Küçük',
		uk: 'Маленький',
		id: 'Kecil',
		da: 'Lille',
	},
	Text: {
		fr: 'Texte',
		sv: 'Text',
		nl: 'Tekst',
		pl: 'Tekst',
		pt_BR: 'Texto',
		ru: 'Текст',
		zh_CN: '文本',
		sk: 'Text',
		de: 'Text',
		it: 'Testo',
		es: 'Texto',
		tr: 'Metin',
		uk: 'Текст',
		id: 'Teks',
		da: 'Tekst',
	},
	'Quick Links': {
		fr: 'Liens favoris',
		sv: 'Snabblänkar',
		nl: 'Snelle links',
		pl: 'Szybkie linki',
		pt_BR: 'Links Rápidos',
		ru: 'Быстрые ссылки',
		zh_CN: '快速链接',
		sk: 'Rýchle odkazy',
		de: 'Schnelllinks',
		it: 'Link veloci',
		es: 'Links Favoritos',
		tr: 'Hızlı Linkler',
		uk: 'Швидкі посилання',
		id: 'Tautan Singkat',
		da: 'Hurtig links',
	},
	'Settings icon': {
		fr: 'Icône réglages',
		sv: 'Inställningsikon',
		nl: 'Instellingen icoon',
		pl: 'Ikona ustawień',
		pt_BR: 'Ícone de configuração',
		ru: 'Значок настроек',
		zh_CN: '设置图标',
		sk: 'Ikona nastavení',
		de: 'Einstellungssymbol',
		it: 'Icona Impostazioni',
		es: 'Ícono de la configuración',
		tr: 'Ayarlar simgesi',
		uk: 'Іконка налаштувань',
		id: 'Pengaturan icon',
		da: 'Indstillingsikon',
	},
	'Upload background here': {
		fr: 'Ajoutez votre arrière-plan',
		sv: 'Ladda upp bakgrunden här',
		nl: 'Upload hier achtergrond',
		pl: 'Prześlij tło tutaj',
		pt_BR: 'Suba o seu background aqui',
		ru: 'Загрузите фон здесь',
		zh_CN: '上传背景',
		sk: 'Nahrať pozadie tu',
		de: 'Hier Hintergrund hochladen',
		it: 'Carica lo sfondo qui',
		es: 'Sube el fondo aquí',
		tr: 'Arka planı buraya yükleyin',
		uk: 'Завантажити зображення',
		id: 'Unggah latar belakan disini',
		da: 'Upload baggrund her',
	},
	'Analog clock': {
		fr: 'Horloge analogue',
		sv: 'Analog klocka',
		nl: 'Analoge klok',
		pl: 'Zegar analogowy',
		pt_BR: 'Relógio Analógico',
		ru: 'Аналоговые часы',
		zh_CN: '模拟时钟',
		sk: 'Analógové hodiny',
		de: 'Analoge Uhr',
		it: 'Orologio analogico',
		es: 'Reloj Analógico',
		tr: 'Analog saat',
		uk: 'Аналоговий годинник',
		id: 'Jam Analog',
		da: 'Analog ur',
	},
	'Display Seconds': {
		fr: 'Afficher les secondes',
		sv: 'Visa sekunder',
		nl: 'Weergave seconden',
		pl: 'Wyświetl sekundy',
		pt_BR: 'Mostrar segundos',
		ru: 'Показывать секунды',
		zh_CN: '显示秒',
		sk: 'Zobraziť sekundy',
		de: 'Sekunden anzeigen',
		it: 'Visualizza secondi',
		es: 'Mostrar los segundos',
		tr: 'Saniyeyi göster',
		uk: 'Показувати секунди',
		id: 'Tampilkan keduanya',
		da: 'Vis sekunder',
	},
	Automatic: {
		fr: 'Automatique',
		sv: 'Automatiskt',
		nl: 'Automatisch ',
		pl: 'Automatycznie',
		pt_BR: 'Automático',
		ru: 'Автоматически',
		zh_CN: '自动设置',
		sk: 'Automatické',
		de: 'Automatisch',
		it: 'Automatico',
		es: 'Automático',
		tr: 'Otomatik',
		uk: 'Автоматично',
		id: 'Otomatis',
		da: 'Automatisk',
	},
	Geolocation: {
		fr: 'Géolocalisation',
		sv: 'Geolokalisering',
		nl: 'Locatie',
		pl: 'Geolokalizacja',
		pt_BR: 'Geolocalização',
		ru: 'Геолокация',
		zh_CN: '使用我的位置',
		sk: 'Geolokácia',
		de: 'Geolokalisierung',
		it: 'Geolocalizzazione',
		es: 'Geolocalización',
		tr: 'Coğrafi konum',
		uk: 'Геолокація',
		id: 'Geo-lokasi',
		da: 'Geolokalisering',
	},
	'City not found': {
		fr: 'Ville inconnue',
		sv: 'Staden hittades inte',
		nl: 'Stad niet gevonden',
		pl: 'Zmień miasto',
		pt_BR: 'Cidade não encontrada',
		ru: 'Город не найден',
		zh_CN: '找不到城市',
		sk: 'Mesto nenájdené',
		de: 'Stadt nicht gefunden',
		it: 'Città non trovata',
		es: 'Ciudad no encontrada',
		tr: 'Şehir bulunamadı',
		uk: 'Місто не знайдено',
		id: 'Kota Ditemukan',
		da: 'By ikke fundet',
	},
	'Change city': {
		fr: 'Changer la ville',
		sv: 'Byt stad',
		nl: 'Verander locatie',
		pl: 'Zmień miasto',
		pt_BR: 'Mudar cidade',
		ru: 'Сменить город',
		zh_CN: '更改城市',
		sk: 'Zmeniť mesto',
		de: 'Stadt ändern',
		it: 'Cambia città',
		es: 'Cambiar ciudad',
		tr: 'Şehri değiştir',
		uk: 'Змінити місто',
		id: 'Ubah kota',
		da: 'Ændre by',
	},
	'There was a problem': {
		fr: 'Il y a eu un problème',
		sv: 'Ett fel uppstod',
		nl: 'Er is een probleem',
		pl: 'Wystąpił problem',
		pt_BR: 'Houve um problema',
		ru: 'Возникла проблема',
		zh_CN: '出现错误',
		sk: 'Nastal problém',
		de: 'Ein Problem ist aufgetreten',
		it: "C'è stato un problema",
		es: 'Hubo un problema',
		tr: 'Bir problem vardı',
		uk: 'Виникла проблема',
		id: 'Ada masalah',
		da: 'Der opstod en fejl',
	},
	'Imperial units': {
		fr: 'Unités impériales',
		sv: 'Imperial enheter',
		nl: 'Empirische eenheden',
		pl: 'Jednostki Imperialne',
		pt_BR: 'Unidades imperiais',
		ru: 'Использовать Фаренгейты',
		zh_CN: '英制单位',
		sk: 'Imperiálne jednotky',
		de: 'Imperiale Maßeinheiten',
		it: 'Sistema imperiale',
		es: 'Sistema imperial',
		uk: 'Використовувати шкалу Фаренгейта',
		tr: 'Emperyal birimler',
		id: 'Kisaran Unit',
		da: 'Engelske enheder',
	},
	Forecast: {
		fr: 'Prévisions',
		sv: 'Prognos',
		nl: 'Voorspelling',
		pl: 'Prognoza',
		pt_BR: 'Previsão',
		ru: 'Прогноз',
		zh_CN: '预报',
		sk: 'Predpoveď',
		de: 'Vorhersage',
		it: 'Previsione',
		es: 'Pronóstico',
		tr: 'Hava Durumu',
		uk: 'Прогноз',
		id: 'Ramalan Cuaca',
		da: 'Prognose',
	},
	'Every mornings': {
		fr: 'Les matins',
		sv: 'Varje morgon',
		nl: 'Elke ochtend',
		pl: 'Każdego poranka',
		pt_BR: 'Toda manhã',
		ru: 'Каждое утро',
		zh_CN: '每天早上',
		sk: 'Každé ráno',
		de: 'Jeden Morgen',
		it: 'Ogni mattina',
		es: 'Cada mañana',
		tr: 'Her sabah',
		uk: 'Щоранку',
		id: 'Setiap pagi',
		da: 'Hver morgen',
	},
	'Always show': {
		fr: 'Toujours',
		sv: 'Alltid',
		nl: 'Altijd',
		pl: 'Zawsze',
		pt_BR: 'Mostrar',
		ru: 'Всегда показывать',
		zh_CN: '总是',
		sk: 'Vždy',
		de: 'Immer anzeigen',
		it: 'Sempre',
		es: 'Siempre',
		tr: 'Her zaman göster',
		uk: 'Завжди',
		id: 'Selalu tampilkan',
		da: 'Vis altid',
	},
	'Never show': {
		fr: 'Jamais',
		sv: 'Aldrig',
		nl: 'Nooit',
		pl: 'Nigdy',
		pt_BR: 'Ocultar',
		ru: 'Никогда не показывать',
		zh_CN: '绝不',
		sk: 'Nikdy',
		de: 'Nie anzeigen',
		it: 'Mai',
		es: 'Nunca',
		tr: 'Gösterme',
		uk: 'Ніколи',
		id: 'Belum pernah upload',
		da: 'Vis aldrig',
	},
	Temperature: {
		fr: 'Température',
		sv: 'Temperatur',
		nl: 'Temperatuur',
		pl: 'Temperatura',
		pt_BR: 'Temperatura',
		ru: 'Температура',
		zh_CN: '温度',
		sk: 'Teplota',
		de: 'Temperatur',
		it: 'Temperatura',
		es: 'Temperatura',
		tr: 'Sıcaklık',
		uk: 'Температура',
		id: 'tempratur',
		da: 'Temperatur',
	},
	Actual: {
		fr: 'Réelle',
		sv: 'Faktisk',
		nl: 'Werkelijke',
		pl: 'Rzeczywisty',
		pt_BR: 'Real',
		ru: 'Действительный',
		zh_CN: '实际的',
		sk: 'Reálny',
		de: 'Tatsächlich',
		it: 'Real',
		es: 'Real',
		tr: 'Gerçek',
		uk: 'Дійсна',
		id: 'Aktual',
		da: 'Aktuel',
	},
	'Feels like': {
		fr: 'Ressenti',
		sv: 'Känsla',
		nl: 'Gevoelsmatige',
		pl: 'Uczucie',
		pt_BR: 'Sensação térmica',
		ru: 'Ощущается как',
		zh_CN: '感覺像',
		sk: 'Pocit',
		de: 'Fühlt Sich An Wie',
		it: 'Si Sente Come',
		es: 'Se Siente Como',
		tr: 'Gibi hissettiriyor',
		uk: 'Відчуття',
		id: 'Terasa seperti',
		da: 'Føles som',
	},
	Both: {
		fr: 'Les deux',
		sv: 'Både',
		nl: 'Beide',
		pl: 'Obydwa',
		pt_BR: 'Ambos',
		ru: 'Оба',
		zh_CN: '两个都',
		sk: 'Obaja',
		de: 'Beide',
		it: 'Entrambi',
		es: 'Ambos',
		tr: 'İkisi birden',
		uk: 'Обидві',
		id: 'Keduanya',
		da: 'Begge',
	},
	'Search bar': {
		fr: 'Barre de recherche',
		sv: 'Sökruta',
		nl: 'Zoekbalk',
		pl: 'Pasek wyszukiwania',
		pt_BR: 'Barra de pesquisa',
		ru: 'Строка поиска',
		zh_CN: '搜索框',
		sk: 'VYHĽADÁVACÍ PANEL',
		de: 'Suchleiste',
		it: 'Barra di ricerca',
		es: 'Barra de búsqueda',
		tr: 'Arama çubuğu',
		uk: 'Панель пошуку',
		id: 'Bilah pencarian',
		da: 'Søgefelt',
	},
	'Search engine': {
		fr: 'Moteur de recherche',
		sv: 'Sökmotor',
		nl: 'Zoekmachine',
		pl: 'Wyszukiwarka',
		pt_BR: 'Buscadores',
		ru: 'Поисковая система',
		zh_CN: '搜索引擎',
		sk: 'Vyhľadávač',
		de: 'Suchmaschine',
		it: 'Motore di ricerca',
		es: 'Motor de búsqueda',
		tr: 'Arama motoru',
		uk: 'Пошукова система',
		id: 'Mesin pencari',
		da: 'Søgemaskine',
	},
	Enable: {
		fr: 'Activer',
		sv: 'Aktivera',
		nl: 'Activeren',
		pl: 'Aktywować',
		pt_BR: 'Ativar',
		ru: 'Включить',
		zh_CN: '启用',
		sk: 'Aktivovať',
		de: 'Aktivieren',
		it: 'Abilita',
		es: 'Activar',
		tr: 'Aktif Et',
		uk: 'Активовано',
		id: 'Aktif',
		da: 'Aktiver',
	},
	'Open in new tab': {
		fr: 'Ouvrir dans un nouvel onglet',
		zh_CN: '在新标签页打开链接',
		sv: 'Öppna i ny flik',
		nl: 'Openen in nieuw tabblad',
		pl: 'Otwieraj w nowej karcie',
		pt_BR: 'Abrir em nova aba',
		ru: 'Открыть в новой вкладке',
		sk: 'Otvoriť v novej karte',
		de: 'In einem neuen Tab öffnen',
		it: 'Apri in una nuova scheda',
		es: 'Abrir en una nueva pestaña',
		tr: 'Yeni sekmede aç',
		uk: 'Відкрити в новій вкладці',
		id: 'Buka di tab baru',
		da: 'Åben i et nyt faneblad',
	},
	'URL request': {
		fr: 'URL de requête',
		sv: 'URL begäran',
		nl: 'URL verzoek',
		pl: 'Żądanie adresu URL',
		pt_BR: 'URL de pesquisa',
		ru: 'URL-запрос',
		zh_CN: '网址请求',
		sk: 'Žiadosť o adresu URL',
		de: 'URL Anfrage',
		it: 'Richiesta URL',
		es: 'Solicitud de URL',
		tr: 'URL isteği',
		uk: 'URL запит',
		id: 'URL permintaan',
		da: 'URL-anmodning',
	},
	'%s Not found': {
		fr: '%s Pas trouvé',
		sv: '%s Hittades inte',
		nl: '%s Niet gevonden',
		pl: 'Nie znaleziono %s',
		pt_BR: '% s Não encontrado',
		ru: '% s не найдено',
		zh_CN: '%s 未找到',
		sk: '%s nebol nájdený',
		de: '%s nicht gefunden',
		it: '%s non trovato',
		es: '% s no encontrado',
		tr: '%s Bulunamadı',
		uk: '%s не знайдено',
		id: '%s tidak ditemukan',
		da: '%s ikke fundet',
	},
	'Search query: %s': {
		fr: 'Requête: %s',
		sv: 'Sökfråga: %s',
		nl: 'Zoekopdracht: %s',
		pl: 'Wyszukiwane hasło: %s',
		pt_BR: 'Buscador:% s',
		ru: 'Поисковый запрос: %s',
		zh_CN: '搜索查询：%s',
		sk: 'Vyhľadávací dopyt: %s',
		de: 'Suchanfrage: %s',
		it: 'Ricerca di ricerca: %s',
		es: 'Consulta de búsqueda:% s',
		tr: 'Arama sorgusu: %s',
		uk: 'Пошуковий запит: %s',
		id: 'Pencarian kata kunci %s',
		da: 'Søgeterm: %s',
	},
	Opacity: {
		fr: 'Opacité',
		sv: 'Opacitet',
		nl: 'Dekking',
		pl: 'Nieprzezroczystość',
		pt_BR: 'Opacidade',
		ru: 'Непрозрачность',
		zh_CN: '不透明度',
		sk: 'Nepriehľadnosť',
		de: 'Deckkraft',
		it: 'Opacità',
		es: 'Opacidad',
		tr: 'Opaklık',
		uk: 'Непрозорість',
		id: 'Transparansi',
		da: 'Uigennemsigtighed',
	},
	'Time & Date': {
		fr: 'Date & heure',
		sv: 'Tid och datum',
		nl: 'Datum en tijd',
		pl: 'Data i godzina',
		pt_BR: 'Data & Hora',
		ru: 'Время и дата',
		zh_CN: '时间和日期',
		sk: 'Čas a dátum',
		de: 'Zeit und Datum',
		it: "Ora dell'appuntamento",
		es: 'Fecha & hora',
		tr: 'Saat ve Tarih',
		uk: 'Час & Дата',
		id: 'Waktu & Tanggal',
		da: 'Tid og dato',
	},
	'Custom Style': {
		fr: 'Style personnalisé',
		sv: 'Anpassad stil',
		nl: 'Aangepaste stijl',
		pl: 'Niestandardowy styl',
		pt_BR: 'Estilo Personalizado',
		ru: 'Пользовательский стиль',
		zh_CN: '自定义样式',
		sk: 'Vlastný štýl',
		de: 'Benutzerdefinierter Stil',
		it: 'Stile personalizzato',
		es: 'Estilo personalizado',
		tr: 'Özel Stil',
		uk: 'Власні стилі',
		id: 'Personalisasi Gaya',
		da: 'Tilpasset stil',
	},
	'Type in your custom CSS': {
		fr: 'Entrez votre CSS personnalisé',
		sv: 'Skriv in din anpassade CSS',
		nl: 'Typ uw aangepaste CSS in',
		pl: 'Wpisz swój niestandardowy CSS',
		pt_BR: 'Insira seu CSS personalizado',
		ru: 'Введите свой собственный CSS',
		zh_CN: '输入您的自定义 CSS',
		sk: 'Zadajte svoj vlastný CSS',
		de: 'Geben Sie Ihr benutzerdefiniertes CSS ein',
		it: 'Digita il tuo CSS personalizzato',
		es: 'Escribe aquí tu CSS personalizado',
		tr: "Özel CSS'nizi yazın",
		uk: 'Скопіюйте власний CSS',
		id: 'Ketik CSS khusus Anda',
		da: 'Skriv dit tilpassede CSS',
	},
	'Make cool things happen with CSS. ': {
		fr: 'Tentez de jolies choses en CSS. ',
		sv: 'Få coola saker att hända med CSS. ',
		nl: 'Laat coole dingen gebeuren met CSS. ',
		pl: 'Twórz fajne rzeczy dzięki CSS. ',
		pt_BR: 'Faça coisas legais acontecerem com CSS. ',
		ru: 'Творите с помощью CSS. ',
		zh_CN: '用 CSS 让很酷的事情发生。 ',
		sk: 'Urobte skvelé veci pomocou CSS. ',
		de: 'Machen Sie mit CSS coole Dinge möglich. ',
		it: 'Fai accadere cose interessanti con i CSS. ',
		es: 'Haz que sucedan cosas geniales con CSS. ',
		tr: 'CSS ile harika şeyler yapın. ',
		uk: 'Зробіть круті речі за допомогою CSS. ',
		id: 'Wujudkan hal-hal mewah dengan CSS. ',
		da: 'Få smarte ting til at ske med CSS. ',
	},
	'Check out our ': {
		fr: 'Jetez un oeil à nos ',
		sv: 'Kolla in vår ',
		nl: 'Bekijk onze ',
		pl: 'Sprawdź nasze ',
		pt_BR: 'Confira nosso ',
		ru: 'Посмотрите наши ',
		zh_CN: '看看我们的 ',
		sk: 'Pozrite si naše ',
		de: 'Schauen Sie sich unsere an ',
		it: "Dai un'occhiata al nostro ",
		es: 'Echa un vistazo a nuestro ',
		tr: 'Göz atın ',
		uk: 'Check out our ',
		id: 'Lihat kami ',
		da: 'Tjek vores ',
	},
	'CSS snippets.': {
		fr: 'extraits de CSS.',
		sv: 'CSS-utdrag.',
		nl: 'CSS-fragmenten.',
		pl: 'Fragmenty kodu CSS.',
		pt_BR: 'trechos de CSS.',
		ru: 'CSS-сниппеты.',
		zh_CN: 'CSS 片段。',
		sk: 'úryvky CSS.',
		de: 'CSS-Schnipsel.',
		it: 'frammenti CSS.',
		es: 'Fragmentos de CSS.',
		tr: "Özel CSS'nizi yazın",
		uk: 'CSS snippets.',
		id: 'Cuplikan CSS.',
		da: 'CSS uddrag.',
	},
	'US Date Format': {
		fr: 'Date américaine',
		sv: 'Amerikansk dejt',
		nl: 'Amerikaanse datumnotatie',
		pl: 'Format daty w USA',
		pt_BR: 'Formato de data dos EUA',
		ru: 'Формат даты США',
		zh_CN: '美国日期格式',
		sk: 'Formát dátumu v USA',
		de: 'US-Datumsformat',
		it: 'Formato data USA',
		es: 'Formato de fecha americano',
		tr: 'Amerikan formatı',
		uk: 'Формат дати США',
		id: 'Format Tanggal US',
		da: 'Amerikansk datoformat',
	},
	'12-Hour Time': {
		fr: 'Affichage 12h',
		sv: '12-timmars klocka',
		nl: '12 uur tijd',
		pl: 'Czas 12-godzinny',
		pt_BR: 'Formato de 12 horas',
		ru: '12-часовой формат времени',
		zh_CN: '12小时制',
		sk: '12-hodinový čas',
		de: '12-Stunden Uhrzeit',
		it: 'Sistema orario a 12 ore',
		es: 'Sistema horario de 12 horas',
		tr: '12 Saatlik Zaman',
		uk: '12-годинний формат часу',
		id: 'Waktu 12-Jam',
		da: '12-timers ur',
	},
	'Time zone': {
		fr: 'Fuseau horaire',
		sv: 'Tidszon',
		nl: 'Tijdzone',
		pl: 'Strefa czasowa',
		pt_BR: 'Fuso Horário',
		ru: 'Часовой пояс',
		zh_CN: '时区',
		sk: 'Časové pásmo',
		de: 'Zeitzone',
		it: 'Fuso orario',
		es: 'Uso horario',
		tr: 'Saat dilimi',
		uk: 'Часовий пояс',
		id: 'Zona Waktu',
		da: 'Tidszone',
	},
	Language: {
		fr: 'Langue',
		sv: 'Välj språk',
		nl: 'Kies een taal',
		pl: 'Wybierz Język',
		pt_BR: 'Idioma',
		ru: 'Язык',
		zh_CN: '选择语言',
		sk: 'Vybrať jazyk',
		de: 'Sprache',
		it: 'Lingua',
		es: 'Lenguaje o idioma',
		tr: 'Dil',
		uk: 'Мова',
		id: 'Bahasa',
		da: 'Sprog',
	},
	Greeting: {
		fr: 'Bienvenue',
		sv: 'Hälsning',
		nl: 'Groet',
		pl: 'Powitanie',
		pt_BR: 'Saudação',
		ru: 'Приветствие',
		zh_CN: '问候',
		sk: 'S pozdravom',
		de: 'Gruß',
		it: 'Saluto',
		es: 'Saludo',
		tr: 'Selamlama',
		uk: 'Привітання',
		id: 'Salam',
		da: 'Velkomst',
	},
	Quotes: {
		fr: 'Citations',
		sv: 'Citat',
		nl: 'Citaten',
		pl: 'Cytaty',
		pt_BR: 'Citações',
		ru: 'Цитаты',
		zh_CN: '引号',
		sk: 'Citácie',
		de: 'Zitate',
		it: 'Citazioni',
		es: 'Cotizaciones',
		tr: 'alıntılar',
		uk: 'Цитати',
		id: 'Kutipan',
		da: 'Citater',
	},
	'Always show author': {
		fr: "Toujours afficher l'auteur",
		sv: 'Visa alltid författaren',
		nl: 'Altijd auteur weergeven',
		pl: 'Zawsze pokazuj autora',
		pt_BR: 'Sempre mostrar autor',
		ru: 'Всегда показывать автора',
		zh_CN: '始终显示作者',
		sk: 'Vždy zobraziť autora',
		de: 'Autor immer anzeigen',
		it: "Mostra sempre l'autore",
		es: 'Mostrar siempre el autor',
		tr: 'Yazarı her zaman göster',
		uk: 'Показувати автора',
		id: 'Selalu tunjukkan penulis',
		da: 'Vis altid forfatteren',
	},
	'Quote type': {
		fr: 'Type de citations',
		sv: 'Typ av citat',
		nl: 'Soort citaten',
		pl: 'Rodzaj cytatu',
		pt_BR: 'Tipo de citação',
		ru: 'Вид цитаты',
		zh_CN: '一种报价',
		sk: 'Druh citátu',
		de: 'Art Zitat',
		it: 'Tipo di citazione',
		es: 'Tipo de cotización',
		tr: 'alıntı türü',
		uk: 'вид цитати',
		id: 'Tipe kutipan',
		da: 'Type af citat',
	},
	Classic: {
		fr: 'Classique',
		sv: 'Klassisk',
		nl: 'Klassiek',
		pl: 'Klasyczny',
		pt_BR: 'Clássico',
		ru: 'Классический',
		zh_CN: '经典的',
		sk: 'klasické',
		de: 'Klassisch',
		it: 'Classico',
		es: 'Clásico',
		tr: 'Klasik',
		uk: 'Класичний',
		id: 'Klasik',
		da: 'Klassisk',
	},
	Fonts: {
		fr: 'Polices',
		sv: 'Anpassat teckensnitt',
		nl: 'Aangepast lettertype',
		pl: 'Czcionka Niestandardowa',
		pt_BR: 'Fonte Personalizada',
		ru: 'Пользовательский шрифт',
		zh_CN: '自定义字体',
		sk: 'Vlastné písmo',
		de: 'Benutzerdefinierte Schriftart',
		it: 'Carattere personalizzato',
		es: 'Tipografía personalizada',
		tr: 'Özel Yazı Tipi',
		uk: 'Власний шрифт',
		id: 'Pernolasasi Font',
		da: 'Skrifttyper',
	},
	'Font family': {
		fr: 'Police',
		sv: 'Typsnittsfamilj',
		nl: 'Lettertypefamilie',
		pl: 'Rodzina czcionek',
		pt_BR: 'Família de fontes',
		ru: 'Семейство шрифтов',
		zh_CN: '字体系列',
		sk: 'Rodina písem',
		de: 'Schriftfamilie',
		it: 'Famiglia di font',
		es: 'Tipografía',
		tr: 'Yazı tipi ailesi',
		uk: 'Шрифт',
		id: 'Font family',
		da: 'Skrifttype familie',
	},
	Weight: {
		fr: 'Épaisseur',
		sv: 'Vikt',
		nl: 'Gewicht',
		pl: 'Waga',
		pt_BR: 'Peso',
		ru: 'Масса',
		zh_CN: '重量',
		sk: 'Hmotnosť',
		de: 'Gewicht',
		it: 'Il peso',
		es: 'Peso',
		tr: 'Önem',
		uk: 'Насиченість',
		id: 'Bobot',
		da: 'Vægt',
	},
	Size: {
		fr: 'Taille',
		sv: 'Storlek',
		nl: 'Grootte',
		pl: 'Rozmiar',
		pt_BR: 'Tamanho',
		ru: 'Размер',
		zh_CN: '尺寸',
		sk: 'Veľkosť',
		de: 'Größe',
		it: 'Taglia',
		es: 'Tamaño',
		tr: 'Boyut',
		uk: 'Розмір',
		id: 'Ukuran',
		da: 'størrelse',
	},
	Shadow: {
		fr: 'Ombres',
		sv: 'Shadow',
		nl: 'Shadow',
		pl: 'Shadow',
		pt_BR: 'Shadow',
		ru: 'Тень',
		zh_CN: 'Shadow',
		sk: 'Shadow',
		de: 'Shadow',
		it: 'Shadow',
		es: 'Shadow',
		tr: 'Shadow',
		uk: 'Shadow',
		id: 'Shadow',
		da: 'Skygge',
	},
	'Custom CSS': {
		fr: 'CSS personnalisé',
		sv: 'Anpassad CSS',
		nl: 'Aangepaste CSS',
		pl: 'Niestandardowe CSS',
		pt_BR: 'CSS Personalizado',
		ru: 'Пользовательский CSS',
		zh_CN: '自定义 CSS',
		sk: 'Vlastný CSS',
		de: 'Benutzerdefinierte CSS',
		it: 'CSS personalizzato',
		es: 'CSS personalizado',
		tr: 'Özel CSS',
		uk: 'Власний CSS',
		id: 'Personalisasi CSS',
		da: 'Tilpasset CSS',
	},
	Settings: {
		fr: 'Réglages',
		sv: 'Inställningar',
		nl: 'Instellingen',
		pl: 'Ustawienia',
		pt_BR: 'Configurações',
		ru: 'Настройки',
		zh_CN: '设置',
		sk: 'Nastavenia',
		de: 'Einstellungen',
		it: 'Impostazioni',
		es: 'Configuración',
		tr: 'Ayarlar',
		uk: 'Налаштування',
		id: 'Pengaturan',
		da: 'Indstillinger',
	},
	Import: {
		fr: 'Importer',
		sv: 'Importera',
		nl: 'Importeren',
		pl: 'Import',
		pt_BR: 'Importar',
		ru: 'Импорт',
		zh_CN: '导入设置',
		sk: 'Importovať',
		de: 'Importieren',
		it: 'Importare',
		es: 'Importar',
		tr: 'İçe Aktar',
		uk: 'Імпортувати',
		id: 'Impor',
		da: 'Importér',
	},
	Export: {
		fr: 'Exporter',
		sv: 'Exportera',
		nl: 'Exporteren',
		pl: 'Eksport',
		pt_BR: 'Exportar',
		ru: 'Экспорт',
		zh_CN: '导出设置',
		sk: 'Export',
		de: 'Exportieren',
		it: 'Esportare',
		es: 'Exportar',
		tr: 'Dışa Aktar',
		uk: 'Експортувати',
		id: 'Ekspor',
		da: 'Eksportér',
	},
	Copied: {
		fr: 'Copié',
		sv: 'Kopierat',
		nl: 'Gekopieerd',
		pl: 'Skopiowano',
		pt_BR: 'Copiado',
		ru: 'Скопировано',
		zh_CN: '已复制',
		sk: 'Skopírované',
		de: 'Kopiert',
		it: 'Copiato',
		es: 'Copiado',
		tr: 'Kopyalandı',
		uk: 'Скопійовано',
		id: 'Disalin',
		da: 'Kopieret',
	},
	'Reset settings': {
		fr: 'Réinitialiser les réglages',
		sv: 'Återställ inställningar',
		nl: 'Reset instellingen',
		pl: 'Przywróć ustawienia domyślne',
		pt_BR: 'Redefinir configurações',
		ru: 'Сбросить настройки',
		zh_CN: '重新设置',
		sk: 'Obnoviť nastavenia',
		de: 'Einstellungen zurücksetzen',
		it: 'Impostazioni iniziali',
		es: 'Restablecer configuración',
		tr: 'Ayarları sıfırla',
		uk: 'Скинути налаштування',
		id: 'Setel ulang pengaturan',
		da: 'Nulstil indstillingerne',
	},
	'Made in France with ❤️': {
		fr: 'Fabriqué en France avec ❤️',
		sv: 'Tillverkad i frankrike med ❤️',
		nl: 'Gemaakt in Frankrijk met ❤️',
		pl: 'Stworzone we Francji z ❤️',
		pt_BR: 'Feito na França com ❤️',
		ru: 'Сделано во Франции с ❤️',
		zh_CN: '源自法国 匠❤️打造',
		sk: 'Spravené vo Francúzsku s ❤️',
		de: 'Gemacht in Frankreich mit ❤️',
		it: 'Fatto in Francia con ❤️',
		es: 'Hecho en Francia con ❤️',
		tr: "❤️ ile Fransa'da üretilmiştir",
		uk: 'Створено в Франції з ❤️',
		id: 'Dibuat di Prancis dengan ❤️',
		da: 'Lavet i Frankrig med ❤️',
	},
	by: {
		fr: 'par',
		sv: 'av',
		nl: 'Door',
		pl: 'przez',
		pt_BR: 'por',
		ru: 'Разработчики:',
		zh_CN: '由',
		sk: 'od',
		de: 'von',
		it: 'Da',
		es: 'por',
		tr: 'tarafından',
		uk: 'Розробники:',
		id: 'oleh',
		da: 'af',
	},
	Visit: {
		fr: 'Rendez-vous sur',
		sv: 'Besök',
		nl: 'Bezoek',
		pl: 'Do zobaczenia na',
		pt_BR: 'Veja',
		ru: 'Посетите',
		zh_CN: '访问',
		sk: 'Navštívte',
		de: 'Besuche',
		it: 'Visita',
		es: 'Visita',
		tr: 'Ziyaret Et',
		uk: 'Відвідайте',
		id: 'Kunjungi',
		da: 'Besøg',
	},
	'our website': {
		fr: 'notre site Internet',
		sv: 'vår hemsida',
		nl: 'onze website',
		pl: 'nasza strona',
		pt_BR: 'nosso site',
		ru: 'наш сайт',
		zh_CN: '我们的网站',
		sk: 'našu webstránku',
		de: 'unsere Website',
		it: 'il nostro sito internet',
		es: 'nuestro sitio web',
		tr: 'websitemiz',
		uk: 'наш сайт',
		id: 'Website kami',
		da: 'vores hjemmeside',
	},
	'for infos and donations': {
		fr: 'pour en savoir plus ou faire un don',
		sv: 'för mera information och donationer',
		nl: 'Voor informatie en donaties',
		pl: 'aby dowiedzieć się więcej lub przekazać darowiznę',
		pt_BR: 'para mais informações e doações',
		ru: 'чтобы узнать больше или поддержать разработчиков',
		zh_CN: '以获取更多资讯，或向我们捐款',
		sk: 'pre informácie a dary',
		de: 'für Informationen und Spenden',
		it: 'per info e donazioni',
		es: 'para más info y donaciones',
		tr: 'bilgi ve bağış için',
		uk: 'для отримання додаткової інформації або пожертвування',
		id: 'untuk info dan donasi',
		da: 'for at lære mere eller donere',
	},
}

export const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

export const months = [
	'January',
	'February',
	'March',
	'April',
	'May',
	'June',
	'July',
	'August',
	'September',
	'October',
	'November',
	'December',
]

export const engineLocales = {
	google: {
		base: 'https://www.google%l/search?q=%s',
		fr: '.fr',
		en: '.com',
		ru: '.ru',
		pl: '.pl',
		pt_BR: '.com.br',
		sv: '.se',
		sl: '.sl',
		nl: '.nl',
		zh_CN: '.tw',
		sk: '.sk',
		de: '.de',
		it: '.it',
		es: '.es',
		no: '.no',
		tr: '.com.tr',
		uk: '.com.ua',
		id: '.co.id',
		da: '.dk',
	},
	ddg: {
		base: 'https://duckduckgo.com/?q=%s&kl=%l',
		fr: 'fr-fr',
		en: 'en-US',
		ru: 'ru-ru',
		pl: 'pl-pl',
		pt_BR: 'br-pt',
		sv: 'se-se',
		sl: 'sl-sl',
		nl: 'nl-nl',
		zh_CN: 'cn-zh',
		sk: 'sk-sk',
		de: 'de-de',
		it: 'it-it',
		es: 'es-es',
		no: 'no-no',
		tr: 'tr-tr',
		uk: 'uk-UA',
		id: 'id-ID',
		da: 'dk-da',
	},
	startpage: {
		base: 'https://www.startpage.com/do/search?query=%s&language=%l',
		fr: 'francais',
		en: 'english',
		ru: 'russian',
		pl: 'polski',
		pt_BR: 'br-pt',
		sv: 'svenska',
		sl: 'sl-sl',
		nl: 'nl-nl',
		zh_CN: 'cn-zh',
		sk: 'sk-sk',
		de: 'de-de',
		it: 'italiano',
		es: 'es-es',
		no: 'norsk',
		tr: 'tr-tr',
		uk: '',
		id: '',
		da: 'dansk',
	},
	qwant: {
		base: 'https://www.qwant.com/?q=%s&r=%l',
		fr: 'FR&sr=fr',
		en: 'US&sr=en',
		ru: 'RU&sr=ru',
		pl: 'PL&sr=pl',
		pt_BR: 'BR&sr=pt',
		sv: 'SE&sr=sv',
		sl: 'SL&sr=sl',
		nl: 'NL&sr=nl',
		zh_CN: 'SG&sr=en',
		sk: 'en&sr=en',
		de: 'DE&sr=de',
		it: 'IT&sr=it',
		es: 'ES&sr=es',
		no: 'NO&sr=nb',
		tr: '', //qwant not available in Turkey
		da: 'DK&sr=da',
	},
	yahoo: {
		base: 'https://%lsearch.yahoo.com/search?q=%s',
		fr: 'fr.',
		en: '',
		ru: 'ru.',
		pl: 'pl.',
		pt_BR: 'br.',
		sv: 'se.',
		sl: 'sl.',
		nl: 'nl.',
		zh_CN: '',
		sk: '',
		de: 'de.',
		it: 'it.',
		es: 'es.',
		no: 'no.',
		tr: 'tr.',
		uk: 'ua.',
		id: 'id.',
		da: 'dk.',
	},
	bing: {
		base: 'https://www.bing.com/search?q=%s&cc=%l',
		fr: 'fr',
		en: '',
		ru: 'ru',
		pl: 'pl',
		pt_BR: 'br',
		sv: 'se',
		sl: 'sl',
		nl: 'nl',
		zh_CN: '',
		sk: 'sk',
		de: 'de',
		it: 'it',
		es: 'es',
		no: 'no',
		tr: 'tr',
		uk: '',
		id: 'id',
		da: 'da',
	},
	brave: {
		base: 'https://search.brave.com/search?q=%s',
	},
	ecosia: {
		base: 'https://www.ecosia.org/search?q=%s',
	},
	lilo: {
		base: 'https://search.lilo.org/?q=%s',
	},
}
